### ISSUE TITLE
支持自动检查版本更新

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#101]
环境变量 `AUTO_DERBY_CHECK_UPDATE=true` 时自动检查更新，启动器默认启用

在项目中加个 version 文件然后当前 version 和 master 进行比较就行

**Comment by fatinghenji** [comment]
好诶，终于不用自己每次pull了

**Comment by NateScarlet** [comment]
自动检查而已 更新还是得手动更新

自动更新需要写个更新器 感觉没太大必要

**Comment by NateScarlet** [comment]
主要是因为现在如果不是 git 仓库日志里面就没版本
