### ISSUE TITLE
在目标达成回数不足提醒处卡住

### ISSUE THREAD

**Issue by love57232** [NateScarlet/auto-derby#104]
![last_screenshot local](https://user-images.githubusercontent.com/69254947/125494364-37c0432a-0abe-442b-898e-a613db7d4fda.png)

**Comment by NateScarlet** [comment]
横向多了2像素 我可以手动裁掉

不过最好还是用 last_screenshot.local.png

**Comment by love57232** [comment]
有的 目前我是有设定那个 但有时候可以有时候又会跳出 您大概是权重调多少呢 谢谢

> 這個我都是手工跑的，或者你可以用什麼插件提高G1權重？

**Comment by fatinghenji** [comment]
> 有的 目前我是有设定那个 但有时候可以有时候又会跳出 您大概是权重调多少呢 谢谢
> 
> > 這個我都是手工跑的，或者你可以用什麼插件提高G1權重？

**這個我都是手工跑的**

**Comment by NateScarlet** [comment]
提高 G1 权重现在有 prefer_g1 插件

**Comment by love57232** [comment]
> 提高 G1 权重现在有 prefer_g1 插件

有的 有加入插件 有可能是预测排名不到预期所以停住吧 没关系我再调适看看 谢谢你们

**Comment by NateScarlet** [comment]
这个提醒和插件没关系 只是还没支持处理这个提醒而已

只是 @fatinghenji 说要手动所以我提一下

**Comment by NateScarlet** [comment]
加了这个菜单自动点取消 不过因为我没有小栗帽没法测试

你们试一下 92bc7ecbbe53c419ffcf446ccf40e9c2cef3a730

**Comment by love57232** [comment]
好的 我等等試試
