### ISSUE TITLE
afk 插件

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#105]
无人值守模式

- [x] 比赛前永不暂停
- [x] 未知文本选可能性最高的，如果识别结果错了就让它崩溃
- [x] 未知事件选第一项
- [x] 抓娃娃随便抓，抓不到就算了

**Comment by danyosate** [comment]
□自动抓娃娃

**Comment by nnsy** [comment]
哈哈，抓娃娃才是乐趣所在啊

**Comment by NateScarlet** [comment]
自动抓空气实现了 微调了第一次 测试需要看脸……

**Comment by NateScarlet** [comment]
开发分支新增插件 no_ocr_prompt

**Comment by NateScarlet** [comment]
开发分支新增插件 no_event_prompt

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/126698873-fc81456b-6f22-447a-970e-174fd9db8277.png)
自动抓娃娃3次都抓到了
