### ISSUE TITLE
直接通过比赛列表识别比赛

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#106]
不点开比赛详情直接识别比赛

这样操作少 纯白背景准确度应该也高 就是需要先定位选项位置

**Comment by yourlies** [comment]
非固定位置的文字识别，只要位置有偏差，准确率就会降低，我之前识别技能就是这样，识别了好几天的技能，过几天又一直识别不了，这种感觉还是hash粗筛+直接比图细筛，是最好的

**Comment by NateScarlet** [comment]
我实现了 没出现你说的问题 你说的问题应该是你没加测试的原因
