### ISSUE TITLE
在线插件生成器

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#109]
可以搞一个网页应用来根据需求自动生成插件 方便小白用户进行简单的自定义配置

- [ ] 指定比赛调整评分
- [ ] 自定义指定日期的期望属性

不过要做也是开个新仓库 用的是完全不同的技术栈 而且用户直接网页就可以用不需要一起下载了

**Comment by fatinghenji** [comment]
呜呜呜呜呜呜呜呜呜
太好了

**Comment by yourlies** [comment]
js是可以直接生成文件下载的，应该，vuejs这种，简单轻松

**Comment by NateScarlet** [comment]
初版上线了 支持生成自定义比赛插件

https://natescarlet.github.io/auto-derby-plugin-generator/
