### ISSUE TITLE
OCR 多個數字被識別為一個字

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#113]
![last_screenshot local](https://user-images.githubusercontent.com/16464896/126111243-2d1ef2b4-ee54-438c-bd25-d47fd5b41ac8.png)
![圖片](https://user-images.githubusercontent.com/16464896/126111306-614f1663-330b-4b18-a4c2-c36c52506b5d.png)

**Comment by NateScarlet** [comment]
分字有问题

**Comment by NateScarlet** [comment]
把子放大一点再识别就好了 2455b5ca64491bf095ad5e26ed356743381edfff
