### ISSUE TITLE
未胜利战滑动点击位置错误

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#115]
![last_screenshot local](https://user-images.githubusercontent.com/37131177/126594188-36453bc4-3156-4877-b6fd-910fe45be03e.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6860166/auto_derby.log)

**Comment by NateScarlet** [comment]
你这处理到一半手动终止 何来的错误

滑动完会点一下旁边来终止惯性

**Comment by fatinghenji** [comment]
我盯着屏幕看的，没有选择新的比赛。
正常的步骤应该不是滑动——点击新的比赛——识别——判定
它现在是滑动——点击（错误位置）——识别——判定
造成的结果是一直在识别第一场比赛
```
……
INFO  [2021-07-22 13:36:33]:auto_derby.single_mode.race:875: image match: Race<中山 dart 1200m Not-Winning ジュニア級未勝利戦>
……
INFO  [2021-07-22 13:36:35]:auto_derby.single_mode.race:875: image match: Race<中山 dart 1200m Not-Winning ジュニア級未勝利戦>
……
INFO  [2021-07-22 13:36:37]:auto_derby.single_mode.race:875: image match: Race<中山 turf 1200m Not-Winning ジュニア級未勝利戦>
……
INFO  [2021-07-22 13:36:38]:auto_derby.single_mode.race:875: image match: Race<中山 turf 1200m Not-Winning ジュニア級未勝利戦>

```
我才手动停止的

**Comment by NateScarlet** [comment]
> 造成的结果是一直在识别第一场比赛

日志里面没有重复识别

![image](https://user-images.githubusercontent.com/21083014/126595042-91e983a7-c295-40ff-b8f1-8ea5a1aefb4a.png)

**Comment by fatinghenji** [comment]
我重新跑一个日志，稍等

**Comment by NateScarlet** [comment]
> 正常的步骤应该不是滑动——点击新的比赛——识别——判定

开发分支不会点击每个比赛 遇到要跑的才会选

**Comment by fatinghenji** [comment]
啊，看明白了，确实是这样

**Comment by NateScarlet** [comment]
一个比赛识别一次以上是正常的 因为滑动量设的比较小 不然可能滑过了 只要不无限循环就行
