### ISSUE TITLE
OCR fails. It seems to often take the "ジ" as "シ".

### ISSUE THREAD

**Issue by waraiotoko2501h** [NateScarlet/auto-derby#12]
Thanks for the response the other day.
The program was working fine, but the current version is failing to OCR.

OCR frequently mistakes "ジ" for "シ".

Is there something wrong with my settings?
I have not changed any settings in NVIDIA Control Panel -> Manage 3D Settings. (Factory default)

Does the graphics board or Windows settings affect OCR?

TEST VERSION fed9276f2a02a770a3116211a3ce42b7bde10c9b
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6589477/launcher.log)

![screenshot_1622701278](https://user-images.githubusercontent.com/751160/120596976-663b8700-c47f-11eb-8c0a-90dd1e4f6d7b.png)
![screenshot_1622701289](https://user-images.githubusercontent.com/751160/120596989-69cf0e00-c47f-11eb-9a51-a744c95c8332.png)

If you need any other logs or screenshots, please let me know.

**Comment by NateScarlet** [comment]
Try add 

```json
"1800f800f801f001e0000f001ff03ff81cfc007f803fe01ffc07fe01fe001c00": "ジ"
```

to `ocr_labels.json`

**Comment by waraiotoko2501h** [comment]
Thanks.  It worked.
But immediately after, I was asked for input.
I'm frequently asked to enter numbers.
// The "launcher.cmd" will not prompt you for input.

**Comment by NateScarlet** [comment]
This project is using a hash based OCR, so gpu setting should not be related.

For unknown reason(maybe clear text setting?) your text is rendered in different pixel value from my samples. 
Manually label them should work.

**Comment by NateScarlet** [comment]
There seems a launcher bug that not allow standard input, you can use the command line directly for now.

And if you finished the text labelling, please send a PR with updated `ocr_labels.json`, so others don't have to do it again.

**Comment by waraiotoko2501h** [comment]
I see. I understand.

Is there a best way to enter the hash manually?
How did you come up with this hash?
> "1800f800f801f001e0000f001ff03ff81cfc007f803fe01ffc07fe01fe001c00": "ジ"

**Comment by NateScarlet** [comment]
> Is there a best way to enter the hash manually?
If you run `py -3.8 -m auto_derby nurturing` directly from a admin command prompt, you can input text in terminal.

https://github.com/NateScarlet/auto-derby/blob/fed9276f2a02a770a3116211a3ce42b7bde10c9b/auto_derby/ocr.py#L77-L82

> How did you come up with this hash?
You can find it in debug log. current similarity threshold for ocr is 0.8, but `シ` has similarity 0.93 with `ジ` .

**Comment by NateScarlet** [comment]
You can also input through launcher now, The text prompt somehow show after input, it should be show before input.

**Comment by waraiotoko2501h** [comment]
I've been adding the hashes manually.
However, it is still very difficult to distinguish between "ジュニアクラス(junior class)" and "シニアクラス(senior class)".

![2021-06-04_04h14_34](https://user-images.githubusercontent.com/751160/120701623-092aea00-c4ee-11eb-9ce9-6aa4a153e091.png)
It seems that the hash of "ジ" registered for the junior class is also recognized as "ジ" for the senior class.

This may not be a good solution, but I solved it as follows.
https://github.com/NateScarlet/auto-derby/blob/451e2122cb8e252c9f4f646d4e7f866576a1c338/auto_derby/single_mode/context.py#L38

```
    year = {
        'ジュニア級': 1,
        'シュニア級': 1,        
        'クラシック級': 2,
        'シニア級': 3,
        'ジニア級': 3,
    }[year_text]
```

**Comment by NateScarlet** [comment]
this 3800...3c00 hash not exists in my `ocr_labels.json`.
you should just correct lable data

**Comment by NateScarlet** [comment]
you can check image for that hash in `ocr_images.local` folder

**Comment by waraiotoko2501h** [comment]
After several attempts, adding it to ocr_labels.json alone did not solve the problem.

3800.... .3c00 hash will be similarity=1.000 for both when junior class and senior class.

"シ" or "ジ" problem is can happen with any other hash.

For both the senior and junior classes, these hashes will have similarity=1.000.
In other words, if I register as "ジ" in the "ジュニア級", it will be recognized as "ジ" in the "シニア級" and you will get a Key error.

There may be others.
```
  "1800f800f801f001e0000f001ff03ff81cfc007f803fe01ffc07fe01fe001c00": "ジ",
  "3800f800f801f001e0010f001f703ff83cfc007e803fe01ffc0ffe01fe003c00": "ジ",
  "1800f800f801f001e0000f001ff03ff81cfe007f803fe01ffc07fe01fe001c00": "シ",
  "fc01fc01f801c0000f001f603ff83cfc10fe007fc03ff01ffc07fe01fe003c00": "シ",
```

I'm attaching it in case you need it.
[ocr.zip](https://github.com/NateScarlet/auto-derby/files/6596022/ocr.zip)

I understand a little bit about how this program works, but...
It seems like a difficult problem to solve.
I'm going to try to find out if it's a problem with clear type text.

Thank you for your support.
(My English is not very good, I apologize for that.)

**Comment by NateScarlet** [comment]
![image](https://user-images.githubusercontent.com/21083014/120757092-add71700-c542-11eb-830e-c7e42003ac35.png)

The top-right `゛` is not included in ocr image, you should not mark this as `ジ`
Base on given image, these hash should all be labeled as シ

Are you sure you see these hash while ジ is displaying ?
Maybe image pre-processing is incorrectlly removed `゛`  from image,
I need a reproducable case (a screenshot that ocr recognize ジ as シ) to work on.

**Comment by waraiotoko2501h** [comment]
> Are you sure you see these hash while ジ is displaying ?

yes.
Please wait while I recreate the situation.

**Comment by NateScarlet** [comment]
I found the fisrt screenshot of this issue is the reproducable case, i could just run test against it

I will work on this tonight

**Comment by waraiotoko2501h** [comment]
P.S.
The clear type text had nothing to do with it.
I toggled between enabled and disabled, rebooted, and tried again, but there was no change in the hash value.

**Comment by waraiotoko2501h** [comment]
1. 「シ」
![2021-06-04_16h07_37](https://user-images.githubusercontent.com/751160/120760651-4ecbcf00-c54f-11eb-8429-783b4ae86145.png)

Immediately after
2. 「゛ュ」
![2021-06-04_16h09_23](https://user-images.githubusercontent.com/751160/120761047-be41be80-c54f-11eb-947c-9d0ee62be608.png)

screenshot
![screenshot_1622790467](https://user-images.githubusercontent.com/751160/120760670-555a4680-c54f-11eb-994f-9d5bc92c7e9a.png)

[pastelog.txt](https://github.com/NateScarlet/auto-derby/files/6596492/pastelog.txt)

**Comment by fatinghenji** [comment]
My solution to this problem:
1. Use the mobile terminal of Google Translate, select Japanese as the original language, and output the language at will.
2. Select handwriting input, and then find the most similar text on the screen for handwriting.
3. Try to enter a whole sentence as much as possible.
4. Google's intelligent error correction will complete the mistakes you may make.
5. Use instant messaging software like discord or telegram to send the intelligently completed text to the computer.
6. Copy and paste the corresponding text on the computer.

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/120804683-88b0cb80-c577-11eb-87a8-40ccf57e7c92.png)

The `゛` become very blurry, image pre-processing need improve

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/120812665-c7e31a80-c57f-11eb-8657-08c000a7eae9.png)

resize + sharpen can solve this problem
