### ISSUE TITLE
laucher无法启动脚本

### ISSUE THREAD

**Issue by zjj871114037** [NateScarlet/auto-derby#128]
<details>
已启动脚本，输出文件为 C:\Users\HASEE\Desktop\auto-derby-master\launcher.log
PS>TerminatingError(Add-Type):“已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: (0) : 未能找到源文件“C:\windows\TEMP\lwkgypog.0.cs”

(1) : using Microsoft.Win32; using System.Collections.ObjectModel; using System.ComponentModel;  namespace NateScarlet.AutoDerby {     public class JobOption     {         public string Label         { get; set; }          public string Value         { get; set; }     }      public class JobOptions : ObservableCollection<JobOption>     {         public JobOptions()         {             Add(new JobOption()             {                 Label = "Nurturing",                 Value = "nurturing",             });             Add(new JobOption()             {                 Label = "Champions meeting",                 Value = "champions_meeting",             });             Add(new JobOption()             {                 Label = "Team race",                 Value = "team_race",             });             Add(new JobOption()             {                 Label = "Daily race: Money",                 Value = "daily_race_money",             });             Add(new JobOption()             {                 Label = "Daily race: SP",                 Value = "daily_race_sp",             });             Add(new JobOption()             {                 Label = "Legend race",                 Value = "legend_race",             });             Add(new JobOption()             {                 Label = "Roulette derby",                 Value = "roulette_derby",             });         }     }      public class DataContext : INotifyPropertyChanged     {         public event PropertyChangedEventHandler PropertyChanged;         protected virtual void OnPropertyChanged(string propertyName)         {             PropertyChangedEventHandler handler = PropertyChanged;             if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));         }          private const string RegistryPath = @"Software\NateScarlet\auto-derby";          private RegistryKey key;          public DataContext()         {             this.key = Registry.CurrentUser.OpenSubKey(RegistryPath, true);             if (this.key == null)             {                 this.key = Registry.CurrentUser.CreateSubKey(RegistryPath);             }              this.JobOptions1 = new JobOptions();         }         ~DataContext()         {             key.Dispose();         }          public string DefaultSingleModeChoicesDataPath;         public string SingleModeChoicesDataPath         {             get             {                 return (string)key.GetValue("SingleModeChoicesDataPath", DefaultSingleModeChoicesDataPath);             }             set             {                 key.SetValue("SingleModeChoicesDataPath", value);                 OnPropertyChanged("SingleModeChoicesDataPath");             }         }          public string DefaultPythonExecutablePath;         public string PythonExecutablePath         {             get             {                 return (string)key.GetValue("PythonExecutablePath", DefaultPythonExecutablePath);             }             set             {                 key.SetValue("PythonExecutablePath", value);                 OnPropertyChanged("PythonExecutablePath");             }         }          public int PauseIfRaceOrderGt         {             get             {                 return (int)key.GetValue("PauseIfRaceOrderGt", 5);             }             set             {                 key.SetValue("PauseIfRaceOrderGt", value, RegistryValueKind.DWord);                 OnPropertyChanged("PauseIfRaceOrderGt");             }         }          public string Plugins         {             get             {                 return (string)key.GetValue("Plugins", "");             }             set             {                 key.SetValue("Plugins", value);                 OnPropertyChanged("Plugins");             }         }          public string TargetTrainingLevels         {             get             {                 return (string)key.GetValue("TargetTrainingLevels", "5,3,3,0,");             }             set             {                 key.SetValue("TargetTrainingLevels", value);                 OnPropertyChanged("TargetTrainingLevels");             }         }          public string ADBAddress         {             get             {                 return (string)key.GetValue("ADBAddress", "");             }             set             {                 key.SetValue("ADBAddress", value);                 OnPropertyChanged("ADBAddress");             }         }          public bool Debug         {             get             {                 return (int)key.GetValue("Debug", 1) != 0;             }             set             {                 key.SetValue("Debug", value, RegistryValueKind.DWord);                 OnPropertyChanged("Debug");             }         }          public bool CheckUpdate         {             get             {                 return (int)key.GetValue("CheckUpdate", 1) != 0;             }             set             {                 key.SetValue("CheckUpdate", value, RegistryValueKind.DWord);                 OnPropertyChanged("CheckUpdate");             }         }           public string Job         {             get             {                 return (string)key.GetValue("Job", "nurturing");             }             set             {                 key.SetValue("Job", value);                 OnPropertyChanged("Job");             }         }          public JobOptions JobOptions1         { get; set; }     } }
”
>> TerminatingError(Add-Type):“已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: (0) : 未能找到源文件“C:\windows\TEMP\lwkgypog.0.cs”

(1) : using Microsoft.Win32; using System.Collections.ObjectModel; using System.ComponentModel;  namespace NateScarlet.AutoDerby {     public class JobOption     {         public string Label         { get; set; }          public string Value         { get; set; }     }      public class JobOptions : ObservableCollection<JobOption>     {         public JobOptions()         {             Add(new JobOption()             {                 Label = "Nurturing",                 Value = "nurturing",             });             Add(new JobOption()             {                 Label = "Champions meeting",                 Value = "champions_meeting",             });             Add(new JobOption()             {                 Label = "Team race",                 Value = "team_race",             });             Add(new JobOption()             {                 Label = "Daily race: Money",                 Value = "daily_race_money",             });             Add(new JobOption()             {                 Label = "Daily race: SP",                 Value = "daily_race_sp",             });             Add(new JobOption()             {                 Label = "Legend race",                 Value = "legend_race",             });             Add(new JobOption()             {                 Label = "Roulette derby",                 Value = "roulette_derby",             });         }     }      public class DataContext : INotifyPropertyChanged     {         public event PropertyChangedEventHandler PropertyChanged;         protected virtual void OnPropertyChanged(string propertyName)         {             PropertyChangedEventHandler handler = PropertyChanged;             if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));         }          private const string RegistryPath = @"Software\NateScarlet\auto-derby";          private RegistryKey key;          public DataContext()         {             this.key = Registry.CurrentUser.OpenSubKey(RegistryPath, true);             if (this.key == null)             {                 this.key = Registry.CurrentUser.CreateSubKey(RegistryPath);             }              this.JobOptions1 = new JobOptions();         }         ~DataContext()         {             key.Dispose();         }          public string DefaultSingleModeChoicesDataPath;         public string SingleModeChoicesDataPath         {             get             {                 return (string)key.GetValue("SingleModeChoicesDataPath", DefaultSingleModeChoicesDataPath);             }             set             {                 key.SetValue("SingleModeChoicesDataPath", value);                 OnPropertyChanged("SingleModeChoicesDataPath");             }         }          public string DefaultPythonExecutablePath;         public string PythonExecutablePath         {             get             {                 return (string)key.GetValue("PythonExecutablePath", DefaultPythonExecutablePath);             }             set             {                 key.SetValue("PythonExecutablePath", value);                 OnPropertyChanged("PythonExecutablePath");             }         }          public int PauseIfRaceOrderGt         {             get             {                 return (int)key.GetValue("PauseIfRaceOrderGt", 5);             }             set             {                 key.SetValue("PauseIfRaceOrderGt", value, RegistryValueKind.DWord);                 OnPropertyChanged("PauseIfRaceOrderGt");             }         }          public string Plugins         {             get             {                 return (string)key.GetValue("Plugins", "");             }             set             {                 key.SetValue("Plugins", value);                 OnPropertyChanged("Plugins");             }         }          public string TargetTrainingLevels         {             get             {                 return (string)key.GetValue("TargetTrainingLevels", "5,3,3,0,");             }             set             {                 key.SetValue("TargetTrainingLevels", value);                 OnPropertyChanged("TargetTrainingLevels");             }         }          public string ADBAddress         {             get             {                 return (string)key.GetValue("ADBAddress", "");             }             set             {                 key.SetValue("ADBAddress", value);                 OnPropertyChanged("ADBAddress");             }         }          public bool Debug         {             get             {                 return (int)key.GetValue("Debug", 1) != 0;             }             set             {                 key.SetValue("Debug", value, RegistryValueKind.DWord);                 OnPropertyChanged("Debug");             }         }          public bool CheckUpdate         {             get             {                 return (int)key.GetValue("CheckUpdate", 1) != 0;             }             set             {                 key.SetValue("CheckUpdate", value, RegistryValueKind.DWord);                 OnPropertyChanged("CheckUpdate");             }         }           public string Job         {             get             {                 return (string)key.GetValue("Job", "nurturing");             }             set             {                 key.SetValue("Job", value);                 OnPropertyChanged("Job");             }         }          public JobOptions JobOptions1         { get; set; }     } }
”
>> TerminatingError(Add-Type):“已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: (0) : 未能找到源文件“C:\windows\TEMP\lwkgypog.0.cs”

(1) : using Microsoft.Win32; using System.Collections.ObjectModel; using System.ComponentModel;  namespace NateScarlet.AutoDerby {     public class JobOption     {         public string Label         { get; set; }          public string Value         { get; set; }     }      public class JobOptions : ObservableCollection<JobOption>     {         public JobOptions()         {             Add(new JobOption()             {                 Label = "Nurturing",                 Value = "nurturing",             });             Add(new JobOption()             {                 Label = "Champions meeting",                 Value = "champions_meeting",             });             Add(new JobOption()             {                 Label = "Team race",                 Value = "team_race",             });             Add(new JobOption()             {                 Label = "Daily race: Money",                 Value = "daily_race_money",             });             Add(new JobOption()             {                 Label = "Daily race: SP",                 Value = "daily_race_sp",             });             Add(new JobOption()             {                 Label = "Legend race",                 Value = "legend_race",             });             Add(new JobOption()             {                 Label = "Roulette derby",                 Value = "roulette_derby",             });         }     }      public class DataContext : INotifyPropertyChanged     {         public event PropertyChangedEventHandler PropertyChanged;         protected virtual void OnPropertyChanged(string propertyName)         {             PropertyChangedEventHandler handler = PropertyChanged;             if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));         }          private const string RegistryPath = @"Software\NateScarlet\auto-derby";          private RegistryKey key;          public DataContext()         {             this.key = Registry.CurrentUser.OpenSubKey(RegistryPath, true);             if (this.key == null)             {                 this.key = Registry.CurrentUser.CreateSubKey(RegistryPath);             }              this.JobOptions1 = new JobOptions();         }         ~DataContext()         {             key.Dispose();         }          public string DefaultSingleModeChoicesDataPath;         public string SingleModeChoicesDataPath         {             get             {                 return (string)key.GetValue("SingleModeChoicesDataPath", DefaultSingleModeChoicesDataPath);             }             set             {                 key.SetValue("SingleModeChoicesDataPath", value);                 OnPropertyChanged("SingleModeChoicesDataPath");             }         }          public string DefaultPythonExecutablePath;         public string PythonExecutablePath         {             get             {                 return (string)key.GetValue("PythonExecutablePath", DefaultPythonExecutablePath);             }             set             {                 key.SetValue("PythonExecutablePath", value);                 OnPropertyChanged("PythonExecutablePath");             }         }          public int PauseIfRaceOrderGt         {             get             {                 return (int)key.GetValue("PauseIfRaceOrderGt", 5);             }             set             {                 key.SetValue("PauseIfRaceOrderGt", value, RegistryValueKind.DWord);                 OnPropertyChanged("PauseIfRaceOrderGt");             }         }          public string Plugins         {             get             {                 return (string)key.GetValue("Plugins", "");             }             set             {                 key.SetValue("Plugins", value);                 OnPropertyChanged("Plugins");             }         }          public string TargetTrainingLevels         {             get             {                 return (string)key.GetValue("TargetTrainingLevels", "5,3,3,0,");             }             set             {                 key.SetValue("TargetTrainingLevels", value);                 OnPropertyChanged("TargetTrainingLevels");             }         }          public string ADBAddress         {             get             {                 return (string)key.GetValue("ADBAddress", "");             }             set             {                 key.SetValue("ADBAddress", value);                 OnPropertyChanged("ADBAddress");             }         }          public bool Debug         {             get             {                 return (int)key.GetValue("Debug", 1) != 0;             }             set             {                 key.SetValue("Debug", value, RegistryValueKind.DWord);                 OnPropertyChanged("Debug");             }         }          public bool CheckUpdate         {             get             {                 return (int)key.GetValue("CheckUpdate", 1) != 0;             }             set             {                 key.SetValue("CheckUpdate", value, RegistryValueKind.DWord);                 OnPropertyChanged("CheckUpdate");             }         }           public string Job         {             get             {                 return (string)key.GetValue("Job", "nurturing");             }             set             {                 key.SetValue("Job", value);                 OnPropertyChanged("Job");             }         }          public JobOptions JobOptions1         { get; set; }     } }
”
已停止该运行的命令，因为首选项变量“ErrorActionPreference”或通用参数设置为 Stop: (0) : 未能找到源文件“C:\windows\TEMP\lwkgypog.0.cs”

(1) : using Microsoft.Win32; using System.Collections.ObjectModel; using System.ComponentModel;  namespace NateScarlet.AutoDerby {     public class JobOption     {         public string Label         { get; set; }          public string Value         { get; set; }     }      public class JobOptions : ObservableCollection<JobOption>     {         public JobOptions()         {             Add(new JobOption()             {                 Label = "Nurturing",                 Value = "nurturing",             });             Add(new JobOption()             {                 Label = "Champions meeting",                 Value = "champions_meeting",             });             Add(new JobOption()             {                 Label = "Team race",                 Value = "team_race",             });             Add(new JobOption()             {                 Label = "Daily race: Money",                 Value = "daily_race_money",             });             Add(new JobOption()             {                 Label = "Daily race: SP",                 Value = "daily_race_sp",             });             Add(new JobOption()             {                 Label = "Legend race",                 Value = "legend_race",             });             Add(new JobOption()             {                 Label = "Roulette derby",                 Value = "roulette_derby",             });         }     }      public class DataContext : INotifyPropertyChanged     {         public event PropertyChangedEventHandler PropertyChanged;         protected virtual void OnPropertyChanged(string propertyName)         {             PropertyChangedEventHandler handler = PropertyChanged;             if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));         }          private const string RegistryPath = @"Software\NateScarlet\auto-derby";          private RegistryKey key;          public DataContext()         {             this.key = Registry.CurrentUser.OpenSubKey(RegistryPath, true);             if (this.key == null)             {                 this.key = Registry.CurrentUser.CreateSubKey(RegistryPath);             }              this.JobOptions1 = new JobOptions();         }         ~DataContext()         {             key.Dispose();         }          public string DefaultSingleModeChoicesDataPath;         public string SingleModeChoicesDataPath         {             get             {                 return (string)key.GetValue("SingleModeChoicesDataPath", DefaultSingleModeChoicesDataPath);             }             set             {                 key.SetValue("SingleModeChoicesDataPath", value);                 OnPropertyChanged("SingleModeChoicesDataPath");             }         }          public string DefaultPythonExecutablePath;         public string PythonExecutablePath         {             get             {                 return (string)key.GetValue("PythonExecutablePath", DefaultPythonExecutablePath);             }             set             {                 key.SetValue("PythonExecutablePath", value);                 OnPropertyChanged("PythonExecutablePath");             }         }          public int PauseIfRaceOrderGt         {             get             {                 return (int)key.GetValue("PauseIfRaceOrderGt", 5);             }             set             {                 key.SetValue("PauseIfRaceOrderGt", value, RegistryValueKind.DWord);                 OnPropertyChanged("PauseIfRaceOrderGt");             }         }          public string Plugins         {             get             {                 return (string)key.GetValue("Plugins", "");             }             set             {                 key.SetValue("Plugins", value);                 OnPropertyChanged("Plugins");             }         }          public string TargetTrainingLevels         {             get             {                 return (string)key.GetValue("TargetTrainingLevels", "5,3,3,0,");             }             set             {                 key.SetValue("TargetTrainingLevels", value);                 OnPropertyChanged("TargetTrainingLevels");             }         }          public string ADBAddress         {             get             {                 return (string)key.GetValue("ADBAddress", "");             }             set             {                 key.SetValue("ADBAddress", value);                 OnPropertyChanged("ADBAddress");             }         }          public bool Debug         {             get             {                 return (int)key.GetValue("Debug", 1) != 0;             }             set             {                 key.SetValue("Debug", value, RegistryValueKind.DWord);                 OnPropertyChanged("Debug");             }         }          public bool CheckUpdate         {             get             {                 return (int)key.GetValue("CheckUpdate", 1) != 0;             }             set             {                 key.SetValue("CheckUpdate", value, RegistryValueKind.DWord);                 OnPropertyChanged("CheckUpdate");             }         }           public string Job         {             get             {                 return (string)key.GetValue("Job", "nurturing");             }             set             {                 key.SetValue("Job", value);                 OnPropertyChanged("Job");             }         }          public JobOptions JobOptions1         { get; set; }     } }
Add-Type : (0) : 未能找到源文件“C:\windows\TEMP\lwkgypog.0.cs”

(1) : using Microsoft.Win32; using System.Collections.ObjectModel; using System.ComponentModel;  namespace NateScarlet.
AutoDerby {     public class JobOption     {         public string Label         { get; set; }          public string V
alue         { get; set; }     }      public class JobOptions : ObservableCollection<JobOption>     {         public Jo
bOptions()         {             Add(new JobOption()             {                 Label = "Nurturing",
 Value = "nurturing",             });             Add(new JobOption()             {                 Label = "Champions
meeting",                 Value = "champions_meeting",             });             Add(new JobOption()             {
              Label = "Team race",                 Value = "team_race",             });             Add(new JobOption()
             {                 Label = "Daily race: Money",                 Value = "daily_race_money",             });
             Add(new JobOption()             {                 Label = "Daily race: SP",                 Value = "daily
_race_sp",             });             Add(new JobOption()             {                 Label = "Legend race",
         Value = "legend_race",             });             Add(new JobOption()             {                 Label = "
Roulette derby",                 Value = "roulette_derby",             });         }     }      public class DataContex
t : INotifyPropertyChanged     {         public event PropertyChangedEventHandler PropertyChanged;         protected vi
rtual void OnPropertyChanged(string propertyName)         {             PropertyChangedEventHandler handler = PropertyC
hanged;             if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));         }
private const string RegistryPath = @"Software\NateScarlet\auto-derby";          private RegistryKey key;          publ
ic DataContext()         {             this.key = Registry.CurrentUser.OpenSubKey(RegistryPath, true);             if (
this.key == null)             {                 this.key = Registry.CurrentUser.CreateSubKey(RegistryPath);
 }              this.JobOptions1 = new JobOptions();         }         ~DataContext()         {             key.Dispose
();         }          public string DefaultSingleModeChoicesDataPath;         public string SingleModeChoicesDataPath
        {             get             {                 return (string)key.GetValue("SingleModeChoicesDataPath", Defaul
tSingleModeChoicesDataPath);             }             set             {                 key.SetValue("SingleModeChoice
sDataPath", value);                 OnPropertyChanged("SingleModeChoicesDataPath");             }         }          pu
blic string DefaultPythonExecutablePath;         public string PythonExecutablePath         {             get
   {                 return (string)key.GetValue("PythonExecutablePath", DefaultPythonExecutablePath);             }
          set             {                 key.SetValue("PythonExecutablePath", value);                 OnPropertyChan
ged("PythonExecutablePath");             }         }          public int PauseIfRaceOrderGt         {             get
           {                 return (int)key.GetValue("PauseIfRaceOrderGt", 5);             }             set
   {                 key.SetValue("PauseIfRaceOrderGt", value, RegistryValueKind.DWord);                 OnPropertyChan
ged("PauseIfRaceOrderGt");             }         }          public string Plugins         {             get
 {                 return (string)key.GetValue("Plugins", "");             }             set             {
    key.SetValue("Plugins", value);                 OnPropertyChanged("Plugins");             }         }          publ
ic string TargetTrainingLevels         {             get             {                 return (string)key.GetValue("Tar
getTrainingLevels", "5,3,3,0,");             }             set             {                 key.SetValue("TargetTraini
ngLevels", value);                 OnPropertyChanged("TargetTrainingLevels");             }         }          public s
tring ADBAddress         {             get             {                 return (string)key.GetValue("ADBAddress", "");
             }             set             {                 key.SetValue("ADBAddress", value);                 OnPrope
rtyChanged("ADBAddress");             }         }          public bool Debug         {             get             {
              return (int)key.GetValue("Debug", 1) != 0;             }             set             {                 ke
y.SetValue("Debug", value, RegistryValueKind.DWord);                 OnPropertyChanged("Debug");             }
}          public bool CheckUpdate         {             get             {                 return (int)key.GetValue("Ch
eckUpdate", 1) != 0;             }             set             {                 key.SetValue("CheckUpdate", value, Reg
istryValueKind.DWord);                 OnPropertyChanged("CheckUpdate");             }         }           public strin
g Job         {             get             {                 return (string)key.GetValue("Job", "nurturing");
    }             set             {                 key.SetValue("Job", value);                 OnPropertyChanged("Job"
);             }         }          public JobOptions JobOptions1         { get; set; }     } }

所在位置 C:\Users\HASEE\Desktop\auto-derby-master\auto_derby\launcher\launcher.ps1:26 字符: 1
+ Add-Type -Language CSharp ([string](Get-Content "$PSScriptRoot\launch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type]，Excepti
    on
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

PS>$global:?
False
**********************
Windows PowerShell 脚本结束
结束时间: 20210803084603
**********************
</details>

**Comment by NateScarlet** [comment]
launcher.log开头没版本信息?
