### ISSUE TITLE
4 選項無法辨認

### ISSUE THREAD

**Issue by Splendent** [NateScarlet/auto-derby#129]
![Screenshot_20210717-222113](https://user-images.githubusercontent.com/3349355/128025606-f42974c3-07ce-4b3b-a1cb-3044e5fd3a45.png)
一段時間沒更新了，不確定現在的版本會不會發生
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6924470/auto_derby.log)

**Comment by NateScarlet** [comment]
我根本没遇到过4选项的事件 所以就没处理
