### ISSUE TITLE
泳裝丸善 海邊時 OCR 失敗

### ISSUE THREAD

**Issue by Splendent** [NateScarlet/auto-derby#130]
![last_screenshot local](https://user-images.githubusercontent.com/3349355/128025922-0989c77b-e3eb-4148-83dd-96c8453c6257.png)
並不是每次都會發生，大概50%機率
看LOG應該是OCR失敗，詳情不確定，可能是阿姨的 )( 遮蔽了OCR的雙眼
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6924486/auto_derby.log)
[auto_derby1.log](https://github.com/NateScarlet/auto-derby/files/6924488/auto_derby1.log)

**Comment by NateScarlet** [comment]
日志没有报错而且这张图能正常识别

需要识别出错时的图片来复现

**Comment by Splendent** [comment]
我多跑幾次看看吧 🏇

**Comment by Splendent** [comment]
嚕了幾場總算出現一次，沒特別注意到發生當下狀況如何
LOG中有提示OCR辨認訊息，但是沒等確認就進行下去
直到最後一個選項(讀書)
後來想重現就無法發生正常的過去了🤔 
有機會我再錄影看看

CMD當時內容如下
```
DEBUG [00:28:05]:auto_derby.ocr:208: ocr result is empty
DEBUG [00:28:05]:auto_derby.ocr:136: match label: value=1, current=f807f807f807f807f007f007f007f007e00fe00fe00fe00fe01fe01fe01fe01f, match=0000e007f807fe07ff07ff07e007e007e007e007e007e00fe01fe03fe03fe01f, similarity=0.789
Matching current displaying image: value=1, similarity=0.789.
Is this correct? (Y/N)DEBUG [00:28:08]:auto_derby.template:45: screenshot
DEBUG [00:28:08]:auto_derby.template:122: lightness match: tmpl=tmpl<single_mode_training_confirm.png>, similarity=0.994
INFO  [00:28:08]:auto_derby.template:181: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(157, 843), similarity=0.94
```

![image](https://user-images.githubusercontent.com/3349355/128219206-aa269093-4d7f-4d9a-a4c6-416057e0ca96.png)

LAST SCREENSHOT
![last_screenshot local](https://user-images.githubusercontent.com/3349355/128219504-6a4e5a75-be86-4c83-a6a0-26d91383fe50.png)
LOG
[auto_derby_1.log](https://github.com/NateScarlet/auto-derby/files/6933246/auto_derby_1.log)

**Comment by NateScarlet** [comment]
用新版 会保存训练图片
https://github.com/NateScarlet/auto-derby/blob/e7bb304ab4122923df4270fe6e4c88e317a944df/auto_derby/single_mode/training.py#L175

**Comment by NateScarlet** [comment]
训练的图片识别是在别的线程里进行的 所以last_screenshot 没有用

**Comment by Splendent** [comment]
再來個，花了點時間看要怎麼找local training img，應該是直接對應路徑吧
![image](https://user-images.githubusercontent.com/3349355/128499358-42c3c156-f028-4c23-b3df-7ef65a9a5d90.png)
```
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=+, current=00000000e001f003f003f807ff7fff7fff7ffe1ff003f003e001000000000000, match=0000e000f001f003f003f003ff3fff7fff3ff807f003f003e001000000000000, similarity=0.906
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=9, current=f007fc1f3e3e0f780f780ff00ff83efefcfff0f900f800781e7cfe3ffc0fe003, match=f003fc1f3e3e0f780f780ff00ff83ffefcfff8ff00f800f80c7c7e3ffe1ff803, similarity=0.898
DEBUG [18:38:16]:auto_derby.ocr:314: ocr result: +9
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=+, current=00000000e000e001e001f003ff1fff3fff3fff1ff003e001e001e00100000000, match=000000000000c001e003e003fe1fff7fff7fff7ff007e003e003e00100000000, similarity=0.891
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=1, current=000f801fe01ff01ff01ff01f801f801f801f801f801f801f801f801f801f000f, match=001ec01fe01ff01ff01f801f801f801f801f801f801f001f001f003f003f003e, similarity=0.883
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=7, current=fefffffffeff807f003f001f800fc00fc007e003f003f003f801f801f801f001, match=fe7ffffffffffcff003f001f800fc00fc007e003e003f003f003f003f001f000, similarity=0.883
DEBUG [18:38:16]:auto_derby.ocr:314: ocr result: +17
DEBUG [18:38:16]:auto_derby.ocr:208: ocr result is empty
DEBUG [18:38:16]:auto_derby.ocr:208: ocr result is empty
DEBUG [18:38:16]:auto_derby.ocr:136: match label: value=+, current=000000008003c007c007c007fc3ffc7ffc7ffc3fc007c007c307830300000000, match=00008001c003c003c007fe3ffffffffffffffc3fc003c003c003800100000000, similarity=0.766
Matching current displaying image: value=+, similarity=0.766.
Is this correct? (Y/N)DEBUG [18:38:19]:auto_derby.template:45: screenshot
DEBUG [18:38:19]:auto_derby.template:122: lightness match: tmpl=tmpl<single_mode_training_confirm.png>, similarity=0.986
INFO  [18:38:19]:auto_derby.template:181: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(348, 843), similarity=0.94
DEBUG [18:38:19]:auto_derby.clients.adb:55: tap: input tap 922 1700
DEBUG [18:38:20]:auto_derby.single_mode.training:175: from_training_scene: image=597231813b6b1dc9145864821110e186
DEBUG [18:38:20]:auto_derby.template:122: lightness match: tmpl=tmpl<single_mode_training_confirm.png>, similarity=0.986
INFO  [18:38:20]:auto_derby.template:181: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(348, 843), similarity=0.94
DEBUG [18:38:20]:auto_derby.ocr:136: match label: value=+, current=00000000e001f003f003f807ff3fff7fff3ffe1ff003f003e001000000000000, match=0000e000f001f003f003f003ff3fff7fff3ff807f003f003e001000000000000, similarity=0.922
```

取前後的scene
```
DEBUG [2021-08-06 18:38:16]:auto_derby.single_mode.training:175: from_training_scene: image=c6b8eb46a8a84c6f541ecc1cf2a7ca3a
.
.
DEBUG [2021-08-06 18:38:16]:auto_derby.ocr:136: match label: value=+, current=000000008003c007c007c007fc3ffc7ffc7ffc3fc007c007c307830300000000, match=00008001c003c003c007fe3ffffffffffffffc3fc003c003c003800100000000, similarity=0.766
DEBUG [2021-08-06 18:38:19]:auto_derby.template:45: screenshot
.
DEBUG [18:38:20]:auto_derby.single_mode.training:175: from_training_scene: image=597231813b6b1dc9145864821110e186
```
- c6b8eb46a8a84c6f541ecc1cf2a7ca3a
![8eb46a8a84c6f541ecc1cf2a7ca3a](https://user-images.githubusercontent.com/3349355/128499972-609c3766-5cf5-4153-ad74-14243e6992b8.png)

- 597231813b6b1dc9145864821110e186
![231813b6b1dc9145864821110e186](https://user-images.githubusercontent.com/3349355/128499913-16381ef5-dde0-45c8-abd1-fed0dfefdc13.png)

- ae582269ac9cf652448599ce89a6eae6
![82269ac9cf652448599ce89a6eae6](https://user-images.githubusercontent.com/3349355/128500163-b9e84095-2df3-4acf-b3cc-36b89a494bcd.png)

- 4f6cacc353c536384d3ced07308e77ef
這檔名怪怪的?原始檔名為`f6b8a2dfccc5eaaffb38317abbbf8`，但照修改時間來看應該是這張沒錯
![f6b8a2dfccc5eaaffb38317abbbf8](https://user-images.githubusercontent.com/3349355/128500382-64363bdc-2cf6-4184-a08b-9ba4bd595759.png)

LOG
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6945049/auto_derby.log)

最後吐槽下，LOCAL IMG真大，能砍掉嗎
![image](https://user-images.githubusercontent.com/3349355/128500761-0e83ea3c-784c-4af6-a889-c145829b478f.png)

**Comment by NateScarlet** [comment]
启动器会自动删3天前的文件
https://github.com/NateScarlet/auto-derby/blob/e7bb304ab4122923df4270fe6e4c88e317a944df/auto_derby/launcher/launcher.ps1#L158-L176

**Comment by NateScarlet** [comment]
用 c6b8eb46a8a84c6f541ecc1cf2a7ca3a 这张复现了
