### ISSUE TITLE
碰到打针就歇菜了

### ISSUE THREAD

**Issue by 1415desu** [NateScarlet/auto-derby#131]
第一次遇到打针时选了选项5，没有反应。后来把afk打开全自动育成时，碰到打针就会卡住不动

**Comment by NateScarlet** [comment]
如果你是想改选项 看 #111 
如果你觉得是bug 看 [问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88) 带日志和截图

**Comment by Rivers47** [comment]
![image](https://user-images.githubusercontent.com/30615204/129472479-074a9570-0722-4ae3-af26-087d4486b650.png)
相同的情况，似乎是找不到option4？
下次再碰到我会开debug模式

**Comment by NateScarlet** [comment]
这个应该是因为 [single_mode_option4.pos.png](https://github.com/NateScarlet/auto-derby/blob/133dd94c150735e2c3226fcfa6f5e1a98a772789/auto_derby/templates/single_mode_option4.pos.png) 只有 4 选项时的位置，现在的位置来自 #129

5选项时的位置信息没有，需要一张 5 选项时的完整截图来修

**Comment by NateScarlet** [comment]
我更新了 #166 给的模版

但是需要一张 5 选项的截图来测试

**Comment by CNA-Bld** [comment]
The images in fd9ccba were cropped based on (the original) single_mode_option{4,5}.pos.png, and I have tested them locally.

I am currently unable to confirm whether the updated 4.pos.png in c7dae4a still works. My eyeball thinks that the position mark for 5-option events didn't change so it should work for the 笹針師 event. I have no idea what a 4-option event looks like though.

And a screenshot of the 笹針師 event that can be used for test cases:
![](https://user-images.githubusercontent.com/2557768/130796185-3db33c91-d4dc-40b4-bba4-f57a981c3381.png)

**Comment by NateScarlet** [comment]
single_mode_option4.png  in fd9ccba3f48837fb1b8f9430a27efa660ba8fa4c will also match to option5, because they have similar color
