### ISSUE TITLE
#bug#安卓手机无法运行脚本

### ISSUE THREAD

**Issue by as8593189** [NateScarlet/auto-derby#132]
异常栈：
DEBUG [2021-08-06 12:43:04]:auto_derby.plugin:43: loaded: afk, auto_crane, example_custom_context, example_custom_race_score, example_custom_training_score, hello_world, limited_sale_buy_everything, limited_sale_buy_first_3, more_g1, prefer_g1, no_event_prompt, no_ocr_prompt, umapyoi, use_legacy_screenshot
DEBUG [2021-08-06 12:43:04]:auto_derby.clients.adb:74: screen size: width=1080 height=2340
DEBUG [2021-08-06 12:43:08]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 12:43:08]:auto_derby.template:59: load: connecting.pos.png
DEBUG [2021-08-06 12:43:08]:auto_derby.template:59: load: connecting.png
ERROR [2021-08-06 12:43:08]:__main__:124: unexpected exception
Traceback (most recent call last):
  File "F:\auto-derby-1.2.2\auto_derby\__main__.py", line 120, in <module>
    main()
  File "F:\auto-derby-1.2.2\auto_derby\__main__.py", line 91, in main
    job()
  File "F:\auto-derby-1.2.2\auto_derby\jobs\nurturing.py", line 309, in nurturing
    tmpl, pos = action.wait_image(
  File "F:\auto-derby-1.2.2\auto_derby\action.py", line 51, in wait_image
    return next(template.match(template.screenshot(max_age=0), *tmpl))
  File "F:\auto-derby-1.2.2\auto_derby\template.py", line 193, in match
    for j in _match_one(img, i):
  File "F:\auto-derby-1.2.2\auto_derby\template.py", line 173, in _match_one
    _, max_val, _, max_loc = cv2.minMaxLoc(res, mask=mask)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\core\src\matrix_iterator.cpp:71: error: (-215:Assertion failed) A.size == arrays[i0]->size in function 'cv::NAryMatIterator::init'

最后的截图：
![last_screenshot local](https://user-images.githubusercontent.com/46948349/128459741-db9437f6-1676-47d2-abae-975a96e8dfc2.png)

这种情况能不能修改自行修改需求分辨率解决？

**Comment by NateScarlet** [comment]
不行 屏幕分辨率必须是 16:9 不然识别坐标对不上
