### ISSUE TITLE
#笔记本显示屏无法运行脚本#

### ISSUE THREAD

**Issue by as8593189** [NateScarlet/auto-derby#133]
debug信息：
WARNING[2021-08-06 13:23:48]:auto_derby.window:120: recover foreground window failed: (1400, 'SetForegroundWindow', '无效的窗口句柄。')
DEBUG [2021-08-06 13:23:49]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:49]:auto_derby.template:59: load: single_mode_class_detail_title.pos.png
DEBUG [2021-08-06 13:23:49]:auto_derby.template:59: load: single_mode_class_detail_title.png
DEBUG [2021-08-06 13:23:50]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(171, 224), similarity=0.050
INFO  [2021-08-06 13:23:50]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:50]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:50]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(171, 224), similarity=0.037
INFO  [2021-08-06 13:23:50]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:50]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(172, 224), similarity=0.035
INFO  [2021-08-06 13:23:51]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:51]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 224), similarity=0.044
INFO  [2021-08-06 13:23:51]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:51]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 224), similarity=0.045
INFO  [2021-08-06 13:23:51]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:52]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:52]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 224), similarity=-0.007
INFO  [2021-08-06 13:23:52]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:52]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:52]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 227), similarity=-0.061
INFO  [2021-08-06 13:23:52]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:53]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:53]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(171, 227), similarity=0.110
INFO  [2021-08-06 13:23:53]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:53]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:54]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(169, 226), similarity=0.110
INFO  [2021-08-06 13:23:54]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:54]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:54]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(170, 227), similarity=0.091
INFO  [2021-08-06 13:23:54]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:54]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:54]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 227), similarity=0.084
INFO  [2021-08-06 13:23:54]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:55]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:55]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(173, 227), similarity=0.094
INFO  [2021-08-06 13:23:55]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:55]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:55]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(172, 227), similarity=0.115
INFO  [2021-08-06 13:23:55]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:56]:auto_derby.template:45: screenshot
DEBUG [2021-08-06 13:23:56]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(169, 227), similarity=0.078
INFO  [2021-08-06 13:23:56]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_title.png',)
DEBUG [2021-08-06 13:23:57]:auto_derby.template:45: screenshot

最后一次截图
![last_screenshot local](https://user-images.githubusercontent.com/46948349/128460489-b9577af1-6782-455c-b4fe-2ba02a7d3006.png)

程序启动会扩大赛马娘窗口，但是本身是笔记本屏幕会导致下面显示不全造成坐标无法点击，如何自定义修改窗口完成配置？
![2](https://user-images.githubusercontent.com/46948349/128460615-8819add3-3cf5-48b5-87fd-65ef0b538602.png)

**Comment by NateScarlet** [comment]
参见 #123
