### ISSUE TITLE
ADB 识别不到 single_mode_class_detail_button

### ISSUE THREAD

**Issue by BaiZero** [NateScarlet/auto-derby#135]

**Comment by BaiZero** [comment]
就那个Y /N 直接全Y
然后1 2 3 4 5 那个从 1 和2 里随机。

**Comment by BaiZero** [comment]
还有就是说可以循环的自动养马吗？还是每次都得点。。我想让他变得AUTO

**Comment by BaiZero** [comment]
我觉得正确率在0.7以上就可以通过不用y和n，   12345我想知道那个位置在那我想自己魔改一下。

**Comment by BaiZero** [comment]
我尝试了一下狂按2y回车3个键  ，好像解决了。应该把。。

**Comment by BaiZero** [comment]
我好像小礼帽和大和的截图不兼容、、、截图小礼帽能用，但是大和就。

**Comment by NateScarlet** [comment]
改模版要跟着改 .pos.png 不然位置不对会被无视

**Comment by NateScarlet** [comment]
如果你自己动核心代码 那出问题由你自己维护

**Comment by BaiZero** [comment]
emmmmm拿总是卡在这个 single_mode_class_detail_button.png 该怎么办。

**Comment by NateScarlet** [comment]
不知道 你什么信息都没给

**Comment by BaiZero** [comment]
无法识别到这个图片，就是粉丝数这个识别不到，我注意到好像每个角色里那个粉丝里  i   的圈颜色都不一样。是不是因为这个。

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88

**Comment by BaiZero** [comment]
日常训练模式下 其他都能识别到，就这个一直不行用的雷电模拟器，1080 1920 分辨率

**Comment by BaiZero** [comment]
要日志马？

**Comment by BaiZero** [comment]
DEBUG [2021-08-07 07:31:22]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(116, 156), similarity=0.364
INFO  [2021-08-07 07:31:22]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 07:31:24]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 07:31:24]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(116, 156), similarity=0.364
INFO  [2021-08-07 07:31:24]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 07:31:26]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 07:31:26]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(116, 156), similarity=0.364
INFO  [2021-08-07 07:31:26]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)

**Comment by NateScarlet** [comment]
last_screenshot 发一下

**Comment by BaiZero** [comment]
![last_screenshot local](https://user-images.githubusercontent.com/45115961/128594356-3450dff7-78a0-4e1a-a769-0853bfc9bccb.png)

**Comment by BaiZero** [comment]
卡在这里不动了

**Comment by NateScarlet** [comment]
这个和圈的颜色没关系 模版就只是个i
原因是样本从DMM客户端取的 分辨率不一样导致匹配不同

**Comment by BaiZero** [comment]
然后我重新从模拟器全屏接了下图。但是只能用一个角色。到了她就不行了。

**Comment by NateScarlet** [comment]
你重新截图能用就很神奇 模版要求的是从540宽的图上截

**Comment by BaiZero** [comment]
小栗帽改过一会 ，然后小栗帽估计无法识别两次G1任务。然后试试别的角色

**Comment by BaiZero** [comment]
？真假的？

**Comment by BaiZero** [comment]
我用以前PCR截图的办法截图的。全屏然后找那个粉丝数i。

**Comment by NateScarlet** [comment]
小栗帽能用 见 #104 #87‘

adb是实验性的 改完新功能不会用 adb 测试再发布 因为我模拟器开加速器很麻烦

**Comment by BaiZero** [comment]
不过和你说的一样比较精细的截图，基本只有一个i的符号。我觉得有没有可能是i周围颜色导致i的颜色其实会发生人眼感受不到的变化。

**Comment by BaiZero** [comment]
明白的。

**Comment by BaiZero** [comment]
就是有没有办法跳过这一步，不识别这个符号，基本运行一次。好像模拟器没有其他问题。

**Comment by NateScarlet** [comment]
不支持跳识别 因为粉丝数用于基本逻辑
不需要的数据都没识别

**Comment by BaiZero** [comment]
那看起来只能从原图片上下手脚。。我还说可以找一个类似图片代替，每次找到同一界面下其他图片，然后点击某个位置，打开粉丝数。         有没有可能利用识别比如   详细  或者   训练这两个图片，，单独写一个打开粉丝界面的坐标然后点击。

**Comment by NateScarlet** [comment]
如果模版匹配可以修就没必要增加额外逻辑 逻辑越多越容易出错

**Comment by BaiZero** [comment]
那确实

**Comment by NateScarlet** [comment]
这个模版在 540 宽的分辨率的匹配度也只有0.9 好像是最初版本在 466 宽的窗口中截图放大过来的那一批模版

**Comment by NateScarlet** [comment]
dev 分支修了 我还加了测试 你试一下

**Comment by BaiZero** [comment]
重新下载代码对吧。。

**Comment by NateScarlet** [comment]
其实只有 single_mode_class_detail_button.png single_mode_class_detail_button.pos.png 改了

新增的代码都只是测试用的

**Comment by BaiZero** [comment]
DEBUG [2021-08-07 19:19:25]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:25]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:25]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:28]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:28]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:28]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:30]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:31]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:31]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:32]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:33]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:33]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:34]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:34]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:34]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:36]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:37]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:37]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)
DEBUG [2021-08-07 19:19:39]:auto_derby.template:45: screenshot
DEBUG [2021-08-07 19:19:39]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.895
INFO  [2021-08-07 19:19:39]:auto_derby.template:197: no match: tmpl=('single_mode_class_detail_button.png',)

**Comment by BaiZero** [comment]
这样的循环

**Comment by NateScarlet** [comment]
你没覆盖 .pos.png 用开发分支坐标不可能是 115 155

**Comment by BaiZero** [comment]
全部重新下载了一下。。怕缺东西。

**Comment by BaiZero** [comment]
问题解决了 ，我是智障。弄错了。

**Comment by BaiZero** [comment]
对了大佬，建议在ADB里加一个   adb kill-server   ，刚开始一直连不上模拟器因为这个。

**Comment by NateScarlet** [comment]
此项目的adb不依赖adb.exe 得连上才能执行命令 所以不行
