### ISSUE TITLE
无法进入育成

### ISSUE THREAD

**Issue by CrepusculeHaL** [NateScarlet/auto-derby#139]
按了start之后没有反应
查看log之后发现有以下内容

Installed packages:
>> TerminatingError():“无法将“cmd.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。”
>> TerminatingError():“无法将“cmd.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。”
无法将“cmd.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
& : 无法将“cmd.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 C:\Users\\Desktop\auto-derby-1.3.0\auto_derby\launcher\launcher.ps1:162 字符: 7
+     & cmd.exe /c "`"$($Data.PythonExecutablePath)`" -m pip list 2>&1" ...
+       ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cmd.exe:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS>$global:?
False

另外在按下start之后也会出现一堆debug
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_fans_not_enough.png>, pos=(261, 228), similarity=0.033
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_target_race_no_permission.png>, pos=(155, 250), similarity=0.031
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_target_unfinished.png>, pos=(165, 247), similarity=0.040
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_finish_button.png>, pos=(330, 810), similarity=0.084
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_formal_race_banner.png>, pos=(372, 765), similarity=0.308
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_race_next_button.png>, pos=(291, 830), similarity=0.406
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_option1.png>, pos=(24, 271), similarity=0.144
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<green_next_button.png>, pos=(389, 419), similarity=0.389
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_ura_finals.png>, pos=(341, 784), similarity=0.042
DEBUG [14:57:51]:auto_derby.template:177: not match: tmpl=tmpl<single_mode_gene_inherit.png>, pos=(224, 531), similarity=0.341
截取了其中一部分

**Comment by NateScarlet** [comment]
为什么你会同时发两个日志 一个是启动失败 一个是正常启动的

脚本需要你手动进育成模式 不会帮你选卡的……

**Comment by CrepusculeHaL** [comment]
已经手动进入育成模式了 然后就是在育成画面卡住
怀疑过是不是一并试用了umado导致识别不到窗口的问题 但是关掉umado再启动游戏也不会动
实际上在我发完之后再去测试了一下 育成开始之前确实有自动点击绿色的继续
但是一进去育成的界面就完全不动了…… 不太清楚哪里出了问题

**Comment by NateScarlet** [comment]
debug/last_screenshot.png 发一下

**Comment by CrepusculeHaL** [comment]
![last_screenshot](https://user-images.githubusercontent.com/88703227/128817697-fe9e8287-c88a-40d5-8b5e-7037230afca7.png)
![last_screenshot](https://user-images.githubusercontent.com/88703227/128817734-3f6f3494-b10c-497b-86f0-3122db2c67f1.png)
按顺序分别是debug1 debug2和3的图
debug2和3的截图画面是一样的

**Comment by NateScarlet** [comment]
选完卡进育成界面再开脚本 不会帮你选卡的

难道我再做个UI提取你拥有的马娘和支援卡让你在启动器上选吗 不然我怎么知道你要练什么卡

**Comment by CrepusculeHaL** [comment]
好的 感谢答疑
麻烦您了 我再去试一试

**Comment by CrepusculeHaL** [comment]
已经可以正常使用了 感谢大佬的脚本
另外确实不能和umado一同使用 会导致脚本没有反应 可能是窗口之类的有冲突
再次感谢抽空答疑

**Comment by fatinghenji** [comment]
> umado

是啥啊
