### ISSUE TITLE
ADB 竞技场选择对手页面卡住

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#144]
使用的是adb无线连接
日志：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6987612/auto_derby.log)
截图：
![last_screenshot](https://user-images.githubusercontent.com/37131177/129469474-abec4821-8cf7-439b-8d47-131d5fec2b98.png)
补充：
只有选择对手页面卡住，手动选择后可以进行后续操作。

**Comment by NateScarlet** [comment]
这个应该是模版精度问题 这里用的模版应该还是从466宽的屏幕上截取的

**Comment by NateScarlet** [comment]
开发分支更新了模版
