### ISSUE TITLE
截图是黑屏

### ISSUE THREAD

**Issue by dahuangpi** [NateScarlet/auto-derby#145]
![last_screenshot](https://user-images.githubusercontent.com/88938053/129547012-d1462495-273e-4b68-9fc9-1aad2d760ad0.png)

**Comment by dahuangpi** [comment]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6991463/auto_derby.log)

**Comment by NateScarlet** [comment]
launcher.log 发一下

**Comment by NateScarlet** [comment]
你之前有成功使用过吗 还是第一次用

**Comment by dahuangpi** [comment]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6992156/launcher.log)

**Comment by dahuangpi** [comment]
我是第一次用的

**Comment by dahuangpi** [comment]
又用adb试了一下，能截到图，但是还是操作不了，这是手机运行的
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6992164/launcher.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6992165/auto_derby.log)

**Comment by NateScarlet** [comment]
不带插件能启动吗 你用了个叫 `1` 的插件

**Comment by NateScarlet** [comment]
你可以试试用 use_legacy_screenshot 插件看能不能截到图

这个是前台全屏截图再裁剪

**Comment by dahuangpi** [comment]
试了试和别的插件无关，用了use_legacy_screenshot以后就可以了，非常感谢

**Comment by NateScarlet** [comment]
那也奇怪 按理说应该能后台截图的

可能是你 win10版本太老 你的是 14409 我的是 19041

**Comment by dahuangpi** [comment]
我这个电脑还是win7。。

**Comment by NateScarlet** [comment]
那就对了 后台截图用了 windows blue 之后才加的 API

https://github.com/NateScarlet/auto-derby/blob/6d01292949bfd12946a91ca7cc501c6813701460/auto_derby/window.py#L180-L193

win7 都停止更新快 2 年了

**Comment by NateScarlet** [comment]
开发分支加了对旧版 windows 自动启用 use_legacy_screenshot

**Comment by dahuangpi** [comment]
对了，昨天还有个问题。一开始launch也启动不了，我自己去下载了powershell之后就没问题了，应该也是系统太旧的问题
