### ISSUE TITLE
最新的dev分支报错

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#148]
log如下：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6994434/auto_derby.log)

**Comment by NateScarlet** [comment]
我重命名文件 你合并的时候把老文件还原了

**Comment by NateScarlet** [comment]
把 limited_sale_close.py 删掉
这个重命名为 limited_sale_ignore.py 了

**Comment by fatinghenji** [comment]
ok
我试试

**Comment by fatinghenji** [comment]
问题解决
