### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#15]
报错文件如下：
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6592808/launcher.log)
不清楚是否因为user为中文的原因

**Comment by NateScarlet** [comment]
不是 这个是点训练 但是没找到匹配的训练确定按钮

**Comment by NateScarlet** [comment]
通常重开脚本就好了 如果没好请尝试描述一下重现步骤

**Comment by fatinghenji** [comment]
复现步骤：
1、使用launcher.cmd启动，授予管理员权限。
2、游戏内打开如下界面：
![image](https://user-images.githubusercontent.com/37131177/120673930-319eee00-c4c6-11eb-9523-5f5504c8c4cb.png)
2、再GUI中选择Nurturing，点击Start。
3、游戏转调至如下界面：
![image](https://user-images.githubusercontent.com/37131177/120674007-41b6cd80-c4c6-11eb-8f84-8b2553022b15.png)
在训练选项1和2各选择一次后自动退出。

**Comment by NateScarlet** [comment]
我自己有时候也遇到 点了训练动画没显示完就截图了 这个应该就是电脑卡了掉帧导致的

我加个等待

**Comment by fatinghenji** [comment]
好的，谢谢开发者了。
