### ISSUE TITLE
Win7 launcher.cmd点了没反应

### ISSUE THREAD

**Issue by ljx3916190** [NateScarlet/auto-derby#154]
装了python3.8 
输了py -3.8 -m pip install -r requirements.txt之后现在是
`D:\uma\auto-derby-1.4.2>py -3.8 -m pip install -r requirements.txt
Requirement already satisfied: pywin32==300 in c:\users\administrator\appdata\lo
cal\programs\python\python38\lib\site-packages (from -r requirements.txt (line 1
)) (300)
Requirement already satisfied: opencv-python==4.5.2.52 in c:\users\administrator
\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.
txt (line 2)) (4.5.2.52)
Requirement already satisfied: opencv-contrib-python==4.5.2.52 in c:\users\admin
istrator\appdata\local\programs\python\python38\lib\site-packages (from -r requi
rements.txt (line 3)) (4.5.2.52)
Requirement already satisfied: cast-unknown==0.1.6 in c:\users\administrator\app
data\local\programs\python\python38\lib\site-packages (from -r requirements.txt
(line 4)) (0.1.6)
Requirement already satisfied: numpy==1.20.3 in c:\users\administrator\appdata\l
ocal\programs\python\python38\lib\site-packages (from -r requirements.txt (line
5)) (1.20.3)
Requirement already satisfied: pillow==8.2.0 in c:\users\administrator\appdata\l
ocal\programs\python\python38\lib\site-packages (from -r requirements.txt (line
6)) (8.2.0)
Requirement already satisfied: mouse==0.7.1 in c:\users\administrator\appdata\lo
cal\programs\python\python38\lib\site-packages (from -r requirements.txt (line 7
)) (0.7.1)
Requirement already satisfied: adb-shell==0.3.3 in c:\users\administrator\appdat
a\local\programs\python\python38\lib\site-packages (from -r requirements.txt (li
ne 8)) (0.3.3)
Requirement already satisfied: six~=1.15.0 in c:\users\administrator\appdata\loc
al\programs\python\python38\lib\site-packages (from cast-unknown==0.1.6->-r requ
irements.txt (line 4)) (1.15.0)
Requirement already satisfied: python-dateutil~=2.8.1 in c:\users\administrator\
appdata\local\programs\python\python38\lib\site-packages (from cast-unknown==0.1
.6->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: rsa in c:\users\administrator\appdata\local\progr
ams\python\python38\lib\site-packages (from adb-shell==0.3.3->-r requirements.tx
t (line 8)) (4.7.2)
Requirement already satisfied: cryptography in c:\users\administrator\appdata\lo
cal\programs\python\python38\lib\site-packages (from adb-shell==0.3.3->-r requir
ements.txt (line 8)) (3.4.7)
Requirement already satisfied: pyasn1 in c:\users\administrator\appdata\local\pr
ograms\python\python38\lib\site-packages (from adb-shell==0.3.3->-r requirements
.txt (line 8)) (0.4.8)
Requirement already satisfied: cffi>=1.12 in c:\users\administrator\appdata\loca
l\programs\python\python38\lib\site-packages (from cryptography->adb-shell==0.3.
3->-r requirements.txt (line 8)) (1.14.6)
Requirement already satisfied: pycparser in c:\users\administrator\appdata\local
\programs\python\python38\lib\site-packages (from cffi>=1.12->cryptography->adb-
shell==0.3.3->-r requirements.txt (line 8)) (2.20)

D:\uma\auto-derby-1.4.2>`

应该是装好了 
然后再双击launcher.cmd 有个黑框闪一下然后就没了

**Comment by ljx3916190** [comment]
我系统是win7

**Comment by NateScarlet** [comment]
Win7 需要手动更新 Powershell  或者直接打命令不用启动器

并且需要使用 use_legacy_screenshot 插件

见 #145

**Comment by NateScarlet** [comment]
[FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#win7-%E5%90%AF%E5%8A%A8%E5%99%A8%E6%97%A0%E6%B3%95%E5%90%AF%E5%8A%A8) 添加了相关说明
