### ISSUE TITLE
ocr识别问题

### ISSUE THREAD

**Issue by magicxiu** [NateScarlet/auto-derby#156]
+2和+21不能正确识别
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7019616/auto_derby.log)
[auto_derby2.log](https://github.com/NateScarlet/auto-derby/files/7019621/auto_derby2.log)
[img.zip](https://github.com/NateScarlet/auto-derby/files/7019623/img.zip)

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/130307680-c1bb92a2-1cfd-49ed-a92f-0869993b7c45.png)

1的右上角提取边框没封闭导致的
