### ISSUE TITLE
优先针对跑法适性而并不是属性来优先选择跑法

### ISSUE THREAD

**Issue by kafu0611** [NateScarlet/auto-derby#158]
在训练个别逃适性为F/G的角色（例如胜利奖券）时，以AFK为前提设定下在生涯育成中仍然会自动以属性优先选择逃跑法导致比赛不断失败，建议至少适性为C或者以上的时候才考虑进行该跑法
[
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7025854/auto_derby.log)
](url)

**Comment by NateScarlet** [comment]
跑法只影响智力
单人模式只要速耐够跑逃就有可能第一名 跑逃会翻车跑其他的一样会翻车

按你这日志力量太低所有跑法预测都是翻车 要5000分才能有人数的一半排名  10000分才能第一名

```
INFO  [2021-08-22 01:30:40]:auto_derby.jobs.nurturing:224: running style score:	3555.23:	lead
INFO  [2021-08-22 01:30:40]:auto_derby.jobs.nurturing:224: running style score:	3067.87:	head
INFO  [2021-08-22 01:30:40]:auto_derby.jobs.nurturing:224: running style score:	2400.59:	middle
INFO  [2021-08-22 01:30:40]:auto_derby.jobs.nurturing:224: running style score:	1723.70:	last
```

如果你要 ban 跑法 用插件改 Race.style_scores 返回值把不要的跑法改为 0
插件生成器计划支持生成此类插件 https://github.com/NateScarlet/auto-derby-plugin-generator/issues/2
