### ISSUE TITLE
两字符识别为1字符程序报错？

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#16]
要求输入识别文字，无论输入7/7月/月都会导致程序报错退出
![image](https://user-images.githubusercontent.com/37131177/120677987-3bc2eb80-c4ca-11eb-9ef6-7abe59afb71c.png)

**Comment by NateScarlet** [comment]
全图发一下 这个是分字没分对

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120678460-ad9b3500-c4ca-11eb-83e4-94a0760d7fd8.png)

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/120678479-b2f87f80-c4ca-11eb-9b92-32fd3c46a6e2.png)

不知为何我的字好像比你的粗

**Comment by fatinghenji** [comment]
可能是因为我用了这个项目？
[umamusume-localify](https://github.com/GEEKiDoS/umamusume-localify)
里面有一个参数是：
`replaceFont` 将所有字体替换为默认字体, 解决缺字问题 (true/false)

**Comment by fatinghenji** [comment]
怎么删除错误的识别结果呢？

**Comment by NateScarlet** [comment]
开 DEBUG 看日志里面找对应的摘要 然后在数据里面把对应的那一条删掉

或者你直接用我的覆盖

**Comment by NateScarlet** [comment]
`ocr_labels.json` 最近加的数据会在最下面

**Comment by fatinghenji** [comment]
我把`replaceFont`参数改为false之后问题解决了。

**Comment by NateScarlet** [comment]
那就是没适配字体的问题 应该不需要我这边改什么东西

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120752307-11117b00-c53c-11eb-8482-f232c8c8525b.png)
再次出现相同问题，这次应该不是字体的锅
重新启动后可以通过上图，但是会卡在新的图片上，比如下图：
![image](https://user-images.githubusercontent.com/37131177/120753030-2aff8d80-c53d-11eb-8203-76fadd08b700.png)
