### ISSUE TITLE
训练数值达到三位数时识别错误

### ISSUE THREAD

**Issue by kafu0611** [NateScarlet/auto-derby#162]
尝试三次均在同一个地方出现错误
出现问题的截图：
![Snipaste_2021-08-23_17-11-49](https://user-images.githubusercontent.com/10711790/130425115-545548c1-b0b6-4760-b491-e1d042b2c1ac.png)
log：
[auto_derby (3).log](https://github.com/NateScarlet/auto-derby/files/7030802/auto_derby.3.log)

**Comment by NateScarlet** [comment]
不要开afk

**Comment by kafu0611** [comment]
去除AFK,limited_sale_buy_first_3之后提示

![Snipaste_2021-08-23_18-48-14](https://user-images.githubusercontent.com/10711790/130427399-86d3ed51-4970-4556-985b-0dd385d05c20.png)
-----
按下两次回车之后：
![Snipaste_2021-08-23_18-49-09](https://user-images.githubusercontent.com/10711790/130427413-02caa346-eb3d-401b-9ecf-8d1733697f94.png)
-----
debug：
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7030908/debug.zip)
-----
log：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7030919/auto_derby.log)

**Comment by NateScarlet** [comment]
啊这 原因是因为你训练效果太强 数字超过了范围……

![图片](https://user-images.githubusercontent.com/21083014/130440459-90ad34bc-b858-468c-a86e-ab9ccdea8e5e.png)

**Comment by NateScarlet** [comment]
训练效果有可能超过 100 吗

如果这个是最大值我直接写个匹配 100 的上半部分的特殊处理就行了

**Comment by kafu0611** [comment]
是的，训练增加最大值是 +100 封顶
