### ISSUE TITLE
PVP活动赛（Champions meeting）在角色确认界面下无法正常进行

### ISSUE THREAD

**Issue by kafu0611** [NateScarlet/auto-derby#163]
好像是加了个确认的界面导致没办法正常识别了
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7038478/auto_derby.log)
![last_screenshot](https://user-images.githubusercontent.com/10711790/130601472-02389f7a-fcc8-4840-97f7-f28c0cb1e78e.png)

**Comment by NateScarlet** [comment]
这里就是让你手动确认的 不然你没选人脚本帮你确认会浪费票

**Comment by kafu0611** [comment]
不过终端没弹出来什么信息来确认，只是一直在循环识别下个界面？

**Comment by NateScarlet** [comment]
游戏都弹了我终端有什么必要弹

**Comment by kafu0611** [comment]
> 游戏都弹了我终端有什么必要弹 你是嫌确认不够麻烦吗

和麻烦不麻烦没有关系
训练中如果出现未确定的选项的时候也会进行确认,这里直接不确认开始扫下个界面感觉不自然，看log还在跑就认为可能是哪里出问题
如果是设计如此那就没什么好说的了

**Comment by NateScarlet** [comment]
不处理的界面根本没必要识别 逻辑越多越容易出错
