### ISSUE TITLE
体力上限很高时识别心情出错

### ISSUE THREAD

**Issue by nnsy** [NateScarlet/auto-derby#164]
![last_screenshot](https://user-images.githubusercontent.com/49087952/130616047-b1452f47-21a6-4bda-82a6-fad8e1f0b45e.png)

**Comment by nnsy** [comment]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7039111/auto_derby.log)

**Comment by NateScarlet** [comment]
为啥你的体力条这么长 难道这游戏体力上限会导致体力条变长？

**Comment by NateScarlet** [comment]
开发分支修了 你可以把 [context.py 的更改](https://github.com/NateScarlet/auto-derby/commit/817893748570cfb93fbbc23623d8582f89d0996d#diff-6abaef12b3a7df54b8bb4c3209139315c4b17e2444aae7dee330256ecf84e210) 手动应用到你当前版本来临时修复
