### ISSUE TITLE
识别当前属性出错

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#17]
![image](https://user-images.githubusercontent.com/37131177/120752307-11117b00-c53c-11eb-8482-f232c8c8525b.png)
再次出现相同问题，这次应该不是字体的锅
重新启动后可以通过上图，但是会卡在新的图片上，比如下图：
![image](https://user-images.githubusercontent.com/37131177/120753030-2aff8d80-c53d-11eb-8203-76fadd08b700.png)

_Originally posted by @fatinghenji in https://github.com/NateScarlet/auto-derby/issues/16#issuecomment-854383348_

**Comment by NateScarlet** [comment]
这是个新问题 应该开个新 issue 

我感觉应该是特别周主题色导致的 下班回去修下

**Comment by NateScarlet** [comment]
识别没问题 可能是截图时机不对 我让匹配位置限制更严格试试

**Comment by NateScarlet** [comment]
我感觉应该好了 因为旧的匹配位置比现在偏下了一点

@fatinghenji 测试下

**Comment by fatinghenji** [comment]
> 我感觉应该好了 因为旧的匹配位置比现在偏下了一点
> 
> @fatinghenji 测试下

ok我去试试

**Comment by fatinghenji** [comment]
目前为止没有出现错误

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120809837-0e834580-c57d-11eb-969c-29df321a3580.png)

又出现了，是不是我升级方法有错？
我用的是`git pull`命令。

**Comment by NateScarlet** [comment]
应该是没升级对 我看你截图上面的版本是 7222af1

git pull 显示啥

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120812895-feb93080-c57f-11eb-9676-b01cbae10a36.png)

**Comment by fatinghenji** [comment]
使用以下两个命令重新pull了一下
```
git reset --hard
git pull origin master
```
应该没问题了。

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120824294-e3075780-c58a-11eb-933e-1e4cea483c1f.png)
版本号是：2d1e432
还是存在这个问题？

**Comment by NateScarlet** [comment]
重开脚本应该就好 我这靠复现不了 估计得动态跑起来才会导致

你有注意到什么特别的事情导致属性栏位置变化的吗

**Comment by fatinghenji** [comment]
没太注意诶？确实重开可以解决

**Comment by NateScarlet** [comment]
我好像知道了 进这个界面的时候属性栏有个特别短的从上到下的动画 如果卡了或者运气不好正好截图到了就会触发

我加个 0.2 秒的等待应该就能解决

**Comment by NateScarlet** [comment]
我新加了 debug 模式下会把最后一次截图存在 `last_screenshot.local.png`

如果再遇到可以直接确定脚本看到的是什么画面 不用猜了

**Comment by fatinghenji** [comment]
好的，我试试最新版本。今天运行没有碰到相似的问题。
