### ISSUE TITLE
支持アオハル杯（青春杯）

### ISSUE THREAD

**Issue by saltyduckegg** [NateScarlet/auto-derby#172]

**Comment by NateScarlet** [comment]
等我手动把这模式玩明白

**Comment by saltyduckegg** [comment]
大佬加油

**Comment by SummerFoam233** [comment]
大佬加油！

**Comment by NateScarlet** [comment]
开发分支已经实现了队友训练识别 不过这剧本的训练失败率比URA低很多 需要 #152

**Comment by NateScarlet** [comment]
开发分支已实现团队赛以外的自动育成

**Comment by Small-Ku** [comment]
不知道爲什麼數字不見了
稍微改了代碼再截的圖才發現text_img中的數字不見了
![圖片](https://user-images.githubusercontent.com/16464896/131678924-b4906357-69be-4381-b795-36ea98d4c8f5.png)
single_mode_training_images的圖片在這裏:
![44cbda955197e5a642f5f05ad436c](https://user-images.githubusercontent.com/16464896/131679045-5bf06aa8-d427-4af5-b098-c0787844b1b2.png)
