### ISSUE TITLE
无法启动脚本

### ISSUE THREAD

**Issue by FeltWelsh** [NateScarlet/auto-derby#173]
在dmm端第一次使用，请问应该怎样顺利启动呢？
![20210830235637608](https://user-images.githubusercontent.com/89797399/131371056-4711ba46-774b-4807-b7bb-e3ab9665bfd6.jpg)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7078044/auto_derby.log)

**Comment by NateScarlet** [comment]
不懂代码就用 launcher.cmd 启动

Duplicated of #119

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby/wiki/FAQ#permissionerror-dmmclient-require-admin-permission
