### ISSUE TITLE
每次启动脚本都会无限循环这些

### ISSUE THREAD

**Issue by henrryli1** [NateScarlet/auto-derby#174]
NFO  [19:29:27]:__main__:23: auto_derby: 1.6.1 (2021-08-29 08:09:06)
DEBUG [19:29:28]:auto_derby.plugin:43: loaded: afk, auto_crane, example_custom_context, example_custom_race_score, example_custom_training_partner_score, example_custom_training_score, example_power_level5, example_smart_falcon, hello_world, limited_sale_buy_everything, limited_sale_buy_first_3, limited_sale_ignore, limited_sale_close, more_g1, prefer_g1, no_event_prompt, no_ocr_prompt, pause_before_command, pause_before_race_continue, SSR駿川たづな, umapyoi, use_legacy_screenshot
INFO  [19:29:30]:__main__:83: waiting game launch
INFO  [19:29:31]:__main__:83: waiting game launch
INFO  [19:29:32]:__main__:83: waiting game launch
INFO  [19:29:33]:__main__:83: waiting game launch
INFO  [19:29:34]:__main__:83: waiting game launch
INFO  [19:29:35]:__main__:83: waiting game launch
INFO  [19:29:36]:__main__:83: waiting game launch
INFO  [19:29:37]:__main__:83: waiting game launch
INFO  [19:29:38]:__main__:83: waiting game launch
INFO  [19:29:39]:__main__:83: waiting game launch
INFO  [19:29:40]:__main__:83: waiting game launch
INFO  [19:29:41]:__main__:83: waiting game launch
INFO  [19:29:42]:__main__:83: waiting game launch
INFO  [19:29:43]:__main__:83: waiting game launch
INFO  [19:29:44]:__main__:83: waiting game launch
INFO  [19:29:45]:__main__:83: waiting game launch
INFO  [19:29:46]:__main__:83: waiting game launch
INFO  [19:29:47]:__main__:83: waiting game launch
INFO  [19:29:48]:__main__:83: waiting game launch
INFO  [19:29:49]:__main__:83: waiting game launch
INFO  [19:29:50]:__main__:83: waiting game launch
INFO  [19:29:51]:__main__:83: waiting game launch
INFO  [19:29:52]:__main__:83: waiting game launch
INFO  [19:29:53]:__main__:83: waiting game launch
INFO  [19:29:53]:__main__:85: game window: 5637988
INFO  [19:29:54]:auto_derby.window:82: width=304 height=201
INFO  [19:29:54]:auto_derby.window:82: width=540 height=960
INFO  [19:29:54]:auto_derby.window:84: already in wanted size
DEBUG [19:29:54]:auto_derby.template:44: screenshot
DEBUG [19:29:54]:auto_derby.template:58: load: connecting.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: connecting.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<connecting.png>, pos=(388, 52), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: retry_button.pos.png
DEBUG [19:29:54]:auto_derby.template:75: can not load: retry_button.pos.png: [Errno 2] No such file or directory: 'D:\\auto-derby-master\\auto_derby\\templates\\retry_button.pos.png'
DEBUG [19:29:54]:auto_derby.template:58: load: retry_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<retry_button.png>, pos=(220, 181), similarity=0.323
DEBUG [19:29:54]:auto_derby.template:58: load: green_next_button.pos.png
DEBUG [19:29:54]:auto_derby.template:75: can not load: green_next_button.pos.png: [Errno 2] No such file or directory: 'D:\\auto-derby-master\\auto_derby\\templates\\green_next_button.pos.png'
DEBUG [19:29:54]:auto_derby.template:58: load: green_next_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<green_next_button.png>, pos=(246, 180), similarity=0.335
DEBUG [19:29:54]:auto_derby.template:58: load: race_start_button.pos.png
DEBUG [19:29:54]:auto_derby.template:75: can not load: race_start_button.pos.png: [Errno 2] No such file or directory: 'D:\\auto-derby-master\\auto_derby\\templates\\race_start_button.pos.png'
DEBUG [19:29:54]:auto_derby.template:58: load: race_start_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<race_start_button.png>, pos=(256, 177), similarity=0.440
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_race_button.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_race_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_race_button.png>, pos=(208, 481), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_start_button.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_start_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_start_button.png>, pos=(221, 866), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_confirm_button.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_confirm_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_confirm_button.png>, pos=(238, 792), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: skip_button.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: skip_button.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<skip_button.png>, pos=(399, 902), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: limited_sale_open.pos.png
DEBUG [19:29:54]:auto_derby.template:75: can not load: limited_sale_open.pos.png: [Errno 2] No such file or directory: 'D:\\auto-derby-master\\auto_derby\\templates\\limited_sale_open.pos.png'
DEBUG [19:29:54]:auto_derby.template:58: load: limited_sale_open.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<limited_sale_open.png>, pos=(235, 177), similarity=0.305
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_reward.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_reward.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_reward.png>, pos=(486, 387), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_collect_all_reward.pos.png
DEBUG [19:29:54]:auto_derby.template:58: load: legend_race_collect_all_reward.png
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_collect_all_reward.png>, pos=(340, 888), similarity=0.000
INFO  [19:29:54]:auto_derby.template:196: no match: tmpl=('connecting.png', 'retry_button.png', 'green_next_button.png', 'race_start_button.png', 'legend_race_race_button.png', 'legend_race_start_button.png', 'legend_race_confirm_button.png', 'skip_button.png', 'limited_sale_open.png', 'legend_race_reward.png', 'legend_race_collect_all_reward.png')
DEBUG [19:29:54]:auto_derby.template:44: screenshot
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<connecting.png>, pos=(388, 52), similarity=0.000
DEBUG [19:29:54]:auto_derby.template:176: not match: tmpl=tmpl<retry_button.png>, pos=(228, 189), similarity=0.323
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<green_next_button.png>, pos=(254, 188), similarity=0.335
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<race_start_button.png>, pos=(264, 185), similarity=0.440
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_race_button.png>, pos=(208, 481), similarity=0.000
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_start_button.png>, pos=(221, 866), similarity=0.000
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_confirm_button.png>, pos=(238, 792), similarity=0.000
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<skip_button.png>, pos=(399, 902), similarity=0.000
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<limited_sale_open.png>, pos=(243, 185), similarity=0.305
DEBUG [19:29:55]:auto_derby.template:176: not match: tmpl=tmpl<legend_race_reward.png>, pos=(486, 387), similarity=0.000

**Comment by henrryli1** [comment]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/7085857/launcher.log)

**Comment by henrryli1** [comment]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7085866/auto_derby.log)

**Comment by NateScarlet** [comment]
[所有工作都要求用户人工切换至对应界面，脚本不负责进对应模式和育成选卡。](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E8%84%9A%E6%9C%AC%E5%90%AF%E5%8A%A8%E6%B2%A1%E6%95%88%E6%9E%9C)

而且现在哪来的 legend race
