### ISSUE TITLE
ADB 新模式育成训练识别出错

### ISSUE THREAD

**Issue by saltyduckegg** [NateScarlet/auto-derby#177]
![image](https://user-images.githubusercontent.com/88698765/132098068-fd680881-7a3a-4e86-9ab7-34d995c8ea4a.png)

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7109948/auto_derby.log)

**Comment by saltyduckegg** [comment]
![image](https://user-images.githubusercontent.com/88698765/132098241-b63674d1-bf64-46c9-86a2-fd40652e967b.png)
有概率不会点击训练，需要手动进入
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7109960/auto_derby.log)

**Comment by saltyduckegg** [comment]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7110001/auto_derby.log)
这个是开启DeBug后的报错日志，和第一张图状况一致

**Comment by NateScarlet** [comment]
需要 debug/last_screenshot.png 和最近的5次 single_mode_training_image 来适配 adb

adb 是实验性的 我发布版本不会通过 adb 测试

**Comment by saltyduckegg** [comment]
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7110039/debug.zip)
不太懂最近的5次是怎么算的，但是我直接把debug文件夹给压缩了，希望有所帮助

**Comment by NateScarlet** [comment]
用 single_mode_training_images\5\ea\d4627f5c9d5f621218a952279dc79.png 复现了

![图片](https://user-images.githubusercontent.com/21083014/132099191-265d5f05-60ae-4dea-a5b7-e720ae7740f2.png)

3 的红色边框没提取出来

**Comment by NateScarlet** [comment]
有时候不进训练是因为进训练的时候没等待按钮出现 这个好修
