### ISSUE TITLE
アオハル杯训练识别出错

### ISSUE THREAD

**Issue by gs040664** [NateScarlet/auto-derby#179]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7111023/auto_derby.log)

**Comment by NateScarlet** [comment]
需要 debug/last_screenshot.png 和最近的5次 single_mode_training_image

**Comment by gs040664** [comment]
不只是青春杯，URA也会发生一样的错误

**Comment by gs040664** [comment]
![last_screenshot](https://user-images.githubusercontent.com/34788655/132117755-46b19b92-e5f2-45da-a2fc-f255713e6ac9.png)
![3cbfaa6d0763cf2e00ca4dfdf6044](https://user-images.githubusercontent.com/34788655/132117767-60c3a442-6b7c-4776-868f-5103bdff4a33.png)
![ad9eafea0ef29312bca83e03ff541](https://user-images.githubusercontent.com/34788655/132117771-2943a3c8-f39b-4d3e-a5d6-8be6a257f245.png)
![778af2fa64b5d49b842131ab295aa](https://user-images.githubusercontent.com/34788655/132117775-434374a0-5fc0-479d-b85e-82bd2c169f16.png)
![cfb0c8691ce57c960a23bab3a208f](https://user-images.githubusercontent.com/34788655/132117782-f6ea3f73-3e29-463b-830d-be1008ab1f50.png)

**Comment by NateScarlet** [comment]
那还要URA的日志和 debug/last_screenshot.png 和最近的5次 single_mode_training_image
我建议另开 issue

**Comment by gs040664** [comment]
可以麻烦请你协助开issue，我来上传档案吗?有点不太熟悉这个操作...

**Comment by NateScarlet** [comment]
第三张和第五张都能复现

issue 可以直接传压缩包

**Comment by gs040664** [comment]
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7111041/debug.zip)

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/132117940-94062961-b655-4476-b522-4c4498e6b849.png)
原因是因为背景只适配了白底的字 没处理蓝底的情况

**Comment by gs040664** [comment]
我稍晚再提供URA的档案，感谢大神帮忙

**Comment by NateScarlet** [comment]
识别这个样本还有一个问题就是有队友被无视了

**Comment by gs040664** [comment]
用了1.7.2版跑アオハル杯训练依然会出错
[aoharu_debug.zip](https://github.com/NateScarlet/auto-derby/files/7111343/aoharu_debug.zip)

**Comment by NateScarlet** [comment]
a90a611ce462ec7c39fdc2ec247cf8ab 这个样本出错

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/132122381-6ee287b4-dc56-409d-a26a-12fab4c4aadf.png)

红边匹配有缺口

**Comment by NateScarlet** [comment]
再有问题发新issue 这个问题和一开始的问题不是同一个原因

**Comment by gs040664** [comment]
了解，谢谢大神
