### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by akhialomgir** [NateScarlet/auto-derby#181]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7111355/auto_derby.log)
![last_screenshot](https://user-images.githubusercontent.com/50533365/132122665-d4f4a76f-efad-45e9-8e58-099deafc3be6.png)

**Comment by NateScarlet** [comment]
你发的这个图识别没问题

```
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py .\.local\132122665-d4f4a76f-efad-45e9-8e58-099deafc3be6.png -s aoharu
INFO  [17:54:23]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(444, 843), similarity=0.95
INFO  [17:54:23]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [17:54:23]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=0% wis=6 ski=3 spd=2 ptn=tm(0%)>
```

训练识别是多线程的 要最近5次的 single_mode_training_image

**Comment by gs040664** [comment]
目前用1.7.5跑也遇到这个错误，不知道贴在这边合不合适
[aoharu_debug.zip](https://github.com/NateScarlet/auto-derby/files/7111408/aoharu_debug.zip)

**Comment by NateScarlet** [comment]
@gs040664
不合适 他不发信息你怎么就能知道是同一个错误

**Comment by akhialomgir** [comment]
![04935e618290ce33aa2dea4941fd8](https://user-images.githubusercontent.com/50533365/132124643-acd27725-5189-4f3f-b76b-f737030f9e76.png)
![28e764e20e4482bd0ae3a2df9af1a](https://user-images.githubusercontent.com/50533365/132124645-39deb535-9f0d-4331-9263-207ef66a5230.png)
![0dec88ff6991d0f682be4bb5569fc](https://user-images.githubusercontent.com/50533365/132124649-39f92232-d44e-4e0c-b0fa-82d57c5b98b0.png)
![78cf46f2ee6ed21ea8189b16d41fb](https://user-images.githubusercontent.com/50533365/132124653-77befd51-20c8-4831-b1d8-6a95dcadfcc4.png)
![cb9c3ba7e04fda1ff309cee5fa2fe](https://user-images.githubusercontent.com/50533365/132124656-b6fc7cfb-5dd6-4086-a5f7-3b1e3acb825a.png)

**Comment by NateScarlet** [comment]
这些图 1.7.6 全部正常识别 应该是已经修过了

```
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_1.png
INFO  [19:12:44]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:44]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=9% pow=6 sta=4 ski=2 ptn=oth>
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_2.png
INFO  [19:12:46]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(157, 843), similarity=0.92
INFO  [19:12:47]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=7% sta=7 gut=3 ski=2>
INFO  [19:12:50]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(348, 843), similarity=0.91
INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=11% gut=9 pow=6 spd=4 ski=2 ptn=spd@2^(0%),spd@2(0%),tm(0%)>
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_4.png
INFO  [19:12:53]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(62, 843), similarity=0.95
INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=9% spd=14 pow=8 ski=3 ptn=spd@2^(18%),pow@3^(18%),spd@2^(51%),tm(85%)>
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_5.png
INFO  [19:12:56]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(444, 843), similarity=0.95
INFO  [19:12:56]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [19:12:56]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=0% wis=6 ski=3 spd=2 ptn=tm(0%)>

```

**Comment by akhialomgir** [comment]
> 
> 
> 这些图 1.7.6 全部正常识别 应该是已经修过了
> 
> ```
> PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_1.png
> INFO  [19:12:44]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:44]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=9% pow=6 sta=4 ski=2 ptn=oth>
> PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_2.png
> INFO  [19:12:46]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(157, 843), similarity=0.92
> INFO  [19:12:47]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=7% sta=7 gut=3 ski=2>
> INFO  [19:12:50]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(348, 843), similarity=0.91
> INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:50]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=11% gut=9 pow=6 spd=4 ski=2 ptn=spd@2^(0%),spd@2(0%),tm(0%)>
> PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_3.png
> INFO  [19:14:52]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(348, 843), similarity=0.91
> INFO  [19:14:52]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:14:52]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:14:52]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:14:52]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=11% gut=9 pow=6 spd=4 ski=2 ptn=spd@2^(0%),spd@2(0%),tm(0%)>
> PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_4.png
> INFO  [19:12:53]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(62, 843), similarity=0.95
> INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:53]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=9% spd=14 pow=8 ski=3 ptn=spd@2^(18%),pow@3^(18%),spd@2^(51%),tm(85%)>
> PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\.local\issue181_5.png
> INFO  [19:12:56]:auto_derby.template:180: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(444, 843), similarity=0.95
> INFO  [19:12:56]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> INFO  [19:12:56]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_soul_full.png',)
> Training<lv=1 fail=0% wis=6 ski=3 spd=2 ptn=tm(0%)>
> ```
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7111610/auto_derby.log)
![last_screenshot](https://user-images.githubusercontent.com/50533365/132127264-4479af06-c012-4782-9624-d11eabf861e7.png)
![9ae8b03fa86ef37a42f3405139f1b](https://user-images.githubusercontent.com/50533365/132127267-3c004cd0-ff1d-4165-b94c-c3b4ea9b9d24.png)
![4677f6addfb1489481bf5de818a3d](https://user-images.githubusercontent.com/50533365/132127272-a5f10e24-4ed5-4d44-87e5-d64eddc46c7c.png)
![bc66d8349d21661d561985ddbfa20](https://user-images.githubusercontent.com/50533365/132127277-4c1a4569-2544-43c7-a722-a529251afc3f.png)
![a06f305c62d5407ac5255708ab464](https://user-images.githubusercontent.com/50533365/132127283-959a9938-fe54-44fe-8413-31b8187d0a2d.png)
![d2cc20e01915e01fa05903236b766](https://user-images.githubusercontent.com/50533365/132127285-bb69e069-9254-482a-97e4-85d89718b2a2.png)
