### ISSUE TITLE
训练识别错误

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#182]
目前用1.7.5跑也遇到这个错误，不知道贴在这边合不合适
[aoharu_debug.zip](https://github.com/NateScarlet/auto-derby/files/7111408/aoharu_debug.zip)

_Originally posted by @gs040664 in https://github.com/NateScarlet/auto-derby/issues/181#issuecomment-913125090_

**Comment by gs040664** [comment]
了解了，以后遇到新问题都开新issue，再麻烦大神协助处理

**Comment by NateScarlet** [comment]
样本 7d18b9f04a65b853efcab49cefa7890b 复现

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/132123775-800b4271-3710-4f2e-a4eb-3ccd84395325.png)

又是红边没封口
