### ISSUE TITLE
训练识别错误

### ISSUE THREAD

**Issue by gs040664** [NateScarlet/auto-derby#183]
错误信息
ValueError: invalid literal for int() with base 10: ''
[aoharu_debug.zip](https://github.com/NateScarlet/auto-derby/files/7111627/aoharu_debug.zip)

**Comment by NateScarlet** [comment]
037818cf5faa8c7771dc41e27a6b8ccd 复现

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/132337649-a38d1a2e-cbdd-489b-9105-e64e01affbb0.png)

又是红框提取没封口
