### ISSUE TITLE
ADB 青春杯团体赛识别问题

### ISSUE THREAD

**Issue by akhialomgir** [NateScarlet/auto-derby#186]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7125855/auto_derby.log)
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7125861/debug.zip)
![last_screenshot](https://user-images.githubusercontent.com/50533365/132447041-5023bd21-634f-4a34-8995-69bcdfda228c.png)

**Comment by NateScarlet** [comment]
分辨率不一样导致模版匹配度只有 0.89  降低这里要求的匹配度应该就行了
