### ISSUE TITLE
Program crush immediately

### ISSUE THREAD

**Issue by Rivers47** [NateScarlet/auto-derby#188]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7192667/auto_derby.log)

**Comment by NateScarlet** [comment]
need debug/last_screenshot.png

**Comment by NateScarlet** [comment]
why ocr_labels includes `c007f03ffc3f3c201e001f00ff1fff7f7ffc1ff01ff01ef03ef8fc7ff83fc007,n` ?
there should be no recognized text include `n` 

maybe remove that line in `data/ocr_labels.csv` and try agian

**Comment by Rivers47** [comment]
> need debug/last_screenshot.png

![last_screenshot](https://user-images.githubusercontent.com/30615204/134067097-2eb426d9-56b8-47ec-a3bf-ec7cdbcf48b9.png)

**Comment by NateScarlet** [comment]
> Any idea why the line is generated?

because when script ask what character displaying, you pressed `n` twice

**Comment by NateScarlet** [comment]
Given image can be recognized without error

```
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_command_scene.py .\134067097-2eb426d9-56b8-47ec-a3bf-ec7cdbcf48b9.png
INFO  [11:18:18]:auto_derby.template:196: no match: tmpl=('single_mode_aoharu_class_detail_button.png',)
INFO  [11:18:18]:auto_derby.template:180: match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(114, 165), similarity=0.99
INFO  [11:18:18]:auto_derby.template:180: match: tmpl=tmpl<single_mode_character_detail_button.png>, pos=(466, 607), similarity=0.95
Context<scenario=新設！　URAファイナルズ！！,turn=67,mood=(1.2, 1.1),vit=0.295,spd=969,sta=613,pow=541,gut=266,wis=400,fan=0,ground=,distance=,style=,condition=0>
```

try remove data/ocr_labels.csv then try again.

**Comment by Rivers47** [comment]
An thanks!
The scripted asked me what character was displaying during choosing a training category, which I thought was weird (and the console was flooded by the debug output, so I couldn't even find the line containing the character in question)

**Comment by NateScarlet** [comment]
in that case, just press enter without other key.
it will ask again
