### ISSUE TITLE
使用友人卡时 自动训练进入死循环

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#20]
最后一次运行文件如下：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6598989/auto_derby.log)
出现死循环的图片如下：
![image](https://user-images.githubusercontent.com/37131177/120813294-55bf0580-c580-11eb-90ff-6af04dc1a96f.png)
![image](https://user-images.githubusercontent.com/37131177/120813313-5b1c5000-c580-11eb-9c71-844c2e462a36.png)
![image](https://user-images.githubusercontent.com/37131177/120813327-5d7eaa00-c580-11eb-8f33-bc97fca10167.png)
![image](https://user-images.githubusercontent.com/37131177/120813340-5fe10400-c580-11eb-8848-b02203ddf595.png)
![image](https://user-images.githubusercontent.com/37131177/120813348-62435e00-c580-11eb-9765-38f68a33e00f.png)
![image](https://user-images.githubusercontent.com/37131177/120813372-67a0a880-c580-11eb-9f56-b013abc50d50.png)
死循环就是在以上图片之间循环选择。
重新运行`launcher.cmd`同样复现.

**Comment by NateScarlet** [comment]
还不支持友人卡……

**Comment by NateScarlet** [comment]
你手动选一个外出

**Comment by NateScarlet** [comment]
这个是你所有的训练都没达到期望值 所以外出休息 但是它不知道怎么选友人卡

```
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:167: expected score:	22.08
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	21.41:	Training<spd=15, pow=6, ski=2>
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	19.66:	Training<pow=11, sta=8, ski=2>
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	18.86:	Training<sta=18, per=6, ski=3>
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	16.93:	Training<per=13, spd=5, pow=5, ski=2>
INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	16.63:	Training<int=15, ski=4, spd=3>
```

**Comment by fatinghenji** [comment]
> 这个是你所有的训练都没达到期望值 所以外出休息 但是它不知道怎么选友人卡
> 
> ```
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:167: expected score:	22.08
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	21.41:	Training<spd=15, pow=6, ski=2>
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	19.66:	Training<pow=11, sta=8, ski=2>
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	18.86:	Training<sta=18, per=6, ski=3>
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	16.93:	Training<per=13, spd=5, pow=5, ski=2>
> INFO  [2021-06-04 21:56:29]:auto_derby.jobs.nurturing:172: score:	16.63:	Training<int=15, ski=4, spd=3>
> ```

懂了，谢谢大佬开发的工具。
