### ISSUE TITLE
動畫沒跑完就檢測時間

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#201]
![last_screenshot](https://user-images.githubusercontent.com/16464896/136829993-b0b8f7f2-452d-4103-b8b5-5a932c5ad4fc.png)
這時會把露出來那一點棕色當作是字

**Comment by NateScarlet** [comment]
什么版本 这个修过 https://github.com/NateScarlet/auto-derby/commit/0ed876e6b54c038e0d454cb6801730cc2b9fbb7d

**Comment by NateScarlet** [comment]
那试试开发分支 最近的修改都是等这个界面的动画

**Comment by Small-Ku** [comment]
好的，我再試試開發分支

**Comment by NateScarlet** [comment]
改成不靠时间 出错最多重试10次 看行不行
