### ISSUE TITLE
脚本经常因为点击失败卡住。。

### ISSUE THREAD

**Issue by Sylphinford** [NateScarlet/auto-derby#210]
![QQ截图20211030105856](https://user-images.githubusercontent.com/43917892/139526865-ed236d10-8ea5-488e-b455-95f2d9a9aadc.png)
脚本经常像图上这样卡住
我仔细观察了一下发现
脚本点击了按钮，比如比赛，但实际上不知道为啥，程序界面没有回应，依然在主页
而脚本以为已经进去比赛列表了，然后就卡住，
这个在其他的按钮，训练，详情等都会出现。

**Comment by NateScarlet** [comment]
为啥会没点击成功 你是不是在脚本执行时操作了 #206 

或者是因为你开的这选项识别的干扰

**Comment by Sylphinford** [comment]
中途没有操作，就挂着
那个umacruise 是stop状态，也没有遮挡程序界面
不知道为啥，经常会出现点击不成功
有时候刚启动就卡住，脚本开始时不是会点击查看粉丝详情吗，
经常这里就卡住了然后无限循环 no match

**Comment by NateScarlet** [comment]
开debug 发日志和 last_screeenshot.png

**Comment by NateScarlet** [comment]
> 那个umacruise 是stop状态，也没有遮挡程序界面

说不定只要开了就有影响，不开看能不能重现

**Comment by Sylphinford** [comment]
[debug.2.zip](https://github.com/NateScarlet/auto-derby/files/7446252/debug.2.zip)
[debug.3.zip](https://github.com/NateScarlet/auto-derby/files/7446253/debug.3.zip)
2号是3号卡住后，重开立刻卡住的
这里是关掉umacruise的

**Comment by NateScarlet** [comment]
问题应该是点击前设置游戏窗口为活动窗口失败 所以点击没点击到窗口里面 你启动脚本后手动激活游戏窗口试试

```
WARNING[2021-10-30 11:48:13]:auto_derby.window:121: recover foreground window failed: (0, 'SetForegroundWindow', 'No error message is available')
```

再发下 launcher.log 里面有系统环境信息

**Comment by NateScarlet** [comment]
这个警告会在尝试恢复之前的前台窗口但窗口已关闭的时候出现 你是不是前台会有打开时间很短的其他窗口

**Comment by NateScarlet** [comment]
```
INFO  [2021-10-30 11:42:54]:auto_derby.template:180: match: tmpl=tmpl<single_mode_race_start_button.png>, pos=(351, 796), similarity=0.96
DEBUG [2021-10-30 11:42:54]:auto_derby.clients.dmm:59: tap: point=(351, 796)
```
点击比赛开始按钮的时候失败了11次 第12次才成功

**Comment by Sylphinford** [comment]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/7446304/launcher.log)

启动脚本前，游戏窗口在桌面前台，我也挪到了窗口不会被脚本启动的界面挡住的位置

**Comment by NateScarlet** [comment]
可能是什么软件的弹窗 截图现在用的是后台截图 遮挡不影响

**Comment by Sylphinford** [comment]
弹窗吗，远程挂机的，没有一直看着，所以不知道会不会有啥弹窗。
我明天试试把游戏窗口放左边

**Comment by Sylphinford** [comment]
但是好像也不对，我观察发现是点击失败导致卡住时那次，是看着过程的，没有弹窗影响

**Comment by NateScarlet** [comment]
试试 f411c4ea00fe54167aa4d54969c5408cd0e418bb 我加了当前窗口到debug日志 而且启动时设置游戏窗口为前台

**Comment by Sylphinford** [comment]
[debug2开头卡住.zip](https://github.com/NateScarlet/auto-derby/files/7447369/debug2.zip
[debug1训练卡住.zip](https://github.com/NateScarlet/auto-derby/files/7447371/debug1.zip)
[debug3 训练卡住.zip](https://github.com/NateScarlet/auto-derby/files/7447382/debug3.zip)
[debug4 比赛结束卡.zip](https://github.com/NateScarlet/auto-derby/files/7447383/debug4.zip)
)
4号这个比赛结束后卡住了，我点了一下又开始跑了了，然后又卡在训练上了

**Comment by NateScarlet** [comment]
确实是前台窗口被切成别的了，如果你自己没动的话应该是有别的程序在抢前台窗口

```
INFO  [2021-10-30 15:16:40]:auto_derby.clients.dmm:55: foregrounded game window: handle=986368
DEBUG [2021-10-30 15:32:26]:auto_derby.window:131: foreground window: h_wnd=2821100
```

我一会加详细debug看窗口标题是什么

**Comment by NateScarlet** [comment]
用 07802b6b0555c9e0b3f7aec9aad5e887f55815bc 然后开 debug_window 插件

这个会在切换前台窗口前记录窗口名称和窗口进程信息

**Comment by Sylphinford** [comment]
[auto_derby训练.zip](https://github.com/NateScarlet/auto-derby/files/7448579/auto_derby.zip)
[auto_derby开头.zip](https://github.com/NateScarlet/auto-derby/files/7448581/auto_derby.zip)
[auto_derby比赛1.zip](https://github.com/NateScarlet/auto-derby/files/7448582/auto_derby.1.zip)
[auto_derby比赛2.zip](https://github.com/NateScarlet/auto-derby/files/7448583/auto_derby.2.zip)
[auto_derby比赛3.zip](https://github.com/NateScarlet/auto-derby/files/7448584/auto_derby.3.zip)
[auto_derby崩了.zip](https://github.com/NateScarlet/auto-derby/files/7448590/auto_derby.zip)
[auto_derby比赛4.zip](https://github.com/NateScarlet/auto-derby/files/7448595/auto_derby.4.zip)

有个脚本自己停了

**Comment by NateScarlet** [comment]
崩了是 #201 没弄好 dafb7dd01dbe22fd620e4bf241e976250015d4a9 修了

**Comment by NateScarlet** [comment]
把 Chrome Remote Desktop 关了再试

```
DEBUG [2021-10-31 10:23:00]:debug_window:21: process 8040: name='explorer.exe' executable='C:\WINDOWS\Explorer.EXE' command='C:\WINDOWS\Explorer.EXE'
DEBUG [2021-10-31 09:37:02]:debug_window:21: process 2484: name='remoting_desktop.exe' executable='C:\Program Files (x86)\Google\Chrome Remote Desktop\92.0.4515.41\remoting_desktop.exe' command='"C:\Program Files (x86)\Google\Chrome Remote Desktop\92.0.4515.41\remoting_desktop.exe"  --mojo-named-platform-channel-pipe=4432.5684.17266079970271058380 --mojo-pipe-token=898730842735747553 --type=desktop'
```

**Comment by NateScarlet** [comment]
有的日志当前窗口就是游戏窗口 没有问题

如果是动了鼠标导致点歪了卡住那是正常的 没法支持用户同时操作

不然就是不知为何你游戏窗口点了没效果 难道是正好在检查窗口到点击这段时间里切了窗口

**Comment by Sylphinford** [comment]
远程桌面也会影响吗。有点难，挂机不能动，只能远程到空闲的电脑上挂。

Explorer.EXE 抢前台窗口，看不懂，过程中是挂机状态，没去点资源管理器。

**Comment by NateScarlet** [comment]
不用远程测试下是不是这个的问题 或者换个别的远程

**Comment by Sylphinford** [comment]
本地跑了一次脚本，目前没出现窗口被抢。
能本地跑的时间不多，明天再试试

**Comment by Sylphinford** [comment]
今天本地跑脚本，这个时间自动跳出来然后卡住了。
这个现象之前见到过几次。不知道为啥。。

![QQ截图20211101205043](https://user-images.githubusercontent.com/43917892/139733088-f403aedd-be82-4157-97a1-1d519432e1c2.jpg)
[auto_derby.zip](https://github.com/NateScarlet/auto-derby/files/7455788/auto_derby.zip)

**Comment by NateScarlet** [comment]
这属于你windows的问题了 和之前说的应该不是同一个问题  你桌面没任务栏?

**Comment by NateScarlet** [comment]
查了下这面板快捷键是win+alt+d 可能你自己按到了

**Comment by NateScarlet** [comment]
```
DEBUG [2021-11-01 20:46:26]:auto_derby.clients.dmm:61: tap: point=(42, 911)
DEBUG [2021-11-01 20:46:26]:auto_derby.window:133: foreground window: h_wnd=2298708
DEBUG [2021-11-01 20:46:26]:debug_window:47: foreground window: process_id=16712 thread_id=7084 text='umamusume'
DEBUG [2021-11-01 20:46:26]:debug_window:21: process 16712: name='umamusume.exe' executable='None' command='None'
DEBUG [2021-11-01 20:46:27]:debug_window:47: foreground window: process_id=1608 thread_id=18624 text='日期和时间信息'
DEBUG [2021-11-01 20:46:27]:debug_window:21: process 1608: name='ShellExperienceHost.exe' executable='C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe' command='"C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe" -ServerName:App.AppXtk181tbxbce2qsex02s8tw7hfxa9xb3t.mca'
```

出错的时候是点击右下角 可能是你鼠标同时动了导致点到外面，应该不会是坐标转换有问题 不然应该是没法点到其他按钮的

实在不行你在跑脚本前把 explorer.exe 杀了 用完再手动启动

**Comment by NateScarlet** [comment]
把 explorer.exe 杀了还会被 explorer 卡住？

**Comment by NateScarlet** [comment]
这几个月你是唯一遇到这个问题的，可能环境有什么没注意到的问题。

windows 相关问题有可能新建个别的用户运行就能解决。

如果还是不行那就上模拟器用 adb 控制，完全绕过窗口鼠标这一套。

**Comment by Sylphinford** [comment]
试了下adb  夜神模拟器安卓9
脚本读取不到截图，，全黑的
控制权确实有了，，开启脚本能自动切换到游戏
![last_screenshot](https://user-images.githubusercontent.com/43917892/140199126-a5b02b04-b008-4856-80a2-c2fddebdd1fa.png)

**Comment by NateScarlet** [comment]
测试直接命令行用adb shell screencap截图 

如果可以就是adb_shell模块问题 不行就是模拟器问题 我用蓝叠hyper-v版测试的

**Comment by NateScarlet** [comment]
分辨率必须是 9:16 的 我测试的时候 1080x1920 才和电脑 540x960 识别精度一样

**Comment by Sylphinford** [comment]
我试了，，adb可以截图

![QQ截图20211103230523](https://user-images.githubusercontent.com/43917892/140408686-e5c7787f-ee46-4658-bb95-e2450724e1a3.jpg)
![QQ截图20211104204058](https://user-images.githubusercontent.com/43917892/140408726-8be6ed71-c6c5-40ab-ac91-f97083d81096.jpg)

就是脚本读取的截图是全黑的

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby/blob/c2e5c138125cac6dc13dbd74045161ca03f6e5cf/auto_derby/clients/adb.py#L82- L87 取消注释 下面直到return(不含)的部分注释掉试试

**Comment by Sylphinford** [comment]
变成这样了
![QQ截图20211105200957](https://user-images.githubusercontent.com/43917892/140565538-32a95e20-0609-4279-9628-7f13c1bcc7dd.jpg)

应该没注释错吧
![QQ截图20211105201047](https://user-images.githubusercontent.com/43917892/140565656-c65fb312-0953-4777-84cb-34bb3c0ad773.jpg)

**Comment by NateScarlet** [comment]
python的缩进空格必须是4的倍数 你有的行是9个空格

**Comment by NateScarlet** [comment]
加了启动时自动选择速度最快且结果不为纯色的截图方法 c8045ae2e1efdc196cba7c0a5b95a8d0432ac5e6

**Comment by Sylphinford** [comment]
好了。。现在脚本能看到截图了

**Comment by Sylphinford** [comment]
这个unexpected exception错误是什么问题
[auto_derby1.zip](https://github.com/NateScarlet/auto-derby/files/7577145/auto_derby1.zip)
[auto_derby2.zip](https://github.com/NateScarlet/auto-derby/files/7577146/auto_derby2.zip)
[auto_derby3.zip](https://github.com/NateScarlet/auto-derby/files/7577147/auto_derby3.zip)

**Comment by NateScarlet** [comment]
一个 issue 只处理一个问题

这个像是 #102 或者 #204
