### ISSUE TITLE
在使用py -3.8 -m pip install -r requirements.txt执行中，会有报错

### ISSUE THREAD

**Issue by LeeIwichkokoro** [NateScarlet/auto-derby#211]
![image](https://user-images.githubusercontent.com/93388785/139564189-9f241dbb-1767-4f51-9628-29d9d3f5f4ef.png)
如图上所示

**Comment by NateScarlet** [comment]
更新 pip

Duplicate of #203

而且你这错误信息截图不完整 要是你是第一个遇到这问题的人我是看不出来原因的
