### ISSUE TITLE
自动出门比赛因为找不到对应赛事而报错停止

### ISSUE THREAD

**Issue by debi-derby** [NateScarlet/auto-derby#212]
集中发生在第二年/第三年3月上下

示例：
INFO  [2021-11-12 09:55:09]:auto_derby.template:180: match: tmpl=tmpl<single_mode_race_menu_fan_icon.png>, pos=(203, 586), similarity=0.95
ERROR [2021-11-12 09:55:09]:__main__:123: unexpected exception
Traceback (most recent call last):
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\__main__.py", line 119, in <module>
    main()
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\__main__.py", line 90, in main
    job()
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\jobs\nurturing.py", line 225, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\jobs\nurturing.py", line 88, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\jobs\nurturing.py", line 52, in _handle_turn
    command_with_scores[0][0].execute(ctx)
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\single_mode\commands\race.py", line 85, in execute
    scene.choose_race(ctx, self.race)
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\scenes\single_mode\race_menu.py", line 82, in choose_race
    for race2, pos in find_by_race_menu_image(ctx, template.screenshot()):
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\single_mode\race\game_data.py", line 263, in find_by_race_menu_image
    for i in _find_by_race_menu_item(ctx, screenshot.crop(bbox)):
  File "C:\Downloads\auto-derby-master\auto-derby-master\auto_derby\single_mode\race\game_data.py", line 248, in _find_by_race_menu_item
    raise ValueError("_find_by_race_menu_item: no race match spec: %s", full_spec)
ValueError: ('_find_by_race_menu_item: no race match spec: %s', ((2, 5, 1), '中山', 1, 2000, 1, 2, 5400, (200,)))

**Comment by NateScarlet** [comment]
错误信息里面是5月 发debug/last_screenshot.png

**Comment by NateScarlet** [comment]
感觉像是 #102

**Comment by debi-derby** [comment]
我的debug文件夹里永远是空的，是覆盖了么

主要不知道是怎么和游戏交互的，不然我可以试着debug一下，是通过不停的截图来辨识么？

**Comment by NateScarlet** [comment]
[问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)
[FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ)

**Comment by debi-derby** [comment]
我是直接命令行启动的(启动器会报错退出，debug以及各备份文件夹没有看到过图片，下次报错时我再看看)

**Comment by NateScarlet** [comment]
命令行默认不开 debug
启动器报什么错

**Comment by debi-derby** [comment]
Matching current displaying image: value=離, similarity=0.797.
所以这个image也是要在debug文件夹里看么？我一直很疑惑，因为没有看到过这个"image”.
启动器我recover一下错误试试

**Comment by NateScarlet** [comment]
命令行debug要设环境变量 参考

https://github.com/NateScarlet/auto-derby/blob/c2e5c138125cac6dc13dbd74045161ca03f6e5cf/auto_derby/launcher/launcher.ps1#L104-L111

**Comment by NateScarlet** [comment]
> Matching current displaying image: value=離, similarity=0.797.

这个指的是悬浮窗口显示的图片

**Comment by debi-derby** [comment]
> > Matching current displaying image: value=離, similarity=0.797.
> 
> 这个指的是悬浮窗口显示的图片

这个悬浮窗口和游戏窗口有区别么？ 我并没有在游戏窗口看到任何“凸显”辨识图片的外标识

**Comment by NateScarlet** [comment]
看你任务栏 是单独窗口显示的图片

**Comment by debi-derby** [comment]
> 命令行默认不开 debug 启动器报什么错
启动器打开以后如下
![luancher1](https://user-images.githubusercontent.com/94163456/141607577-d7894f8a-e03b-4819-8c5d-976d8119f5de.png)

我如果在python executable 那里选择choose， 会弹出一个命令窗，然后print一个error以后闪退

我如果直接选择start，也是会闪退然后留下一个新的命令窗
![launcher2](https://user-images.githubusercontent.com/94163456/141607623-1b4e9d6b-03c3-4ddf-bfb4-a55184bb5253.png)

我的python 是通过anaconda装的然后改了环境变量，不知道是不是和这个有关系

**Comment by debi-derby** [comment]
> 看你任务栏 是单独窗口显示的图片
这个问题现在清楚了

**Comment by NateScarlet** [comment]
为什么输入框显示成这样 能直接输入吗

和下面输入框用的是同样的实现 而且就算没装官方py启动器也应该只是空的而已

**Comment by debi-derby** [comment]
> 为什么输入框显示成这样 能直接输入吗
> 
> 和下面输入框用的是同样的实现 而且就算没装官方py启动器也应该只是空的而已

那个蓝色的条是因为我点了，正常打开就是和下面adb address一样的
launcher好像也有debug log
如果我直接点start:
[launcher.log](https://github.com/NateScarlet/auto-derby/files/7531490/launcher.log)
如果我试图设置python路径：
[launcher.log](https://github.com/NateScarlet/auto-derby/files/7531491/launcher.log)

**Comment by debi-derby** [comment]
> 命令行debug要设环境变量 参考
> 
> https://github.com/NateScarlet/auto-derby/blob/c2e5c138125cac6dc13dbd74045161ca03f6e5cf/auto_derby/launcher/launcher.ps1#L104-L111

这个环境变量在对应的文件里也有，但是命令行怎么启动debug， 我看usage里面没有debug这个选项？

usage: __main__.py [-h] [-p PLUGIN [PLUGIN ...]] [--adb ADB] job

positional arguments:
  job

optional arguments:
  -h, --help            show this help message and exit
  -p PLUGIN [PLUGIN ...], --plugin PLUGIN [PLUGIN ...]
                        plugin names to enable
  --adb ADB             adb connect address like `127.0.0.1:5037`

**Comment by NateScarlet** [comment]
环境变量属于基本概念 自己搜

**Comment by NateScarlet** [comment]
当前值为空时打不开选择框修了 9b282918705bec4188bcfd3e9f6c5a4d3b5b81a1
