### ISSUE TITLE
不能识别送角色碎片的比赛

### ISSUE THREAD

**Issue by kafu0611** [NateScarlet/auto-derby#216]
截图：
![last_screenshot](https://user-images.githubusercontent.com/10711790/145675220-0e650a3d-8ac1-4f0d-923e-46d88f85e472.png)
可能是新加入的G1标识导致识别错误出现无法继续进行

log：
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7696913/debug.zip)

**Comment by NateScarlet** [comment]
这是啥 我没见过
你关闭比赛推荐还会有吗

![图片](https://user-images.githubusercontent.com/21083014/145678866-a6ba25dc-8528-45c9-b10e-7c26b0583db5.png)

**Comment by kafu0611** [comment]
更新客户端之后就会出现
应该和关闭比赛推荐没有关系

**Comment by NateScarlet** [comment]
应该是新活动加的每天送一片碎片
https://dmg.umamusume.jp/news/detail?id=470

**Comment by NateScarlet** [comment]
暂时你先手动把这碎片拿了就应该不会显示了
我改成从右边取色

**Comment by NateScarlet** [comment]
改成从底部半径2像素的范围中找最匹配的颜色了
