### ISSUE TITLE
找不到 URA

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#217]
朋友有遇到
![圖片](https://user-images.githubusercontent.com/16464896/145711955-a460a948-2efc-4e29-a80f-8a3e3f35e843.png)

然後我也遇到了
![last_screenshot](https://user-images.githubusercontent.com/16464896/145711994-3861f5ce-0ce5-4419-b2f4-1b58ad9405db.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7698697/auto_derby.log)

我有手動跑 extract_single_mode_races.py，但仍出錯

**Comment by Small-Ku** [comment]
可能我DMM版的太久沒有更新過了，現在先試試更新再跑

**Comment by NateScarlet** [comment]
用1.12.0 应该不会有这问题 1.21.1改了比赛等级的识别位置
