### ISSUE TITLE
错误的将%符号识别为单独字符

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#218]
- 最后的OCR图片
![last_screenshot](https://user-images.githubusercontent.com/37131177/145767591-12016e7a-5194-4fd7-8d06-6ded35484225.png)
- 日志文件
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7701685/auto_derby.log)

**Comment by fatinghenji** [comment]
应该是日志显示有延迟错误，不是程序bug

**Comment by NateScarlet** [comment]
不是延迟错误 训练识别用了多线程识别 不等待识别完毕直接切下一张图提高性能 训练相关得看 debug/single_mode_training_images
