### ISSUE TITLE
暑期集训 夏日合宿 能否 以训练为主、不跑比赛

### ISSUE THREAD

**Issue by issenn** [NateScarlet/auto-derby#220]
建议
夏日合宿前6月后半保留70%以上的体力
7月8月以训练为主，不要跑比赛
以智力锻炼（在智力锻炼上有人）代替休息。

**Comment by NateScarlet** [comment]
[FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B5%9B%E7%A8%8B)

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
