### ISSUE TITLE
育成賽事後會自動卡住

### ISSUE THREAD

**Issue by newyen2** [NateScarlet/auto-derby#223]
![94](https://user-images.githubusercontent.com/29043416/146487084-2806e268-db59-425e-a59a-3cd7152d3b35.PNG)
好幾次跑完賽事都會卡在這個畫面
![156](https://user-images.githubusercontent.com/29043416/146487395-78cadf08-45c9-44e9-b38a-dbd6f135940f.PNG)
剛從1.10轉成1.13.1遇到的問題，有使用以下plugins:
afk,自訂賽事,more_g1,SSR樫本理子

附上log:https://file.io/DyvLJ7OZZGwm

**Comment by NateScarlet** [comment]
应该是没有自动创建 data 文件夹导致的

手动在项目目录下创建一个 data 文件夹应该就能解决

**Comment by newyen2** [comment]
了解，我晚些時候測試一下
