### ISSUE TITLE
unexpected exception 朝日杯卡住

### ISSUE THREAD

**Issue by Sylphinford** [NateScarlet/auto-derby#225]
这个活动出来后，这里就完全卡住了，重试了都是这个错误。。只能手动把这关过了再重开脚本
是不是旁边多个了图标的问题

py -3.8 ./scripts/extract_single_mode_races.py 试了，没效果

![last_screenshot](https://user-images.githubusercontent.com/43917892/146653474-af083d5e-1fb6-475f-98bb-d5b31e4a83f4.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7739830/auto_derby.log)

**Comment by NateScarlet** [comment]
Duplicate of #216 

你确定用的最新版？
