### ISSUE TITLE
无法启动脚本

### ISSUE THREAD

**Issue by zjj871114037** [NateScarlet/auto-derby#226]
`已启动脚本，输出文件为 C:\Users\HASEE\Desktop\auto-derby-master\launcher.log

Job                       : nurturing
Debug                     : False
CheckUpdate               : True
PythonExecutablePath      : C:\Users\HASEE\AppData\Local\Programs\Python\Python38-32\python.exe
SingleModeChoicesDataPath : C:\Users\HASEE\Desktop\auto-derby-master\data\single_mode_choices.csv
PauseIfRaceOrderGt        : 2
Plugins                   : 20%training,auto_crane,more_g1,no_ocr_prompt
TargetTrainingLevels      : 5,,,0,4
ADBAddress                :
Version                   : 1.13.4
Python Version            : Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]

command:
title auto-derby: 1.13.4
cd /d "C:\Users\HASEE\Desktop\auto-derby-master"
set "DEBUG="
set "AUTO_DERBY_LAST_SCREENSHOT_SAVE_PATH="
set "AUTO_DERBY_OCR_IMAGE_PATH="
set "AUTO_DERBY_SINGLE_MODE_EVENT_IMAGE_PATH="
set "AUTO_DERBY_SINGLE_MODE_TRAINING_IMAGE_PATH="
set "AUTO_DERBY_SINGLE_MODE_CHOICE_PATH=C:\Users\HASEE\Desktop\auto-derby-master\data\single_mode_choices.csv"
set "AUTO_DERBY_PAUSE_IF_RACE_ORDER_GT=2"
set "AUTO_DERBY_PLUGINS=20%training,auto_crane,more_g1,no_ocr_prompt"
set "AUTO_DERBY_SINGLE_MODE_TARGET_TRAINING_LEVELS=5,,,0,4"
set "AUTO_DERBY_ADB_ADDRESS="
set "AUTO_DERBY_CHECK_UPDATE=true"
"C:\Users\HASEE\AppData\Local\Programs\Python\Python38-32\python.exe" -m auto_derby nurturing
start "auto-derby launcher" cmd.exe /c .\launcher.cmd
exit

**********************
Windows PowerShell 脚本结束
结束时间: 20211220133502
**********************
`
![捕获](https://user-images.githubusercontent.com/31470064/146717342-4310d949-d79c-4906-92d8-77ceb5ceda36.PNG)

**Comment by starik222** [comment]
I had the same problem on one of my computers. If I understood correctly, this problem is related to versions of OpenSSL libraries. I don’t know where these libraries are in pure python, since I use Anaconda. In Anaconda, I copied the libssl-1_1-x64.dll and libcrypto-1_1-x64.dll libraries from the "Anaconda3\Library\bin" directory to the "Anaconda3\DLLs" directory. This solved the problem.

**Comment by NateScarlet** [comment]
you can just uncheck `Check update` from launcher
