### ISSUE TITLE
青春杯无法识别

### ISSUE THREAD

**Issue by woaiwan** [NateScarlet/auto-derby#228]
![last_screenshot](https://user-images.githubusercontent.com/36910418/148686238-e8dc6257-1a0f-476b-b664-786ea585d584.png)
[debug.zip](https://github.com/NateScarlet/auto-derby/files/7835228/debug.zip)
[launcher - 副本.log](https://github.com/NateScarlet/auto-derby/files/7835231/launcher.-.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/7835232/auto_derby.log)

**Comment by NateScarlet** [comment]
你的data/ocr_labels.csv格式不对 检查文件或者整个删除后重试
