### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#23]
以下是日志文件。
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6603730/launcher.log)

**Comment by NateScarlet** [comment]
你的 single_mode_choices.json 是空的

**Comment by NateScarlet** [comment]
如果你要自己来选择事件 直接把选择数据保存在别的位置就行了

启动器会记住填写的路径

**Comment by fatinghenji** [comment]
好的。
