### ISSUE TITLE
竞技场宝箱局出现在中或下时无法识别

### ISSUE THREAD

**Issue by debi-derby** [NateScarlet/auto-derby#230]
近些时的宝箱局如果出现在最下面，无法准确识别，会默认开始第二个

**Comment by NateScarlet** [comment]
图标有动画 只识别其中一帧 多来几局应该就能识别了 反正宝箱不点会一直在

**Comment by NateScarlet** [comment]
看了下代码发现只检查最上面的那局 需要下面有宝箱的截图来测试

**Comment by debi-derby** [comment]
我下次看到了截图上传

**Comment by NateScarlet** [comment]
不需要截图了 

通过检测对应区域是否为平滑渐变来判断有没有宝箱局
