### ISSUE TITLE
mumu模拟器，adb连接失败

### ISSUE THREAD

**Issue by sbaidaner** [NateScarlet/auto-derby#231]
![QQ截图20220122213620](https://user-images.githubusercontent.com/76510258/150640610-6c212dcc-0941-454a-8399-406285032f10.png)

adb功能挺正常的，能截图，这个问题也没百度到解决方法。。

**Comment by NateScarlet** [comment]
发日志

测试用命令行连接设置的地址

检查防火墙设置

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
