### ISSUE TITLE
2022-02-18更新后如友人卡已可外出会识别失败

### ISSUE THREAD

**Issue by jiuyi1214** [NateScarlet/auto-derby#232]
auto_derby.template:196: no match: tmpl=('single_mode_command_go_out.png',)
![last_screenshot](https://user-images.githubusercontent.com/50827476/154621096-4c35aefa-937d-443e-933a-1878fcb79906.png)

**Comment by NateScarlet** [comment]
发[日志](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)

**Comment by NateScarlet** [comment]
应该也是界面改布局了
