### ISSUE TITLE
2022-02-18更新后比赛菜单界面变更导致选不了比赛

### ISSUE THREAD

**Issue by mem1ry** [NateScarlet/auto-derby#233]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8094816/auto_derby.log)
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8094860/debug.zip)

**Comment by NateScarlet** [comment]
last_screenshot.png 是损坏的

日志显示找不到比赛菜单中的粉丝数图标

是不是在点比赛按钮的时候动了鼠标导致没点上没进入比赛菜单，是的话直接手动重新点一下就行了

**Comment by mem1ry** [comment]
重开后复现了一下
鼠标键盘不使用的情况下
训练回合可以正常训练，各项训练截图正常
屏幕显示已经进入比赛菜单  游戏界面如下
比赛界面last_screenshot.png依然是损坏的
日志信息与之前一致
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8095452/auto_derby.log)

![截图](https://user-images.githubusercontent.com/52670319/154646000-1f0d8637-2eac-4ad5-ba4e-99dd40951cea.png)

**Comment by madmaxmadmax0714** [comment]
我是程式超新手但出現同樣問題
我今天更新完DMM就出現剛剛有人提問的外出位置辨識問題,自己試一試改動相關的POS.PNG可以令程式繼續執行
但是去到自選比賽就出現樓主的問題,再試一試改相關的POS.PNG 但是這次解決不了 提高不到足夠的辨識度

我在想會不會遊戲更新後改動了圖片位置令程式辨識不能

**Comment by madmaxmadmax0714** [comment]
看上來比賽FANS人頭的位置的確有些許改動
在未更新遊戲的手機看
![WhatsApp Image 2022-02-18 at 6 00 37 PM(2)](https://user-images.githubusercontent.com/99954580/154651347-9bbe8c16-489a-4e92-a879-ca45e1d73746.jpeg)
在更新遊戲後的DMM看
![image](https://user-images.githubusercontent.com/99954580/154650727-02b3d8b6-b00a-42d5-bb9e-d3179a4cdef1.png)

**Comment by madmaxmadmax0714** [comment]
> 

把single_mode_race_menu_fan_icon.pos.png 删掉就可以繼續執行了~謝謝
但未跑完整套未知有沒有其他問題

**Comment by NateScarlet** [comment]
@madmaxmadmax0714 

> 在有主要目標的月份無限LOOP發呆

按钮往左下移动了一点 也是删 pos.png 能行

> 然後在部分月份選擇比賽時辨識文字失敗掛掉

修复版本还没跑完一局 如果我发新版本之后还会出现再发新 issue

**Comment by madmaxmadmax0714** [comment]
@NateScarlet 辛苦了。十分感謝！明天會再試一試。
