### ISSUE TITLE
识别训练效果时会被肤色影响

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#24]
以下是最后的截图以及要求填写的内容。
![image](https://user-images.githubusercontent.com/37131177/120915416-1acee600-c6d6-11eb-82f3-4b57ef8dedf7.png)
![last_screenshot local](https://user-images.githubusercontent.com/37131177/120915417-1d314000-c6d6-11eb-96ce-58a152d373dd.png)

**Comment by fatinghenji** [comment]
重新启动程序也会稳定复现
每次到这个页面都要求填写识别结果。

**Comment by NateScarlet** [comment]
更新下版本试试 我后面改进过识别

**Comment by NateScarlet** [comment]
最新版也复现了 我检查下

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/120915690-bf9df300-c6d7-11eb-8ff9-f691d0373296.png)
胡来的右手

**Comment by NateScarlet** [comment]
在开发分支修了 开发分支我正在弄自动选跑法 还没实际测试好
