### ISSUE TITLE
青春杯无限历战

### ISSUE THREAD

**Issue by riceshowersuki** [NateScarlet/auto-derby#241]
不论使不使用赛程插件，最后都会变成历战青春杯。也不会休息，也不会外出。一旦体力清空就会开始跑比赛。于是我查了一下log发现似乎是算法出了什么问题……导致比赛和休息以及外出优先级是一样的。包括魂的优先级也变成了彩圈不是白魂……求大佬解答一下

INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:48: context: Context<scenario=アオハル杯～輝け、チームの絆～,turn=52,mood=(1.2, 1.1),vit=0.193,spd=634,sta=323,pow=425,gut=264,wis=408,fan=119033,ground=SA,distance=EAAB,style=DAAF,condition=0>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<阪神 turf 1800m OP 大阪城ステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<阪神 dart 1400m OP ポラリスステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<阪神 dart 2000m OP 仁川ステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<中山 turf 1600m OP 東風ステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<中山 turf 1200m G3 オーシャンステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<中山 turf 1800m G3 中山ウマ娘ステークス>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Race<中京 turf 2000m G2 金鯱賞>
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	Rest
INFO  [2022-02-20 00:27:50]:auto_derby.jobs.nurturing:50: score:	0.00:	GoOut<main>

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8102601/auto_derby.log)

**Comment by riceshowersuki** [comment]
以及我的赛程插件

import auto_derby
from auto_derby import single_mode


from typing import Text, Dict, Tuple

_ACTION_NONE = 0
_ACTION_BAN = 1
_ACTION_LESS = 2
_ACTION_MORE = 3
_ACTION_PICK = 4

_DEFAULT_ACTION = _ACTION_BAN

_RULES: Dict[Tuple[int, Text], int] = {
    (51, "フェブラリーステークス"): _ACTION_PICK,
    (53, "大阪杯"): _ACTION_PICK,
    (53, "高松宮記念"): _ACTION_BAN,
    (55, "天皇賞（春）"): _ACTION_PICK,
    (56, "ヴィクトリアマイル"): _ACTION_PICK,
    (58, "安田記念"): _ACTION_PICK,
    (59, "宝塚記念"): _ACTION_PICK,
    (59, "帝王賞"): _ACTION_PICK,
    (65, "スプリンターズステークス"): _ACTION_PICK,
    (67, "天皇賞（秋）"): _ACTION_PICK,
    (68, "JBCクラシック"): _ACTION_PICK,
    (68, "JBCスプリント"): _ACTION_BAN,
    (68, "JBCレディスクラシック"): _ACTION_PICK,
    (68, "エリザベス女王杯"): _ACTION_PICK,
    (69, "ジャパンカップ"): _ACTION_PICK,
    (69, "マイルチャンピオンシップ"): _ACTION_PICK,
    (70, "チャンピオンズカップ"): _ACTION_PICK,
    (71, "有馬記念"): _ACTION_PICK,
    (71, "東京大賞典"): _ACTION_PICK,
}


class Plugin(auto_derby.Plugin):
    def install(self) -> None:
        class Race(auto_derby.config.single_mode_race_class):
            def score(self, ctx: single_mode.Context) -> float:
                ret = super().score(ctx)
                action = _RULES.get(
                    (ctx.turn_count(), self.name),
                    _DEFAULT_ACTION,
                )
                if action == _ACTION_BAN:
                    ret = 0
                elif action == _ACTION_LESS:
                    ret -= 5
                elif action == _ACTION_MORE:
                    ret += 5
                elif action == _ACTION_PICK:
                    ret += 100
                return ret

        auto_derby.config.single_mode_race_class = Race


auto_derby.plugin.register(__name__, Plugin())

**Comment by NateScarlet** [comment]
`20%training` 和 `CAP` 不是内置的插件 你去掉还会出现这问题吗？

**Comment by NateScarlet** [comment]
看名字应该是 20%training 在体力低于 20% 的时候把所有评分都设成0导致的

**Comment by riceshowersuki** [comment]
了解！cap是我的赛程插件，我去掉体力插件试试

**Comment by NateScarlet** [comment]
如果想无视训练不能直接把所有训练评分设成0 因为休息外出也会被看作是一种另类的训练来计算评分

应该用 single_mode.commands.g.ignore_training_commands 返回 True 才对

**Comment by riceshowersuki** [comment]
原来如此！感谢大佬！把训练插件关掉之后确实没有问题了！我把数值修改一下试试，本来是看到插件列表里的20%成功率以下不训练的插件就下载了，没想到bug处在这里。

**Comment by NateScarlet** [comment]
那个是用户自己分享的，我自己没用过。

给维基加了提醒
