### ISSUE TITLE
青春杯選訓練項目時會卡住

### ISSUE THREAD

**Issue by denpa910** [NateScarlet/auto-derby#244]
![MIP4{TQ~2 J2G0L7(6$SA2H](https://user-images.githubusercontent.com/100455883/155836103-c552b6c7-9ed0-412d-ae5a-f748a5381fdc.png)
![FLU{N@ST~Q1KJ1CMJVV3 I2](https://user-images.githubusercontent.com/100455883/155836167-6f0c420a-b520-44d3-8a6c-1984c797ac22.png)
File "C:\Users\sakurasou\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\sakurasou\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\sakurasou\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\软件\autoderby\ver3\auto-derby-master\auto_derby\single_mode\training\training.py", line 428, in from_training_scene_v2
    self.skill = _ocr_training_effect(img.crop(bbox_group[5]))
  File "D:\软件\autoderby\ver3\auto-derby-master\auto_derby\single_mode\training\training.py", line 129, in _ocr_training_effect
    return int(text.lstrip("+"))
ValueError: invalid literal for int() with base 10: ''

作者你好，這邊情況是用了一年時間也沒遇到過這種，然後最近一週年更新後打算刷活動使用的時候就出現了選訓練項目的時候會卡住，日誌發了最新的一部分，要是發少了繼續補充，不太清楚要發多少。

**Comment by denpa910** [comment]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8146283/auto_derby.log)

**Comment by NateScarlet** [comment]
截图分辨率不对 你是给的 debug/last_screenshot.png 吗

**Comment by denpa910** [comment]
![last_screenshot](https://user-images.githubusercontent.com/100455883/155846715-ef6bd704-7a4b-4f9b-8b02-feb0559a8709.png)
上面的图不是，这个是last-screenshot，也一样是卡住的时候

**Comment by denpa910** [comment]
順便晚上換最老的URA模式養完全沒問題，只有青春杯有這個情況

**Comment by NateScarlet** [comment]
新发的这张我测试能够正常识别

```
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_training_scene.py -s aoharu .\auto_derby\test_data\single_mode\training_scene_issue244+aoharu+.png
INFO  [22:31:31]:auto_derby.template:183: match: tmpl=tmpl<single_mode_training_confirm.png>, pos=(443, 843), similarity=0.83
INFO  [22:31:32]:auto_derby.template:199: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [22:31:32]:auto_derby.template:199: no match: tmpl=('single_mode_aoharu_soul_full.png',)
INFO  [22:31:32]:auto_derby.template:199: no match: tmpl=('single_mode_aoharu_soul_full.png',)
Training<lv=1 fail=0% wis=7 spd=3 ski=3 ptn=oth,tm(18%)>
```

日志发一下

**Comment by NateScarlet** [comment]
不对 因为是训练识别异步的 需要发 debug/single_mode_training_images 中的最近五张

**Comment by denpa910** [comment]
![c041aa498b4d7e90d5786064566d3](https://user-images.githubusercontent.com/100455883/155847020-b4427f7b-ec77-4661-87e3-5034b88c9bbe.png)
![66cde7e76a126a6144bff08ff3cf5](https://user-images.githubusercontent.com/100455883/155847044-32e71c0d-c9da-4dac-a5e8-1c562e09fcec.png)
![9ee696bdcf9c3062170221fac3ebc](https://user-images.githubusercontent.com/100455883/155847057-ee868d5e-fcce-4783-a41c-299dad0260e9.png)
![30e40d34af64b3c29efc0a808895a](https://user-images.githubusercontent.com/100455883/155847094-b96a9bfc-1b5d-41f5-9160-f0d8dd9f76c2.png)
![b2181d46916945e31b8986bb14161](https://user-images.githubusercontent.com/100455883/155847108-47515308-a20b-47cf-a9fb-7057bf45fc60.png)

**Comment by NateScarlet** [comment]
用力量训练这张可以复现

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/155848137-0f5403c4-9295-4d51-8b82-664608415bae.png)
4 识别的白边没封闭导致的

**Comment by denpa910** [comment]
辛苦大佬，那这是我无法纠正的是吧？要等后续autoderby版本更新咯？

**Comment by denpa910** [comment]
开发分支是在哪里 我要下一个新的autoderby吗orz

**Comment by Small-Ku** [comment]
https://github.com/NateScarlet/auto-derby/issues/247#issuecomment-1060659788

> 還有OCR識別的問題
![252c6bcccf063ddeda21f11c3056e530](https://user-images.githubusercontent.com/16464896/157038955-ec24915e-1031-4a00-bd14-896cd3bc0634.png)
[540p](https://user-images.githubusercontent.com/16464896/157663554-74c0cf70-8c9b-49ca-b197-fb5ea47de06d.png)
[1080p](https://user-images.githubusercontent.com/16464896/157038895-83a6704b-14a2-45fb-ad0a-708babff7116.png) 

貌似是因爲這個 c6d849a 引起的，我手動 revert 在 refactor 後的版本就貌似修正了
但是我用的是 540p 的模擬器，正在讓朋友在 1080p 的模擬器裡試

**Comment by NateScarlet** [comment]
@Small-Ku #247 结束再看

你把这个修复撤销了那又会出现现在这 issue 的问题

要不然就先别练黄色主题色的角色

**Comment by NateScarlet** [comment]
我用神鹰复现然后 scenario-climax 分支修了
