### ISSUE TITLE
ADB模式青春杯会死循环绿帽一开始的说明

### ISSUE THREAD

**Issue by wwftherocksp** [NateScarlet/auto-derby#246]
模拟器跑的时候，绿帽问是否听解说，会选第一项，之后大概因为afk的关系会死循环，DMM会自动选第二项跳过说明

log：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8148408/auto_derby.log)

debug：
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8148409/debug.zip)

**Comment by NateScarlet** [comment]
关 afk 手动选第二项然后再开

**Comment by NateScarlet** [comment]
从命令行选第二项 脚本会记住选项
