### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by iiSlash** [NateScarlet/auto-derby#248]
无法启动，在import [win32gui后停止[
[launcher.log](https://github.com/NateScarlet/auto-derby/files/8194530/launcher.log)
]

**Comment by NateScarlet** [comment]
显示[找不到模块](https://github.com/NateScarlet/auto-derby/wiki/FAQ#modulenotfounderror-no-module-named-xxx)？

**Comment by NateScarlet** [comment]
而且最好用官方的 python 
miniconda 我没用过

**Comment by iiSlash** [comment]
> 显示[找不到模块](https://github.com/NateScarlet/auto-derby/wiki/FAQ#modulenotfounderror-no-module-named-xxx)？

是的，我本来用的是本机环境而且以前可以用。然后一段时间没用后我想更新就不能用了，很奇怪。然后干脆本地全部卸载换miniconda了结果也不行。
我再下个本地的试试吧

**Comment by iiSlash** [comment]
可以用了，但是巅峰杯刚进去就不行了。识别不了一个点，不知道是什么图案手动修正了几次也不行
![last_screenshot](https://user-images.githubusercontent.com/45996401/157302894-6cdad9cc-648f-4e07-9998-4332f5354100.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8208754/auto_derby.log)

[launcher.log](https://github.com/NateScarlet/auto-derby/files/8208758/launcher.log)

**Comment by NateScarlet** [comment]
谁告诉你支持巅峰杯的？#247 又没关
