### ISSUE TITLE
Daily race 支持 VERY HARD

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#249]
解決辦法應該與 #34 相同

**Comment by NateScarlet** [comment]
感觉应该直接按比赛奖励的 clear 图标找 这样未来出更多难度也不用更新 而且 #34 的问题也解决了

**Comment by Small-Ku** [comment]
所以是直接跑贏過的日常賽嗎? 畢竟的確沒有跑低級賽事的誘因

**Comment by NateScarlet** [comment]
是啊 直接跑最上面一个匹配就完了

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/158170437-87f602fa-ae4a-4400-82fc-5175b4171c78.png)

这个等 3 月 18 号更新的每日传说赛出来再搞 感觉会有影响
