### ISSUE TITLE
比赛后识别粉丝数出错

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#26]
和上午报错相似？这次不知道又是哪个出问题了，同样是可以重启复现。已经更新到最新版本了，版本号是：177958c-dirty
![image](https://user-images.githubusercontent.com/37131177/120924428-51bcf000-c706-11eb-8bd1-366d1e9c5dcf.png)
![last_screenshot local](https://user-images.githubusercontent.com/37131177/120924430-54b7e080-c706-11eb-918f-931c5cca054d.png)

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/120924487-93e63180-c706-11eb-81d7-6ccc86b32b9f.png)

是耳朵进了粉丝数区域

现在获取粉丝数暂时还没用处 是为之后的功能做准备 你可以把 

https://github.com/NateScarlet/auto-derby/blob/f39e131cc7b1808c8a3fd32539f5985b11256bb9/auto_derby/single_mode/context.py#L94

改成直接返回 0 先用着
