### ISSUE TITLE
Friend card plugin not recognized in climax scenario

### ISSUE THREAD

**Issue by gentle-knight-13** [NateScarlet/auto-derby#263]
## Description

插件 「SSR樫本理子.py」 和 「SSR駿川たづな.py」 在高潮场景中不能正确处理，因为不能识别朋友图标。
其原因是由于增加了商店按钮，改变了出游按钮和朋友图标的位置。

screenshot:
<img src="https://user-images.githubusercontent.com/98640031/159108067-f50bfb85-f092-4267-93b6-b263379d46b1.png" width="50%" />

debug log:
```
DEBUG [2022-03-19 13:45:01]:auto_derby.template:61: load: single_mode_go_out_friend_icon.pos.png
DEBUG [2022-03-19 13:45:01]:auto_derby.template:61: load: single_mode_go_out_friend_icon.png
DEBUG [2022-03-19 13:45:01]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_go_out_friend_icon.png>, pos=(311, 802), similarity=0.159
INFO  [2022-03-19 13:45:01]:auto_derby.template:199: no match: tmpl=('single_mode_go_out_friend_icon.png',)
```

问题领域 :
https://github.com/NateScarlet/auto-derby/blob/092b4c1f3ea622702042af33c737e5c4810666bb/auto_derby/scenes/single_mode/command.py#L149-L151

注：我不懂中文，所以我用了DeepL 翻译。
因此，中文可能会让人不舒服。

## P.S.
在高潮场景中使用的朋友图标和坐标的图像可以通过添加它们来识别。
https://github.com/gentle-knight-13/auto-derby/commit/5151fd09edfd5bca6e09ac734fa5d76255e90425

debug log:
```
DEBUG [2022-03-19 03:45:13]:auto_derby.template:61: load: single_mode_climax_command_go_out.pos.png
DEBUG [2022-03-19 03:45:13]:auto_derby.template:61: load: single_mode_climax_command_go_out.png
DEBUG [2022-03-19 03:45:13]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_climax_command_go_out.png>, similarity=1.000
INFO  [2022-03-19 03:45:13]:auto_derby.template:183: match: tmpl=tmpl<single_mode_climax_command_go_out.png>, pos=(175, 863), similarity=1.00
```

**Comment by NateScarlet** [comment]
thanks for the report, fixed in 28ec7fd5d50b9c5261694fca8d8d34ab1392c59b

**Comment by gentle-knight-13** [comment]
Thanks for the fix!
I checked the fix and I see that I should have added the new coordinates to the existing coordinate image.
My understanding of the source code was lacking. haha.
