### ISSUE TITLE
第三年下半檢測完所有項目後陷入死循環

### ISSUE THREAD

**Issue by newyen2** [NateScarlet/auto-derby#264]
![148984](https://user-images.githubusercontent.com/29043416/159168344-12727214-a88e-4da7-bfd0-deb3c85a275f.PNG)
檢測完持有物品、訓練項目、商店後卡死，開啟Debug模式後似乎重複執行固定幾行，等待30秒後仍然無變化

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8311478/auto_derby.log)

然後試問一下1.16.0的文字識別頁面是暫時性的還是未來版本也會存在？

**Comment by NateScarlet** [comment]
不是卡死 在穷举最佳物品方案 多等会

为什么你会有这么多 プレーンカップケーキ

文字识别页面怎么了 为什么要在未来版本去掉？

**Comment by NateScarlet** [comment]
优化了算法 只递归计算最好的子方案 你看还卡不卡 d9aaab5a49520fc529d26d73f04ad2cc7007e0d3
