### ISSUE TITLE
巅峰赛中，打开商店页面会唤起浏览器，但浏览器有报错，无限Loading中

### ISSUE THREAD

**Issue by cwbeta** [NateScarlet/auto-derby#265]
![error](https://user-images.githubusercontent.com/8300417/159280267-fc301ff1-081b-47c2-bd78-afac775852ba.png)
JS的错误显示试图获取的Javascript文件被服务器识别为text/plain类型：
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.（assets/index.ac25b9a9.js）

:8300/assets/vendor.1a7cc180.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.（assets/vendor.1a7cc180.js）

**Comment by NateScarlet** [comment]
python 什么版本 

运行

`py -3.8 -c "import mimetypes; print(mimetypes.types_map.get('.js'))"` 显示什么

**Comment by cwbeta** [comment]
py -3.8 -c "import mimetypes; print(mimetypes.types_map.get('.js'))"显示“application/javascript”
python版本3.8.3

**Comment by NateScarlet** [comment]
奇怪 那说明给的类型是正常的 你用 edge 测试下

`py -3.8 .\auto_derby\web\page_example.py` 可以打开测试页面

**Comment by cwbeta** [comment]
嗯，Edge我也试过的，也是一样的结果。

**Comment by cwbeta** [comment]
![Uploading QQ截图20220321223325.png…]()

**Comment by NateScarlet** [comment]
难道是你把js的文件类型关联过纯文本编辑器? 等我我单独搞个写死的版本你测试下

**Comment by cwbeta** [comment]
我试了把index.html里面的引用强行t改成ype="text/javascript"是能识别的，但是因为是module，不能这么写，就很尴尬

**Comment by NateScarlet** [comment]
可能是缓存 用 Ctrl+F5 强制刷新看看

**Comment by cwbeta** [comment]
可以了！那估计真是这个问题，我看起来js文件还是js格式，很奇怪：
![QQ截图20220321224847](https://user-images.githubusercontent.com/8300417/159286850-89676c63-82de-4987-a8f9-e9e83063fd7d.png)

**Comment by NateScarlet** [comment]
那你运行 `py -3.8 -c "import mimetypes; import http.server; print(mimetypes.types_map.get('.js'))"` 应该会返回 text/plain

python 会读注册表的这个 “Content Type” 设置

![图片](https://user-images.githubusercontent.com/21083014/159287615-a8e2f5d6-f336-4ed9-8435-4609e942285d.png)

**Comment by NateScarlet** [comment]
v1.17.1 修复了
