### ISSUE TITLE
巅峰杯商店问题

### ISSUE THREAD

**Issue by paranoia2333** [NateScarlet/auto-derby#268]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8338441/auto_derby.log)
![last_screenshot](https://user-images.githubusercontent.com/102275828/159842562-e683e0b4-bfbe-4bed-8985-becc38b4a2a2.png)
![last_screenshot](https://user-images.githubusercontent.com/102275828/159842607-a66abc12-6132-47b2-b8b2-4cc3ab8559cb.png)
![image](https://user-images.githubusercontent.com/102275828/159842850-f79328c0-688a-4cc8-94c1-3c7c089c94fe.png)
养其他育成时未发生问题可以正常运行，巅峰杯新剧本到了打完出道战第一次开商店后，会停在商店界面，程序似乎停止运行了，我手动买物品再开启脚本后会停在自己拥有的道具界面

**Comment by NateScarlet** [comment]
看你的 data/single_mode_item_labels.csv 是不是有逗号前长度不一样的行

尝试把当前的这个文件重命名为别的再试

**Comment by NateScarlet** [comment]
发现原因是你把 SINGLE_MODE_CHOICE_PATH 设为了物品标签文件的路径

**Comment by paranoia2333** [comment]
大佬我这个是昨天刚下载的，没有设置过物品标签文件，请问这个在哪里设置，是启动脚本时的ADB address吗

**Comment by NateScarlet** [comment]
![image](https://user-images.githubusercontent.com/21083014/159850303-be961807-ca3c-48d2-b968-c644d3a2c95b.png)

启动器有 Single mode choices 这个必然是你改了 默认值是 data/single_mode_choices.csv

**Comment by NateScarlet** [comment]
![image](https://user-images.githubusercontent.com/21083014/159850442-13378dbb-ebb5-4f98-be6f-e715e5264476.png)

启动器有 Single mode choices 这个必然是你改了 默认值是 data/single_mode_choices.csv

**Comment by paranoia2333** [comment]
![image](https://user-images.githubusercontent.com/102275828/159850904-e49039f8-cbb9-4aae-ab2b-0feda570334f.png)
![image](https://user-images.githubusercontent.com/102275828/159850996-2ead0daa-9f3b-46e5-8de4-08669fa0c06b.png)
![image](https://user-images.githubusercontent.com/102275828/159851404-70cac022-80fc-4660-8e2e-6973f12bf882.png)
按照您说的把路径改回去了还是会出现这个问题

**Comment by NateScarlet** [comment]
> 尝试把当前的这个文件重命名为别的再试

**Comment by paranoia2333** [comment]
谢谢您，已经可以正常使用了
