### ISSUE TITLE
巅峰杯禁止使用闹钟

### ISSUE THREAD

**Issue by debi-derby** [NateScarlet/auto-derby#269]
有没有参数可以控制巅峰杯自动使用闹钟的设定？
之前的剧本可以用 pause_before_race_continue 控制，现在该脚本无法触发了

**Comment by NateScarlet** [comment]
插件改 `auto_derby.config.single_mode_should_retry_race`
我之后把 pause_before_race_continue 更新下

**Comment by NateScarlet** [comment]
也不对 应该加个别的插件 巅峰杯这个直接不重试就行了 暂停反而不合适

**Comment by debi-derby** [comment]
> 也不对 应该加个别的插件 巅峰杯这个直接不重试就行了 暂停反而不合适

确实，如果不是这次开了任务，应该不会挂巅峰杯，一场耗时太久了。这种情况闹钟就完全不需要了
