### ISSUE TITLE
cv报错

### ISSUE THREAD

**Issue by JMFANS** [NateScarlet/auto-derby#270]
INFO  [17:40:15]:__main__:23: auto_derby: 1.17.6 (2022-03-24 23:13:55)
INFO  [17:40:16]:auto_derby.version:54: lastest: 1.15.4 from https://natescarlet.coding.net/p/github/d/auto-derby/git/raw/master/version
DEBUG [17:40:16]:auto_derby.plugin:43: loaded: afk, auto_crane, debug_item_effect, debug_window, example_custom_client, example_custom_context, example_custom_item_score, example_custom_race_score, example_custom_training_partner_score, example_custom_training_score, example_oguri_cap, example_power_level5, example_smart_falcon, example_tamamo_cross, hello_world, less_op, limited_sale_buy_everything, limited_sale_buy_first_3, limited_sale_ignore, limited_sale_close, more_g1, prefer_g1, no_event_prompt, no_item_prompt, no_ocr_prompt, pause_before_command, pause_before_race_continue, pause_on_last_turn, race_campaign, SSR樫本理子, SSR駿川たづな, umapyoi, use_legacy_screenshot
DEBUG [17:40:16]:auto_derby.clients.adb:74: screen size: width=1080 height=2340
DEBUG [17:40:20]:auto_derby.clients.adb:88: screenshot method performance: name=_screenshot_raw perf_counter_ns=3730406700
DEBUG [17:40:23]:auto_derby.clients.adb:88: screenshot method performance: name=_screenshot_png perf_counter_ns=2610210300
INFO  [17:40:23]:auto_derby.clients.adb:105: selected screenshot method: name=_screenshot_png perf_counter_ns=2610210300
DEBUG [17:40:26]:auto_derby.template:47: screenshot
DEBUG [17:40:26]:auto_derby.template:61: load: connecting.pos.png
DEBUG [17:40:26]:auto_derby.template:61: load: connecting.png
ERROR [17:40:26]:__main__:129: unexpected exception
Traceback (most recent call last):
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\__main__.py", line 125, in <module>
    main()
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\__main__.py", line 96, in main
    job()
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\jobs\nurturing.py", line 325, in nurturing
    tmpl, pos = action.wait_image(*spec.keys())
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\action.py", line 53, in wait_image
    return next(template.match(template.screenshot(max_age=0), *tmpl))
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\template.py", line 195, in match
    for j in _match_one(img, i):
  File "C:\Users\asus\Desktop\auto-derby-master\auto_derby\template.py", line 175, in _match_one
    _, max_val, _, max_loc = cv2.minMaxLoc(res, mask=mask)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\core\src\matrix_iterator.cpp:71: error: (-215:Assertion failed) A.size == arrays[i0]->size in function 'cv::NAryMatIterator::init'

**Comment by NateScarlet** [comment]
你是第一次运行还是更新版本后出这个问题？

**Comment by NateScarlet** [comment]
adb 屏幕分辨率必须是 9:16
