### ISSUE TITLE
夏日海邊橙色背景 OCR

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#271]
橙色的邊框又被當作文字了QQ
![6f627b35e1f88142b61f0f6929029569](https://user-images.githubusercontent.com/16464896/160134437-c32c3140-65bb-48de-aa63-bb5ef498cdfd.png)
![fff54482114bb78c5aac8e65c946a](https://user-images.githubusercontent.com/16464896/160133941-dc9dcced-8ba7-482f-86ee-41b4b78f8d87.png)

**Comment by NateScarlet** [comment]
不该给白边扩边的 e99cd208630191b1c0e959779092fac0df41cffb
