### ISSUE TITLE
最佳物品方案窮舉時間過長

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#272]
窮舉了5分鐘還沒算完，可能與 #264 有關？我檢查過識別的物品清單是對的。
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8352891/debug.zip)

**Comment by NateScarlet** [comment]
这个是算法限制 因为使用顺序也会影响评分 所以复杂度是随物品数量指数增长的 你有更好的方案吗?

**Comment by Small-Ku** [comment]
我不熟算法複雜度之類的問題，可能需要一點時間來搞懂這個是怎麼運作的
可是同一個組合，同一個分數出現48次是正常的嗎？
(分數輸出應該是這行吧？)

| COUNT    | LINE |
|---------|-------------------------------------------|
|      48 | item.plan:28: score: 11.22: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      45 | item.plan:28: score: 8.78: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り |
|      24 | item.plan:28: score: 29.91: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      23 | item.plan:28: score: 28.77: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      12 | item.plan:28: score: 11.53: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      12 | item.plan:28: score: 12.11: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      12 | item.plan:28: score: 12.54: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      12 | item.plan:28: score: 13.64: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|      11 | item.plan:28: score: 9.84: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り |
|       6 | item.plan:28: score: 29.54: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       6 | item.plan:28: score: 30.54: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       6 | item.plan:28: score: 30.76: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       6 | item.plan:28: score: 31.63: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       6 | item.plan:28: score: 34.08: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       6 | item.plan:28: score: 58.20: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       5 | item.plan:28: score: 59.05: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       4 | item.plan:28: score: 12.07: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       4 | item.plan:28: score: 13.71: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       4 | item.plan:28: score: 14.73: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       4 | item.plan:28: score: 16.80: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 17.99: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 31.15: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 32.40: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 34.92: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 37.13: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 58.44: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 58.86: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 59.88: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       2 | item.plan:28: score: 66.70: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 37.99: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 59.15: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 59.37: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 67.04: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 67.92: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|
|       1 | item.plan:28: score: 68.27: ブートキャンプメガホン,ロイヤルビタージュース,健康祈願のお守り|

**Comment by NateScarlet** [comment]
正常 要对每个命令都进行评分 你没看分会有不一样的

**Comment by NateScarlet** [comment]
你可以把debug关掉看卡不卡 或许是输出日志太多导致慢

这个日志输入的不止是最终物品使用计划的评分 还有中途子计划的评分

**Comment by Small-Ku** [comment]
那我下次遇到再試好了，畢竟現在遇不到這個問題了

**Comment by NateScarlet** [comment]
改了一下 只在找到更好方案时输出日志 [5ae2195](https://github.com/NateScarlet/auto-derby/commit/5ae21952fe2dd269c97ef8ec7a1d28481c839c30)

**Comment by NateScarlet** [comment]
应该就是日志导致的 我现在15个物品计算方案只要一两秒

**Comment by NateScarlet** [comment]
然后18个物品要1分多

**Comment by NateScarlet** [comment]
算了 用随机选  然后加个最大计算时间 就算不是最佳也无所谓了

**Comment by NateScarlet** [comment]
发现因为高等级物品的ID都比较高 先直接按ID倒序排序再穷举 可以在有高级物品的时候跳过低等级物品的枚举

**Comment by NateScarlet** [comment]
发现确实有重复计算同样的方案 6f4ecd89080c642f211be91d1de0fd8e2d4eb5e9

**Comment by NateScarlet** [comment]
想半天发现其实可以不考虑顺序 失败率高的时候最后最佳方案肯定是先用体力或者护符 如果体力道具期望分达不到效果分 那buff也应该达不到效果分或者根本不需要降失败率

**Comment by NateScarlet** [comment]
不考虑顺序之后耗时变为了瞬间

**Comment by Small-Ku** [comment]
感謝 ⊂((・▽・))⊃
