### ISSUE TITLE
连续打比赛时会先取消连战提醒然后重新跑一遍项目检测

### ISSUE THREAD

**Issue by RecycleBee** [NateScarlet/auto-derby#274]
连战三回的提醒冒出来的时候会先找取消键，再跑一遍项目检测后才能正常连战。触发的频率不低，过程有点耗时间，有没有什么改进的方法？

![7X 1`B)GCQW `O8 YE LRU3](https://user-images.githubusercontent.com/83790689/160207331-31527b84-3f75-4899-acec-41b421c35da5.png)
第一次尝试连战

![~(W(1$Y)V8{ XFD4)XSG)~G](https://user-images.githubusercontent.com/83790689/160207611-8d6b1575-1586-4485-960d-5cee8339ca5c.png)
第二次尝试连战，接下来就是正常比赛了。

**Comment by NateScarlet** [comment]
方法就是不要育成中途中断脚本
