### ISSUE TITLE
训练过程中卡死，一直循环

### ISSUE THREAD

**Issue by isisake-19** [NateScarlet/auto-derby#275]
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.97
DEBUG [19:27:22]:auto_derby.template:47: screenshot
DEBUG [19:27:22]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_command_training.png>, similarity=1.000
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.97
DEBUG [19:27:22]:auto_derby.template:47: screenshot
DEBUG [19:27:22]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_command_training.png>, similarity=1.000
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.97
INFO  [19:27:22]:auto_derby.scenes.scene:41: enter: unknown -> single-mode-command
DEBUG [19:27:22]:auto_derby.template:47: screenshot
DEBUG [19:27:22]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_command_training.png>, similarity=1.000
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.97
INFO  [19:27:22]:auto_derby.scenes.scene:43: entered: single-mode-command
INFO  [19:27:22]:auto_derby.window:83: width=540 height=960
INFO  [19:27:22]:auto_derby.window:85: already in wanted size
DEBUG [19:27:22]:auto_derby.window:112: set foreground window: h_wnd=6030862
INFO  [19:27:22]:auto_derby.clients.dmm:55: foregrounded game window: handle=6030862
DEBUG [19:27:22]:auto_derby.template:61: load: single_mode_climax_grade_point_icon.pos.png
DEBUG [19:27:22]:auto_derby.template:61: load: single_mode_climax_grade_point_icon.png
DEBUG [19:27:22]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_climax_grade_point_icon.png>, similarity=1.000
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_climax_grade_point_icon.png>, pos=(19, 161), similarity=1.00
DEBUG [19:27:22]:auto_derby.single_mode.context:209: _recognize_scenario: Make a new track!!  ～クライマックス開幕～
DEBUG [19:27:22]:auto_derby.template:61: load: single_mode_character_detail_button.pos.png
DEBUG [19:27:22]:auto_derby.template:61: load: single_mode_character_detail_button.png
DEBUG [19:27:22]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_character_detail_button.png>, similarity=1.000
INFO  [19:27:22]:auto_derby.template:183: match: tmpl=tmpl<single_mode_character_detail_button.png>, pos=(466, 559), similarity=0.95
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<85.9%,シ,1800fc00> by 3800fc00fc00f00040000f401ff03ff81cfc007e803fc01ff007fc03fc007c00
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<89.1%,ニ,fe3ffe3f> by fe3ffe3ffe3ffc1f00000000000000000000000000000000ff7fffffffffff7f
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<86.7%,ア,ffffffff> by ffffffffffff00f00070c078e03de03fe01ff00cf000f80078003c003c001c00
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<100.0%,y,807fc27f> by 807fc27f33371b631e630ee32ee33fc7ffe7fc6f8c7ffc79dc79cc7d8c6f0800
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<85.2%,1,003ec0ff> by 007e80ffe0fffcfffeff80ff00fe00fe00fe00fe00fe00fe00fe00fe00fe003c
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<92.2%,0,f007fc1f> by f00ffc1f7e3f1f7c0f780ff807f007f007f00ff00f780f781f7cfe3ff80fe003
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<84.4%,月,f87ffcff> by fc7ffcff9cf10ce0fcfffcfffcff0ce00ce0fcfffcff0ee007e0077002780000
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<98.4%,前,0018783c> by 0008783cfeff02ff00000040fee8feecfee8fee8cee8fee8fee0c6e0e6f0c470
DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<85.2%,半,80018c31> by 80018c719c71dc31c801c001fe7ffe7fdc3fc003fffffffffe7f800180018001
DEBUG [19:27:24]:auto_derby.template:47: screenshot
DEBUG [19:27:24]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_character_detail_button.png>, similarity=1.000
INFO  [19:27:24]:auto_derby.template:183: match: tmpl=tmpl<single_mode_character_detail_button.png>, pos=(466, 559), similarity=0.95

**Comment by NateScarlet** [comment]
> DEBUG [19:27:22]:auto_derby.ocr:127: query label: IHMQueryResult<100.0%,y,807fc27f> by 807fc27f33371b631e630ee32ee33fc7ffe7fc6f8c7ffc79dc79cc7d8c6f0800

你OCR字符标错了 在data/ocr_labels.csv中找到 807fc27f 开头的那行删掉
