### ISSUE TITLE
育成卡在賽事結束後

### ISSUE THREAD

**Issue by newyen2** [NateScarlet/auto-derby#279]
卡在結算巔峰杯pt的介面，有看到鼠標移動到按鈕這個操作，但遊戲並沒有回應，感覺是等待時間過短的問題
![2](https://user-images.githubusercontent.com/29043416/160563848-79a1d9fd-af7a-4ff9-9ce6-3d65a4ed78a3.PNG)
![1](https://user-images.githubusercontent.com/29043416/160563854-79c7820d-eb6a-4cc0-9194-a9f8ff7c928c.PNG)

**Comment by SRoStar** [comment]
我也经常出现这个问题，设置的无人值守。有时间频率很高（一次育成出现五六次），有时候一次也没有

**Comment by YiBo-Z** [comment]
我也遇到过这样的问题 但是开启debug之后就再也没遇到过了 不知道是不是变慢了一点的影响

**Comment by newyen2** [comment]
我等下測兩次 一次不開debug 另一次開debug 然後有遇到問題我就貼上來

**Comment by SRoStar** [comment]
> 我也遇到过这样的问题 但是开启debug之后就再也没遇到过了 不知道是不是变慢了一点的影响 我之前把鼠标拔下来也是有这样的情况出现的 但是我已经开启debug2天了 开启后就再也没出现

确实这样，我开debug后就也没在出现这个问题了。bug藏起来不让改了属于是

**Comment by NateScarlet** [comment]
启动器的 debug 会保存最后的截屏 所以会慢一点

单独开日志的DEBUG 不启用其他DEBUG数据可以用这个插件


```python
import auto_derby


import logging


class Plugin(auto_derby.Plugin):
    def install(self) -> None:
        logging.getLogger("auto_derby").setLevel(logging.DEBUG)


auto_derby.plugin.register(__name__, Plugin())
```

**Comment by newyen2** [comment]
我現在正在測，前段時間在忙其他作業，雖然我現在裝上面那個plugin後測到現在還沒遇到這個問題，但我想重現一下卡住的情況，因為就我發issue之前卡住的頻率不算低

**Comment by newyen2** [comment]
目前就是守在電腦前面 然後注意不動滑鼠 也盡量不中斷程序

**Comment by newyen2** [comment]
我昨天總共測了4把沒有遇到同樣情況，如果我之後有再遇到相關情況再貼上來

**Comment by NateScarlet** [comment]
我遇到了 给 wait_tap_image 加了 0.01 秒 感觉就不会出现了

**Comment by NateScarlet** [comment]
还是会出现 得单独针对这个场景加大
