### ISSUE TITLE
无法自动购买商店出售物品

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#28]
会卡在购买后关闭的页面
![image](https://user-images.githubusercontent.com/37131177/120924970-efb1ba00-c708-11eb-98d3-3166a760e33c.png)
可以看到鼠标点击的反馈，但是并没有关掉这个页面。

**Comment by NateScarlet** [comment]
日志发一下 这是你游戏卡了吧

**Comment by fatinghenji** [comment]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6604218/launcher.log)
这个是log，另外竞技场如果出现平局也需要手动点击。

**Comment by NateScarlet** [comment]
竞技场竟然还有平局的 我从来都没遇到过 你有图吗

**Comment by fatinghenji** [comment]
我再去开一轮。是一个灰色的drawn。

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/120925227-37851100-c70a-11eb-90c2-a281e7abf7ba.png)
这个样子。

**Comment by NateScarlet** [comment]
这个日志是正常以RP不足结束并且里面没有匹配过限定商店

是不是你遇到后又开了导致日志被覆盖了 最近3次的运行日志有备份可以看下

**Comment by fatinghenji** [comment]
大佬打了个包，没删敏感信息，关issue之前我把这层删了
[auto-derby.zip](https://github.com/NateScarlet/auto-derby/files/6604228/auto-derby.zip)

**Comment by NateScarlet** [comment]
在 log.1 里面有 我看下

**Comment by NateScarlet** [comment]
我估计是点交换之后网络连接时间比通常长导致点击没作用
我加个等待

**Comment by NateScarlet** [comment]
不对啊 只有连接成功后才能看到这个关闭按钮

**Comment by NateScarlet** [comment]
是不是你和脚本同时操作导致判定没点到

我改成不停点直到消失为止

**Comment by fatinghenji** [comment]
> 是不是你和脚本同时操作导致判定没点到
> 
> 我改成不停点直到消失为止

没有做任何操作ummmmm，改成一直点应该会解决这个问题
