### ISSUE TITLE
OCR識別問題

### ISSUE THREAD

**Issue by AkkaA0305** [NateScarlet/auto-derby#285]
What is OCR looking at...

Probably the upper right of "半"

![nox](https://user-images.githubusercontent.com/103111138/161963924-427c6b83-0421-4ab2-9dbf-556f6f451c0e.png)
![oce_error](https://user-images.githubusercontent.com/103111138/161963918-188bf9f1-3154-4ce0-933a-d70067b4348a.png)
[auto-derby.zip](https://github.com/NateScarlet/auto-derby/files/8426369/auto-derby.zip)

**Comment by NateScarlet** [comment]
模拟器需要用1080x1920分辨率

**Comment by AkkaA0305** [comment]
I'm sorry. I fixed it to 1080 x 1920. But another error occurre. And do you have a recommended DPI?
[debug.1.zip](https://github.com/NateScarlet/auto-derby/files/8441085/debug.1.zip)
![erroe](https://user-images.githubusercontent.com/103111138/162157778-ff59c6ef-b96a-4241-b249-993565a86f87.png)
