### ISSUE TITLE
竞技场如果出现平局需要手动点击

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#29]
![image](https://user-images.githubusercontent.com/37131177/120925227-37851100-c70a-11eb-90c2-a281e7abf7ba.png)
这个样子。

_Originally posted by @fatinghenji in https://github.com/NateScarlet/auto-derby/issues/28#issuecomment-855395611_

**Comment by NateScarlet** [comment]
@fatinghenji 我加上了 虽然没测试但是应该没问题

**Comment by fatinghenji** [comment]
问题解决了
