### ISSUE TITLE
Failure to swipe operation.

### ISSUE THREAD

**Issue by AkkaA0305** [NateScarlet/auto-derby#293]
Perhaps you are looking for "新潟記念" under "セントウルステークス", but the swipe process is not working properly and an error is occurring
[issue.zip](https://github.com/NateScarlet/auto-derby/files/8488178/issue.zip)
.

**Comment by NateScarlet** [comment]
maybe same as #71

can you test with a larger [min swipe duration](https://github.com/NateScarlet/auto-derby/blob/8060c172411afc3bf283a093733869f6a48ba0f3/auto_derby/clients/adb.py#L152)?

**Comment by AkkaA0305** [comment]
The game has been updated and the store UI has changed and "auto-derby" no longer works, so I will try it after the new UI is supported.

**Comment by NateScarlet** [comment]
only climax scenario is affected, ura/climax scenario still work

**Comment by AkkaA0305** [comment]
I set it to 350 and it worked. Thank you

**Comment by AkkaA0305** [comment]
I tried several times and 350 didn't work. I am now trying to raise it by 50.

**Comment by AkkaA0305** [comment]
I was able to swipe at 350 after several verifications. 
But there was another problem. 
I cannot get to the "カトレア賞" because it goes up before going to the bottom of the race list.


https://user-images.githubusercontent.com/103111138/163680177-b8877472-5d29-42c1-815b-398c0ed75195.mp4



[issue2.zip](https://github.com/NateScarlet/auto-derby/files/8500136/issue2.zip)

**Comment by NateScarlet** [comment]
try [61affc1](https://github.com/NateScarlet/auto-derby/commit/61affc181dd8a20960a74a585561ee420398a013)

**Comment by AkkaA0305** [comment]
修正されたadb.pyを試しました。
スワイプはできるようになりました。
しかしながら、上の動画と同じくレースリストの一番下にいくまえに上に戻るため「ラジオ日本賞」を見つけるのに失敗します。

↓deepl　translation

I tried the modified adb.py.
Swiping is now possible.
However, as in the video above, it fails to find "ラジオ日本賞" because it goes back to the top before going to the bottom of the race list.

![image](https://user-images.githubusercontent.com/103111138/163698109-79188699-25e2-4e00-9db1-fa108aef977f.png)
[issue3.zip](https://github.com/NateScarlet/auto-derby/files/8500909/issue3.zip)

**Comment by NateScarlet** [comment]
it wiil goes to bottom again with a larger scroll distance (this action may repeat up to 3 times)
maybe enable race sugguestion can save some time for you
