### ISSUE TITLE
champions meeting 选马娘地方停住了

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#296]
程序没有停，一直还在识别，下图是停住的地方

![大赛无全自动](https://user-images.githubusercontent.com/102540842/164605503-30022922-9d2f-444e-9f90-eb1816ba0b0b.png)

**Comment by NateScarlet** [comment]
设计上所有可能花萝卜石的功能都要人工确认

Duplicate of #163

**Comment by NateScarlet** [comment]
更新了 [FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E8%84%9A%E6%9C%AC%E5%90%AF%E5%8A%A8%E6%B2%A1%E6%95%88%E6%9E%9C)
