### ISSUE TITLE
巅峰杯更改购买机制，原程序无法继续识别并运行

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#297]
程序还在没有停止，还在继续识别。版本是auto-derby-1.21.2。以下是停住的地方。

![shop1](https://user-images.githubusercontent.com/102540842/164605862-14bfffce-23f6-46d2-b6c1-9b8cfae3622b.png)

![shop2](https://user-images.githubusercontent.com/102540842/164605873-a2ff0e8c-a408-4f7f-b606-d2ef6b417a1b.png)

![shop3](https://user-images.githubusercontent.com/102540842/164605879-7844c455-575b-4abd-81fd-9cf5a17b7ef2.png)

**Comment by NateScarlet** [comment]
Duplicate of #291 

Small-Ku 有做新的适配 但是没写测试
