### ISSUE TITLE
auto_crane脚本抓取不准确

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#298]
参数没改动过，以前版本在同一台机子也有同样的问题，我统计过命中率只有10%左右。版本是auto-derby-1.21.2。下面是视频，原视频太大故没有上传。

https://user-images.githubusercontent.com/102540842/164606893-dcf5a56c-b369-4676-bbf6-b5017e967b3c.mp4

**Comment by NateScarlet** [comment]
你指望随机位置用固定参数能有多高准确度？ 而且这玩意调了参数也很难测 如果在乎这个就别用自动抓

**Comment by mtt-konan** [comment]
刚刚看了auto_crane的描述，也确实没问题。不过还是谢谢开发者了

https://github.com/NateScarlet/auto-derby/wiki/Plugins#auto_crane
