### ISSUE TITLE
champions meeting 晋级的时候停住了

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#301]
程序没有停，一直还在识别，版本auto-derby-1.21.2，下图是停住的地方

![大赛](https://user-images.githubusercontent.com/102540842/164986334-82627b31-e34b-462b-8461-504b29aa7bf1.png)

**Comment by NateScarlet** [comment]
你一个月会晋级几次? 这也要自动吗

**Comment by haotingliulime** [comment]
哈哈哈哈哈哈
