### ISSUE TITLE
黄色主题色的角色训练识别出错

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#303]
北黑巅峰杯育成，合宿遇到 #294 相同的问题，版本是auto-derby-1.22.0，不是同一时间调试但是报错内容是相同的。

![last_screenshot](https://user-images.githubusercontent.com/102540842/165583198-5c640ac9-7aba-42fe-a71e-31c79d67ef84.png)

[problem.txt](https://github.com/NateScarlet/auto-derby/files/8575024/problem.txt)

[debug.zip](https://github.com/NateScarlet/auto-derby/files/8575030/debug.zip)

**Comment by NateScarlet** [comment]
不是同一张图就不是同一个问题 之前给的图测试已经过了

**Comment by NateScarlet** [comment]
这个应该和 #244 是同一类型

聊天室有人说了 https://gitter.im/auto-derby/community?at=6269334261f5ca3feed545f5

你把 #294 的修复去掉反而应该不会出现这个问题

**Comment by gentle-knight-13** [comment]
I have reverted ed2bfe8 and nurtured it about 5 times, but the problem did not reproduce.
