### ISSUE TITLE
启动后无反应

### ISSUE THREAD

**Issue by kitanai-kitsune** [NateScarlet/auto-derby#305]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8660162/auto_derby.log)

[launcher.log](https://github.com/NateScarlet/auto-derby/files/8660171/launcher.log)
启动后无反应 直接退出

**Comment by Small-Ku** [comment]
Python 和依賴版本不對

**Comment by kitanai-kitsune** [comment]
> Python 版本不對
> 
> `需求 DMM 版 和 python3.8`

谢谢 换成3.8后ok了

**Comment by NateScarlet** [comment]
这个具体问题的原因其实不是 python 版本

而是你用的不是我指定的 opencv 版本 [有bug](https://github.com/opencv/opencv_contrib/issues/3171)

**Comment by kitanai-kitsune** [comment]
> 这个具体问题的原因其实不是 python 版本
> 
> 
> 
> 而是你用的不是我指定的 opencv 版本 [opencv 4.5.5 有bug](https://github.com/opencv/opencv_contrib/issues/3171)

嗯 我把python的依赖全部重装了一遍就OK了
