### ISSUE TITLE
adb不能识别1080*1920的画面

### ISSUE THREAD

**Issue by mtt-konan** [NateScarlet/auto-derby#306]
用红米k40运行赛马娘，分辨率为1080\*2340的，不能cv识别，遇到了#270的问题。后面我用adb命令修改分辨率至1080\*1920，这会cv不会报错了，但是还是识别不到，是因为底下的黑边影响了吗

![adb-q](https://user-images.githubusercontent.com/102540842/167815733-fa71654c-a1fa-4e1b-9390-6a8aea2c02fc.jpeg)

**Comment by NateScarlet** [comment]
底下的黑边不影响 顶上的会影响 因为坐标原点是左上角

如果没命令改缩放原点的话就只能用自定义客户端来转换当前坐标到1080x1920
