### ISSUE TITLE
巅峰杯育成没有选择商品，并且不会外出

### ISSUE THREAD

**Issue by qqqspppl** [NateScarlet/auto-derby#307]
巅峰杯点开商店后不购买直接退出
请问是需要调整什么吗

**Comment by Small-Ku** [comment]
請根據[问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)上載相關資訊。

**Comment by qqqspppl** [comment]
> 請根據[问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)上載相關資訊。

本质来讲是我想知道商店界面会弹出一个网页，在网页中有商品的总表，但点确定没有反应，这个是操作问题还是没有正确运行

**Comment by NateScarlet** [comment]
网页上写了要你干啥 看不懂用机翻或者不要用这个项目

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
