### ISSUE TITLE
大佬能帮我看看我遇到什么问题了吗，纯新人

### ISSUE THREAD

**Issue by 956262934** [NateScarlet/auto-derby#308]
![QQ图片20220516200909](https://user-images.githubusercontent.com/105646174/168589555-ac48bcf0-ffbf-4895-807c-fe9cb74b8915.png)
![QQ图片20220516200917](https://user-images.githubusercontent.com/105646174/168589578-ebb5da60-b3dd-4353-aa54-c56631d480ae.png)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/8699874/launcher.log)

**Comment by 956262934** [comment]
大佬有空的话能帮忙看一下吗，谢谢你啦

**Comment by NateScarlet** [comment]
看 [FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ)

你这日志又没报错 要看啥
