### ISSUE TITLE
在巅峰赛用afk插件自动育成过程中会不停出现低识别率警告，整体进度停止

### ISSUE THREAD

**Issue by shinkai0509** [NateScarlet/auto-derby#310]
![循环出现](https://user-images.githubusercontent.com/106856248/171982130-6bbfe031-23a1-40b8-82ce-0b1d6d9eb205.png)
![卡在的页面](https://user-images.githubusercontent.com/106856248/171982427-6c0175e7-0c8c-447a-ba68-4e0b5b2c96eb.png)
使用了AFK插件后会出现的现象，有时候能自己跳出但很快又会回到这个界面上再次循环。试过取消AFK插件进行了手动的识别，但依然出现了相同的结果。另外曾经出现过把根性请愿书识别成智力请愿书导致无法勾选对应道具整体卡死的情况。这个请问有没有什么解决方法呢？谢谢。

**Comment by Matayoru233** [comment]
遇到这个情况+1

**Comment by NateScarlet** [comment]
afk是标注差不多了才能开的 wiki上面都写了

**Comment by NateScarlet** [comment]
要不然就是你手动标注了错误的结果
