### ISSUE TITLE
6月6日UI更新导致无法识别比赛

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#313]
https://dmg.umamusume.jp/news/detail?id=804

### Discussed in https://github.com/NateScarlet/auto-derby/discussions/312

<div type='discussions-op-text'>

<sup>Originally posted by **mtt-konan** June  6, 2022</sup>
是分辨率不够吗，画面设置成标准化也是这样，版本auto-derby-1.25.1

![p1](https://user-images.githubusercontent.com/102540842/172138942-0266422c-f3b1-42d6-8d11-502bb9f19847.jpg)

![p2](https://user-images.githubusercontent.com/102540842/172138946-301d72c0-67a1-4bae-a637-d7d9a35e3396.jpg)

</div>

**Comment by mtt-konan** [comment]
我重装了游戏，用的游戏默认设置，可能是我的问题。。我看看游戏设置能不能调整场地

**Comment by mtt-konan** [comment]
比赛上面只有场馆是因为这个项目：
[https://github.com/GEEKiDoS/umamusume-localify](url)

此问题已解决，不好意思没弄清楚就来提问了

**Comment by NateScarlet** [comment]
[更新了FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ/_compare/49ea9065868b50b038ef8e9bc2ced0bf8ba12636...32dba841114148dc3d0cc7a81b129eff6126a40c)
