### ISSUE TITLE
第二次提问物品时卡住

### ISSUE THREAD

**Issue by Rui-0v0** [NateScarlet/auto-derby#315]
#283
版本auto-derby-1.25.1
第一次网页选对应的物品后，网页正常关闭，程序正常运行，第二次网页选对应的物品后，网页显示done   this page can be closed.需要手动关闭，程序停止在这个界面
![9X92B45Q@OKG2~@@2`1)ZNM](https://user-images.githubusercontent.com/107097065/172540081-27b553d0-ca18-4fd5-9f36-0099150e21f1.png)

_Originally posted by @Rui-0v0 in https://github.com/NateScarlet/auto-derby/discussions/314_

**Comment by NateScarlet** [comment]
开调试发日志 看README 

我看不出这个和283有什么关系

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by Rui-0v0** [comment]
第二次提问后网页跳转显示：![8{JGQCLGU~Q38{ X5H190CW](https://user-images.githubusercontent.com/107097065/172544626-161239e5-18ed-45ec-ad34-c54d2c6662dc.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8858745/auto_derby.log)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/8858746/launcher.log)
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8858760/debug.zip)

**Comment by NateScarlet** [comment]
我复现了 似乎是第一次的服务器没成功关闭导致的

**Comment by NateScarlet** [comment]
调用 ThreadingHTTPServer 的 shutdown 没效果

似乎是 [python 的 bug](https://github.com/python/cpython/issues/84485)

0ae0692 修了
