### ISSUE TITLE
识别不到被禁用的物品

### ISSUE THREAD

**Issue by cwbeta** [NateScarlet/auto-derby#316]
使用的是安卓模拟器，巅峰杯长期出现此情况，虽然不会报错，但是会在这个状态持续卡上数分钟，最后触发故障判断返回到上一页重新开始逻辑，一般返回后可以正常继续执行。但若一次育成触发多次，时常导致额外消耗数个小时才能完成一次育成。

出错表现GIF动图：
![赛马娘一直点击边缘](https://user-images.githubusercontent.com/8300417/172796382-6dc01ec4-b530-4db3-878f-8db13db8bbc6.gif)

DEBUG日志打包rar：
传输链接：https://cowtransfer.com/s/2aa80e7f70d247 或 打开【奶牛快传】cowtransfer.com 使用传输口令：57wv0r 提取；

**Comment by NateScarlet** [comment]
应该是物品标错了 尝试不要开afk复现

**Comment by cwbeta** [comment]
好的，我后面试试不开启，谢谢。

**Comment by NateScarlet** [comment]
这个的原因是应该是你有两个 アロマディフューザー 
但是跳过跳过无法使用的物品的时候只跳过第一个
然后一直在找第二个

**Comment by NateScarlet** [comment]
也不对  你的日志里面就只识别到一次 アロマディフューザー

**Comment by cwbeta** [comment]
好的，辛苦了！这效率也是绝了！
