### ISSUE TITLE
启用fast_fail插件后，青春杯一直休息

### ISSUE THREAD

**Issue by jiuyi1214** [NateScarlet/auto-derby#318]
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8935693/auto_derby.log)
去掉后正常

**Comment by NateScarlet** [comment]
fast_fail 的作用就是一直休息啊 fast (快速) fail (失败)

https://github.com/NateScarlet/auto-derby/wiki/Plugins#fast_fail
