### ISSUE TITLE
剧本3消耗大量时间在翻商店，翻背包上是正常现象吗？

### ISSUE THREAD

**Issue by MIBXR** [NateScarlet/auto-derby#321]
脚本在翻阅商店以及背包的过程中，翻到底了还是会不停地继续重复下拉鼠标的动作，然后又开始上拉鼠标，直到顶端依旧重复操作。虽然在不知重复多少次后确实会关闭商店或背包，但耗费的时间非常长，一回合如果触发了逛商店或翻背包的动作，就会导致本回合耗时3-5分钟，极大地拉长了育成时间，一把要2小时。

如果是脚本逻辑所致，还是希望可以更快一些。

我就单上传一个log文件吧
[log.zip](https://github.com/NateScarlet/auto-derby/files/9029497/log.zip)

**Comment by NateScarlet** [comment]
别开afk 确定没标记错

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by MIBXR** [comment]
首先抱歉，刚刚提issue的时候鼠标点快了，没详细描述问题，也没传日志（；´д｀）ゞ，已补上。

为方便我确实开afk了，毕竟初衷就是自动养马

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/176949156-7d207e8d-bb2f-4731-b47f-c99a1e7502e8.png)
整页的 warning 你自己看不到的吗

afk 是在人工标注数据完整度很高的时候用的

wiki 上已经写了可能会导致出错
