### ISSUE TITLE
在创建环境的时候下载东西的时候报错

### ISSUE THREAD

**Issue by Minill1** [NateScarlet/auto-derby#338]
如
<img width="1046" alt="报错1" src="https://user-images.githubusercontent.com/109641025/180998241-16dd4fbc-0dd4-4236-afe6-c2b489bb750f.png">
<img width="1153" alt="报错2" src="https://user-images.githubusercontent.com/109641025/180998257-c2d5bdb1-ab3c-47c4-b7ec-a9e97250ee92.png">
图

**Comment by Minill1** [comment]
求助

**Comment by Minill1** [comment]
了解，再问一下
<img width="916" alt="报错3" src="https://user-images.githubusercontent.com/109641025/181005837-1cb93b65-e27d-4761-8702-2a4546e510b0.png">
。这个是要我打Y吗

**Comment by NateScarlet** [comment]
[FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ)

**Comment by Minill1** [comment]
额，我不小心吧巅峰赛物品名称与图片匹配错了。怎么重置啊？

**Comment by NateScarlet** [comment]
删除 data/single_mode_item_labels.csv 中对应行 或者整个删了

**Comment by Minill1** [comment]
ok，感谢

**Comment by Minill1** [comment]
我预约的比赛它好像不会自动跑啊，就停在那边。而且出门不去友人卡那边

**Comment by Minill1** [comment]
这怎么办啊？

**Comment by NateScarlet** [comment]
推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by Minill1** [comment]
<img width="1274" alt="报错5" src="https://user-images.githubusercontent.com/109641025/181011540-3e88f3aa-e334-445f-a4bf-823aed81a7c2.png">
我也不知道怎么讲，就是卡在这里

**Comment by NateScarlet** [comment]
你选中终端字符的时候程序会暂停 因为你把输出给堵住了

**Comment by Minill1** [comment]
我是为了截图才停住的，不停住就是一直跳

**Comment by NateScarlet** [comment]
脚本不支持游戏内预约 做脚本的时候根本没这功能 后面做了赛程插件也用不上预约 看FAQ

**Comment by Minill1** [comment]
我是SB，那没事了。

**Comment by Minill1** [comment]
那怎么让脚本出门的时候去友人卡那边呢，它都直接选择和马娘出门

**Comment by NateScarlet** [comment]
插件改外出评分 需要会python

**Comment by Minill1** [comment]
额，那不太会。指令都记不住。
