### ISSUE TITLE
开启显卡锐化后识别物品出错

### ISSUE THREAD

**Issue by Minill1** [NateScarlet/auto-derby#339]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/9194865/launcher.log)

**Comment by NateScarlet** [comment]
你又不是不能启动 为什么光发启动器日志

[问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)

**Comment by Minill1** [comment]
<img width="722" alt="报错6" src="https://user-images.githubusercontent.com/109641025/181156437-680f4f9f-8172-4cf9-a5be-f26bbcc11825.png">

**Comment by NateScarlet** [comment]
这个应该是你标错数字识别 文字识别问你Y/N的时候如果识别不对要选N然后手动输入正确的字 商店页面不可能有`级`字

**Comment by Minill1** [comment]
谢谢，我去试试

**Comment by Minill1** [comment]
就是到金蹄铁那边就会让我识别是否正确，但是我输N再打極依旧会报错。

**Comment by Minill1** [comment]
<img width="721" alt="报错7" src="https://user-images.githubusercontent.com/109641025/181158311-11c7df72-efd8-4ae2-ba49-1a16df5ef9a3.png">

**Comment by Minill1** [comment]
<img width="821" alt="报错8" src="https://user-images.githubusercontent.com/109641025/181160410-c79defe6-12ab-4565-bc54-ae14701709f1.png">

**Comment by Minill1** [comment]
这怎么弄，是要打value=40吗？

**Comment by NateScarlet** [comment]
这是把两个字识别成一个字了 发 debug/last_screenshot.png

**Comment by NateScarlet** [comment]
不要用截图发日志， 日志在 auto_derby.log

**Comment by Minill1** [comment]
![last_screenshot](https://user-images.githubusercontent.com/109641025/181164291-b3e6d5d6-8de3-41b2-8f76-dd599c15a5f4.png)

**Comment by NateScarlet** [comment]
你开显卡锐化了？

**Comment by Minill1** [comment]
应该没开，就是解锁了144帧

**Comment by Minill1** [comment]
我去试试

**Comment by Minill1** [comment]
我关了显卡锐化之后还是一样的

**Comment by NateScarlet** [comment]
重新发 last_screenshot.png

**Comment by Minill1** [comment]
![last_screenshot](https://user-images.githubusercontent.com/109641025/181167558-57a8e0b7-08a6-4631-b9c3-78a5d988809b.png)

**Comment by NateScarlet** [comment]
还是有锐化 改了显卡设置要重开吧

**Comment by NateScarlet** [comment]
你看[测试截图](https://github.com/NateScarlet/auto-derby/blob/514d594abf1bcd2a85bb37da19b2834b65cc6596/auto_derby/test_data/single_mode/shop_scene_1.png)的文字边缘

**Comment by Minill1** [comment]
解决了
