### ISSUE TITLE
日常赛支持选择难度

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#34]
以我现在的练度，跑每日只能拿满normal难度，脚本自动跑hard会亏物品。
希望可以自主选择跑的难度或者根据每次不同的天气调整上场的马和跑法。

**Comment by NateScarlet** [comment]
我之后两个日常赛各加一个低一级的工作选项

https://github.com/NateScarlet/auto-derby/blob/master/auto_derby/templates/daily_race_hard.png

现在你把这个图用你想要的难度的图代替应该就行了

其实我推荐前期不要用脚本手打来体验游戏的设计 后面重复多了再用脚本
