### ISSUE TITLE
脚本启动之后出错

### ISSUE THREAD

**Issue by aishangbiao** [NateScarlet/auto-derby#341]
我是从launch.cmd启动的，这是点了powershell的输出文本
已启动脚本，输出文件为 D:\Program Files\auto-derby-1.27.1\launcher.log

Job                       : nurturing
Debug                     : True
CheckUpdate               : True
PythonExecutablePath      : D:\Program Files\Python\Python38\python.exe
SingleModeChoicesDataPath : D:\Program Files\auto-derby-1.27.1\data\single_mode
                            _choices.csv
PauseIfRaceOrderGt        : 4
Plugins                   : auto_crane,Medium_and_long_panhandle_races
TargetTrainingLevels      : 2,2,2,2,
ADBAddress                :
Version                   : 1.27.1
Python Version            : Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 1
                            1:48:03) [MSC v.1928 64 bit (AMD64)]

command:
title auto-derby: 1.27.1
cd /d "D:\Program Files\auto-derby-1.27.1"
set "DEBUG=auto_derby"
set "AUTO_DERBY_ADB_ADDRESS="
set "AUTO_DERBY_CHECK_UPDATE=true"
set "AUTO_DERBY_LAST_SCREENSHOT_SAVE_PATH=debug/last_screenshot.png"
set "AUTO_DERBY_OCR_IMAGE_PATH=debug/ocr_images"
set "AUTO_DERBY_PAUSE_IF_RACE_ORDER_GT=4"
set "AUTO_DERBY_PLUGINS=auto_crane,Medium_and_long_panhandle_races"
set "AUTO_DERBY_SINGLE_MODE_CHOICE_PATH=D:\Program Files\auto-derby-1.27.1\data
\single_mode_choices.csv"
set "AUTO_DERBY_SINGLE_MODE_EVENT_IMAGE_PATH=debug/single_mode_event_images"
set "AUTO_DERBY_SINGLE_MODE_TARGET_TRAINING_LEVELS=2,2,2,2,"
set "AUTO_DERBY_SINGLE_MODE_TRAINING_IMAGE_PATH=debug/single_mode_training_imag
es"
set "AUTO_DERBY_WEB_LOG_BUFFER_PATH=debug/log.jsonl"
set "AUTO_DERBY_WEB_LOG_IMAGE_PATH=debug/images"
"D:\Program Files\Python\Python38\python.exe" -m auto_derby nurturing
start "auto-derby launcher" cmd.exe /c .\launcher.cmd
exit
到这里之后就提示我说powershell已停止工作，自己关闭了
同时游戏的ui界面变成这样，不知道为什么变的非常大
![TC{PR39D_{2C50FYF7 GXRD](https://user-images.githubusercontent.com/110159972/182837194-3e0714e2-6d72-40bc-b3dc-ecc90afed76d.png)
然后这是debug文件里面log.jsonl的信息
![%FJ)A55@_3C})Q0 CAZPOU7](https://user-images.githubusercontent.com/110159972/182838180-d8aa6e8a-6800-47ea-8ff2-832bba6c0e5c.png)

**Comment by NateScarlet** [comment]
日志不要以截图形式发

看 [问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88) 说明

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by NateScarlet** [comment]
你截图连这帖子页面都填不满 算哪门子的特别大

**Comment by aishangbiao** [comment]
> 日志不要以截图形式发
> 
> 看 [问题反馈](https://github.com/NateScarlet/auto-derby#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88) 说明
> 
> 推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

请问是需要把日志全部的内容都发上来吗，整个日志看起来不短而且后面一直在重复相似的语句

**Comment by NateScarlet** [comment]
GitHub 可以传文件的啊

**Comment by aishangbiao** [comment]
> 你截图连这帖子页面都填不满 算哪门子的特别大

主要是我电脑屏幕一共就只有这么高了，游戏下半截显示不出来，不知道这算不算问题，会不会对脚本运行有影响，每次都要手动调整真的很麻烦

**Comment by NateScarlet** [comment]
[FAQ#笔记本屏幕分辨率不够](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E7%AC%94%E8%AE%B0%E6%9C%AC%E5%B1%8F%E5%B9%95%E5%88%86%E8%BE%A8%E7%8E%87%E4%B8%8D%E5%A4%9F)

**Comment by aishangbiao** [comment]
> GitHub 可以传文件的啊
不好意思， 忘了这点了
[log.zip](https://github.com/NateScarlet/auto-derby/files/9260592/log.zip)

**Comment by NateScarlet** [comment]
你这日志啥都没有 没有你说的重复

估计是你游戏窗口超过屏幕范围点不了导致的 FAQ刚才发了

**Comment by aishangbiao** [comment]
> 你这日志啥都没有 没有你说的重复
> 
> 估计是你游戏窗口超过屏幕范围点不了导致的 FAQ刚才发了

请问调整分辨率之后整个屏幕都横过来了怎么办，字和图标之类的所有东西都是横的，无法使用

**Comment by NateScarlet** [comment]
你不是笔记本吗？ 把显示器横过来啊

**Comment by NateScarlet** [comment]
而且跑脚本的时候你要使用什么
