### ISSUE TITLE
脚本无法启动

### ISSUE THREAD

**Issue by aishangbiao** [NateScarlet/auto-derby#342]
我是1366*768的屏幕分辨率，运行脚本的时候屏幕是调整成竖屏状态，
而且已经把游戏界面调整到对应的工作界面了，但脚本还是在循环not match
这是脚本运行xin信息，debug日志文件和last_screenshot
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/9269478/auto_derby.log)
[log.zip](https://github.com/NateScarlet/auto-derby/files/9269479/log.zip)
![last_screenshot](https://user-images.githubusercontent.com/110159972/183097709-da88a0f1-fb90-4df5-aa08-51873d3f2a92.png)

**Comment by NateScarlet** [comment]
你开了显卡锐化 导致模版不能匹配

**Comment by aishangbiao** [comment]
> 你开了显卡锐化 导致模版不能匹配
> 
> 见 #339

不好意思昨天太晚了，我刚刚看了一下，因为我这个是一个很老的集显了，驱动里面是没有显卡锐化这个功能的，应该和那个没关系吧

**Comment by NateScarlet** [comment]
你可以和 auto_derby/test_data 里面的截图比一下

**Comment by aishangbiao** [comment]
> 你可以和 auto_derby/test_data 里面的截图比一下

我能关的设置都关了，还有哪里会对识别有影响吗
![6$}GH1(FV_L(@}D}$0G{M(U](https://user-images.githubusercontent.com/110159972/183228796-f14bb795-50b5-4918-a0ce-8bcc22213211.png)

**Comment by NateScarlet** [comment]
不知道

**Comment by aishangbiao** [comment]
> 不知道

好吧，那请问识图判定的阈值在哪里改啊，我想试试把相似度判定值改低点能不能行

**Comment by NateScarlet** [comment]
不行

**Comment by NateScarlet** [comment]
实在不知道哪里设置可以尝试把显卡控制面板卸了 用windows更新驱动

**Comment by NateScarlet** [comment]
而且你这个是独立显卡的配置 可能你游戏没在用独显

**Comment by aishangbiao** [comment]
> 而且你这个是独立显卡的配置 可能你游戏没在用独显
不是，我这个是集显来着

**Comment by aishangbiao** [comment]
> 实在不知道哪里设置可以尝试把显卡控制面板卸了 用windows更新驱动
哦好的，我试试看

**Comment by aishangbiao** [comment]
[debug.zip](https://github.com/NateScarlet/auto-derby/files/9391301/debug.zip)
重装显卡之后能正常运行脚本了，然后到7月前的时候，运行窗口那边突然问我y/n，我看网页日志这里是一个前字的图片，以为是问是否7月前，就输了y，然后脚本就没有再继续往下运行了，一直都是低相似度的判定

**Comment by NateScarlet** [comment]
点击角色详情没成功 重开脚本或手动点一下

一个 issue 只解决一个问题 有新问题开新 issue
