### ISSUE TITLE
OCR fails to read the number of fans.

### ISSUE THREAD

**Issue by waraiotoko2501h** [NateScarlet/auto-derby#35]
I would like to express my respect for your hard work.

Version: 2e4c9e75d63a460a85ad54eb342ca0b69d4dbffa

situation
![2021-06-08_01h05_03](https://user-images.githubusercontent.com/751160/121053719-9c1d9a00-c7f6-11eb-88ca-f9384762acea.png)

last_screenshot.local.png
![last_screenshot local](https://user-images.githubusercontent.com/751160/121053830-b788a500-c7f6-11eb-9b3a-fba3595f583f.png)

just in case
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6610521/launcher.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6610523/auto_derby.log)

-----------------------
On a personal note, the developers and I have slightly different environments, 
so I delete the default "ocr_labels.json" and recreate it.
If my "ocr_labels.json" is working fine, I will try to merge it with the default "ocr_labels.json" to see if there is any problem.

**Comment by waraiotoko2501h** [comment]
Oh! Sorry!
It may have been fixed while I was writing the issue.
I'll try 2e4c9e75d63a460a85ad54eb342ca0b69d4dbffa.

**Comment by waraiotoko2501h** [comment]
This problem was fixed in faf7872a822417b0b8cd397193ad926a166858d9. Close.

![2021-06-08_01h44_23](https://user-images.githubusercontent.com/751160/121058493-57e0c880-c7fb-11eb-9c30-37bd7618c52c.png)

**Comment by waraiotoko2501h** [comment]
This seems to be a problem in this situation.

Version d23666bb25ea8cba7c372c0281532628a531420f

![2021-06-08_02h21_25](https://user-images.githubusercontent.com/751160/121063543-6a5e0080-c801-11eb-86a3-b8217db456a2.png)

last_screenshot.local.png
![last_screenshot local](https://user-images.githubusercontent.com/751160/121063419-3be02580-c801-11eb-96d1-afe929b11ec5.png)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6610942/launcher.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6610943/auto_derby.log)

**Comment by NateScarlet** [comment]
What a coincident, i got a same error at the same time

![图片](https://user-images.githubusercontent.com/21083014/121064437-2e736d00-c7fa-11eb-8d0c-088aa31d6762.png)

**Comment by NateScarlet** [comment]
Fan count is preparing for auto choosing race which is not implemented yet.

You can just give wrong result `1` to it for now.
