### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by seawolfers** [NateScarlet/auto-derby#350]
第三年五月前脚本报错
![1@9XFK SPIJR645@VAFSU37](https://user-images.githubusercontent.com/71740968/185745634-ff3d9740-6da9-4f40-a83e-180f8978a22d.png)
[auto_derby.zip](https://github.com/NateScarlet/auto-derby/files/9387051/auto_derby.zip)
[log.zip](https://github.com/NateScarlet/auto-derby/files/9387052/log.zip)

**Comment by NateScarlet** [comment]
disable afk and label new race stadium yourself

**Comment by NateScarlet** [comment]
this is a logging error caused by other error (#351)
