### ISSUE TITLE
不能选择不同赛道参赛人数不一致的比赛

### ISSUE THREAD

**Issue by wwftherocksp** [NateScarlet/auto-derby#353]
![1e88fabc0782010b8a1b42bdcd806](https://user-images.githubusercontent.com/894504/186607280-26c9e3aa-78ee-4ec5-998e-e9ae8f6f55be.png)
[auto_derby.log.zip](https://github.com/NateScarlet/auto-derby/files/9422652/auto_derby.log.zip)

`ValueError: not found: Race<G1 JBCスプリント#0001-00fd>`

**Comment by NateScarlet** [comment]
你给的图和日志里记录的不一样 给手动截的图没有意义 debug 文件夹整个给我

```pwsh
PS D:\~\src\github.com\NateScarlet\auto-derby> py .\scripts\recognize_race_menu.py .\temp.local\186607280-26c9e3aa-78ee-4ec5-998e-e9ae8f6f55be.png -s climax
Course<川崎 dart 1400m 左> (203, 600)
Course<京都 turf 2200m 右·外> (203, 715)
```

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by wwftherocksp** [comment]
[debug.zip](https://github.com/NateScarlet/auto-derby/files/9427000/debug.zip)
[debug.z01.zip](https://github.com/NateScarlet/auto-derby/files/9427001/debug.z01.zip)
[debug.z02.zip](https://github.com/NateScarlet/auto-derby/files/9426982/debug.z02.zip)
[launcher.log.zip](https://github.com/NateScarlet/auto-derby/files/9427011/launcher.log.zip)
找不到比赛，遍历了n次debug将近50M只能分卷压缩
将debug.z01.zip改成debug.z01
debug.z02.zip改成debug.z02

**Comment by NateScarlet** [comment]
是这个比赛对不同马娘奖励不一致导致的 需要我改数据结构

**Comment by NateScarlet** [comment]
试试 4427d5c2b0312a3b91d7e4fb7ec360a6702bd2be

**Comment by NateScarlet** [comment]
试试 4bd9c115fb2c686e500c7533ca3bb281587fa1ea
