### ISSUE TITLE
new race_menu.py has issues

### ISSUE THREAD

**Issue by wsycarlos** [NateScarlet/auto-derby#356]
新的scenes/single_mode/race_menu.py好像有点问题
_race_by_course 我加了一行
if course not in i.courses:
            continue
但似乎好像ura预赛 准决赛和决赛的estimate_order 还是有误的感觉 还没细看打log 不知道是不是抓目标比赛依然还是抓错了

**Comment by NateScarlet** [comment]
什么叫 estimate_order 有误 本来 estimate_order 就只是预测
现在因为是单个比赛是多赛道所以随便选了一个赛道来预测

日志不给不考虑处理

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
