### ISSUE TITLE
OCR of 21 with ADB

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#358]
![last_screenshot](https://user-images.githubusercontent.com/16464896/187048230-b7a4b8cc-6a35-43bf-ae55-e9f23cd81dda.png)
![image](https://user-images.githubusercontent.com/16464896/187048236-545c34a9-a699-43c1-9705-276cc6258ed1.png)
The program recognize "21" as a single character recently with ADB.

**Comment by NateScarlet** [comment]
截图时包含的空白区域比较大导致的 识别前加了个自动裁剪
