### ISSUE TITLE
小栗帽巅峰杯出道战，软件报错退出

### ISSUE THREAD

**Issue by Promisphere** [NateScarlet/auto-derby#359]
如题
之前能正常使用v1.26.2版本，今天重新下载了v1.27.5版本，新开了一局一直养到出道战时报错了，重新运行仍然报错；尝试运行了v1.26.2版本能够正常运行
[v1.26.2.zip](https://github.com/NateScarlet/auto-derby/files/9439979/v1.26.2.zip)
[v1.27.5.zip](https://github.com/NateScarlet/auto-derby/files/9439980/v1.27.5.zip)

**Comment by Promisphere** [comment]
附件是两个版本的运行日志

**Comment by NateScarlet** [comment]
你是不是 [auto_derby/data/single_mode_races.jsonl](https://github.com/NateScarlet/auto-derby/blob/c18c8f37dfa315fe903c5efc362a4a5cfc3bcb4a/auto_derby/data/single_mode_races.jsonl) 没更新

v1.27.5 加了 id 字段的

**Comment by Promisphere** [comment]
极有可能，我安装时替换了老版本的data文件夹，我重新解压一份试试

**Comment by NateScarlet** [comment]
继承数据的data文件夹是根目录的 用户不应该动auto_derby/data

**Comment by Promisphere** [comment]
问题已经解决，就是auto_derby/data文件出错导致的
