### ISSUE TITLE
青春杯无法进入队伍对战

### ISSUE THREAD

**Issue by punkeek** [NateScarlet/auto-derby#364]
看起来tap command没有命中按钮捏。
以前1.21版本都没这问题，更新到1.27.5新版本好像不行了.

[debug.zip](https://github.com/NateScarlet/auto-derby/files/9469925/debug.zip)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/9469927/launcher.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/9469928/auto_derby.log)

> last_screenshot
![last_screenshot](https://user-images.githubusercontent.com/50232648/187918752-4580b031-a50c-4af9-bc17-855da02743cd.png)

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/188142703-1b753787-bc78-4799-9145-697be74ad93e.png)
点击坐标歪了 应该是1.26.3改随机位置点击导致的

**Comment by NateScarlet** [comment]
结果不是坐标数值问题 是 imagetools.rect_from_bbox 的转换方式错了 这个函数只在青春杯的场景用了所以没发现
