### ISSUE TITLE
偶像杯无法使用，感觉是无法睡觉与出行。

### ISSUE THREAD

**Issue by Minill1** [NateScarlet/auto-derby#366]

**Comment by Minill1** [comment]
INFOauto_derby.template:1972022/9/5 09:27:14.4771564
no match: tmpl=('single_mode_command_go_out.png',)
INFOauto_derby.template:1972022/9/5 09:27:15.0301566
no match: tmpl=('single_mode_go_out_menu_title.png',)

**Comment by Minill1** [comment]
![last_screenshot](https://user-images.githubusercontent.com/109641025/188343364-6aae7f53-41e4-4cfc-af05-c82ebe223a2d.png)

**Comment by Minill1** [comment]
无限循环什么都不干

**Comment by Minill1** [comment]
<img width="498" alt="报错1" src="https://user-images.githubusercontent.com/109641025/188344014-908dec23-d872-48b6-a48f-2f3e39649b6e.png">

**Comment by NateScarlet** [comment]
还不支持
