### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.img_hash'; 'cv2' is not a package

### ISSUE THREAD

**Issue by JMBanDao** [NateScarlet/auto-derby#367]
ModuleNotFoundError: No module named 'cv2.img_hash'; 'cv2' is not a package

**Comment by NateScarlet** [comment]
[FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#modulenotfounderror-no-module-named-xxx)

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
