### ISSUE TITLE
无法正常识别到比赛

### ISSUE THREAD

**Issue by kafu0611** [NateScarlet/auto-derby#372]
log：[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/9667003/auto_derby.log)
debug：https://1drv.ms/u/s!Ahiyss4uSuRDv9ZhmU39p6qYiGaviQ?e=vnc9et

![last_screenshot](https://user-images.githubusercontent.com/10711790/192833469-b7eeb29c-cf8f-47ab-9b73-106ca070f6fa.png)

**Comment by Small-Ku** [comment]
看log一直在重複`auto_derby.template:197: no match: tmpl=(tmpl<single_mode_training_confirm.png>,)`
這是在腳本要進訓練時，按到比賽那邊了吧
`INFO  [2022-09-29 01:20:24]:auto_derby.scenes.scene:40: enter: single-mode-command -> single-mode-training`
這句看起來就是要進訓練的樣子

**Comment by kafu0611** [comment]
> 看log一直在重複`auto_derby.template:197: no match: tmpl=(tmpl<single_mode_training_confirm.png>,)` 這是在腳本要進訓練時，按到比賽那邊了吧 `INFO [2022-09-29 01:20:24]:auto_derby.scenes.scene:40: enter: single-mode-command -> single-mode-training` 這句看起來就是要進訓練的樣子

其实我也一直这样以为，但是最近几次训练都是在这里卡住了，没有什么对策所以回报了

**Comment by kafu0611** [comment]
又出现了类似的情况
log：[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/9701918/auto_derby.log)
debug：https://1drv.ms/u/s!Ahiyss4uSuRDv9cTq9bvX-zP-G33Lg?e=4U6QRL
![last_screenshot](https://user-images.githubusercontent.com/10711790/193710451-9ce4a150-dc44-4491-ab02-ea2e2236bdfe.png)

**Comment by kafu0611** [comment]
类似的情况
log：https://1drv.ms/u/s!Ahiyss4uSuRDv9gcp75biRYXtnSFLw?e=nqQUaP
debug：https://1drv.ms/u/s!Ahiyss4uSuRDv9gbdxWKQH3JyF7-aA?e=LLQnex
![last_screenshot](https://user-images.githubusercontent.com/10711790/194468110-e7264c08-72f2-4b5c-af18-e6f352e9e299.png)
