### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by qwsdfvbnm** [NateScarlet/auto-derby#374]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/10521354/launcher.log)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/10521361/auto_derby.log)
[debug.zip](https://github.com/NateScarlet/auto-derby/files/10521362/debug.zip)

**Comment by Small-Ku** [comment]
見 #270 #132
此外可參閲 [FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E4%B8%AD%E6%96%87%E7%89%88%E8%AF%86%E5%88%AB%E5%87%BA%E9%94%99) #332 #330
