### ISSUE TITLE
反检测

### ISSUE THREAD

**Issue by Pamirmeow** [NateScarlet/auto-derby#4]
是否会加入随机休眠时间或是随机偏移鼠标位置之类的反检测功能呢, 刚刚我在测试程序的时候似乎被游戏检测出来了:q

**Comment by NateScarlet** [comment]
我没遇到啊 被检测到是什么效果

**Comment by Pamirmeow** [comment]
> 
> 
> 我没遇到啊 被检测到是什么效果

先是断连了两次, 脚本尝试连接, 然后弹了一个操作异常之类的窗口, 不是常见的网络错误窗口, 但我忘了截图了. 明天我再试试能不能在触发这个窗口.

**Comment by Pamirmeow** [comment]
找到原因了, 应该是我这边自己改文件的问题, 和auto_derby没啥关系, 抱歉打扰了

**Comment by NateScarlet** [comment]
现在客户端会回传按钮点击位置

1.26.3 的所有点击都改成随机了
