### ISSUE TITLE
关于自动养马的一些疑问

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#40]
### 部分问题是基于下面的文档
[ウマ娘育成理論 【汉化 by 天祈穹】.pptx](https://github.com/NateScarlet/auto-derby/files/6641563/by.pptx)
#### 看了上面的文章之后觉得定向养成确实很强！
结合自己目前使用脚本的体验，感觉定向性不是很强，即使用了3速3力的支援卡，也会在自动养成的时候把其他属性拉的很高。
- 是否可以在未来的版本中增添定向养成呢？优先拉取某X个属性到指定等级，如速A，耐A，然后再提升其他属性？或者提升X个属性的训练优先度？
- 在养成开始的时候选择自己的跑法偏好，如逃/追/先行
#### 在ura前进行技能升级 ~~已经在ura的总决赛上扑街了5、6次的人这样说到。~~
- 在ura前对技能进行升级可以在一定程度上提高ura的胜利机会，特别是在用了几次闹钟后还发现是2着的时候整个人都傻了:skull:
- 可以像对事件的选择一样，检测到ura比赛前提示技能升级，手动升级之后在terminal中直接敲回车继续脚本运行。
- 当然也可以直接敲回车然后跳过技能的升级。
#### 限时商店买空  ~~PCR后遗症让我已经无金币去升级支援卡~~
- 像题目中提到的一样，买空限时商店会导致金币啪就没了，导致没办法对支援卡进行升级。
- 在以后的版本中会增添是否买空的选项吗？
- 是否会支持仅购买马娘碎片/指定物品（如鞋子/闹钟）？
#### 对生涯中对粉丝要求有规定的马娘的养成效果很差
- ~~说的就是你ハルウララ~~
- 除了上面这个比较极端的例子，自动养成的过程中也会出现因为粉丝数目不够而出现脚本停止的情况。会在以后的版本中进行优化吗？
  - 直接跑比赛最上面的（双圈机率大）
  - 跑粉丝数多的，需要跑的总场数小
#### 跑法自动选择
- 除了出现**结果预见**~~好像是这个吧我日语真的好差~~的时候其他情况好像不能进行跑法的优选？
- 在跑法双A的情况下是怎么决定选择的呢？是根据人数？场地？还是什么？
- 在ura的时候（默认满闹钟，即可以使用4次），能否在出现双A跑法时在首选跑法跑3次未成功选择另一种跑法？
#### 事件选择
- 事件选择的结果是每个马娘不同还是只要是碰到相同事件就需要手动选择呢？
- 即使是相同的马娘选择的跑法/体力不同对事件的选择倾向也会不同。
#### 手机adb模式支持？
- 使用手机adb获取屏幕截图然后模拟点击，就可以把电脑空出来干别的了。
- 主要是现在的运行模式鼠标来回点击会造成打字/看视频的问题。

**Comment by Splendent** [comment]
手機自動點擊的話Robotmon不錯:P

**Comment by fatinghenji** [comment]
> 手機自動點擊的話Robotmon不錯:P

去搜索了下，每太弄明白怎么和现有的这个项目进行联动。
