### ISSUE TITLE
滿數值(MAX)辨認問題 

### ISSUE THREAD

**Issue by Splendent** [NateScarlet/auto-derby#41]
看起來是滿數值時的MAX/數字切換會造成OCR辨認失敗；
目前先把它設成9讓他暫且跑得過
第一次發生
`max_WITHOUT_DEBUG`
![螢幕擷取畫面 2021-06-12 115127](https://user-images.githubusercontent.com/3349355/121764563-7cc89900-cb77-11eb-946c-4cb736d20229.jpg)

第二次發生
`1000_WITH_DEBUG`
![螢幕擷取畫面 2021-06-12 120736](https://user-images.githubusercontent.com/3349355/121764566-84883d80-cb77-11eb-9f12-aa28cb2fd35b.jpg)
![last_screenshot local](https://user-images.githubusercontent.com/3349355/121764568-85b96a80-cb77-11eb-8d29-dad61961c1ad.png)

**Comment by NateScarlet** [comment]
啊这 我自己都没养成到过max

最后max截图糊了是动画效果？

**Comment by Splendent** [comment]
對，他會在1200跟MAX之間切換

> 啊这 我自己都没养成到过max
> 
> 最后max截图糊了是动画效果？

**Comment by NateScarlet** [comment]
感觉可以用区域内内有没有金色来判断是否MAX 不过过渡的每个阶段各来一张样本才好取色

我先用这一张加一下

**Comment by NateScarlet** [comment]
你发的这一张测试通过了 如果还出错发图我加更多测试
