### ISSUE TITLE
支持自动参加适应性合适的比赛

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#46]

**Comment by fatinghenji** [comment]
可以参考下这个项目的比赛计时。
[UmaUmaCruise](https://github.com/amate/UmaUmaCruise)

**Comment by NateScarlet** [comment]
什么叫比赛计时

**Comment by fatinghenji** [comment]
> 什么叫比赛计时

是我表述不清楚
他那个软件支持选择自己想跑的比赛，并在时间到的时候进行提醒。
项目主页有截图的，支持距离，草地/泥地，比赛等级的筛选。
