### ISSUE TITLE
漢字識別錯誤 

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#49]
![圖片](https://user-images.githubusercontent.com/16464896/121855732-441af200-cd26-11eb-99a4-3d3892730644.png)
貌似札幌只識別到了偏旁
圖中8007c00ff87ff8fff8fff83ff01ff03ffcfffe7ffc0f800f800f800f800f8007也附在這裏了
![dbb92c0f76b671596a030f7391c3c21b](https://user-images.githubusercontent.com/16464896/121856253-e20ebc80-cd26-11eb-8148-723f693f346f.png)

**Comment by NateScarlet** [comment]
需要全图 发一下 last_screenshot.local.png

**Comment by Small-Ku** [comment]
好的
![last_screenshot local](https://user-images.githubusercontent.com/16464896/121856796-7bd66980-cd27-11eb-89f4-799332d84c5f.png)
