### ISSUE TITLE
第二步出错

### ISSUE THREAD

**Issue by SuperCirno** [NateScarlet/auto-derby#5]
提示
usage: __main__.py [-h] job
__main__.py: error: the following arguments are required: job
请问大佬怎么解决?

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby/blob/3c40c967ca5c3e3539a02dad8907e39fa37fd395/auto_derby/__main__.py#L24-L30

你要指定要执行的任务

**Comment by SuperCirno** [comment]
原来如此,感谢
