### ISSUE TITLE
三次連續出走的警告

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#50]
貌似在遇到連續出走的警告後，雖然腳本會按下取消，但是會在選擇屬性/休息之後，仍舊尋找single_mode_race_detail_button.png。
一次是取消後休息，一次是訓練，兩次log都在這裏了：https://gist.github.com/Small-Ku/b72d59f4745196631acb76bbc8ba26c9

**Comment by NateScarlet** [comment]
是我少写个 return
