### ISSUE TITLE
最新版的一些问题

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#53]
在体力明显不足的情况不选择休息而选择跑比赛，是否会影像育成结果？
体力剩余情况如下图所示，系统未选择休息而是选择跑比赛。

![last_screenshot local](https://user-images.githubusercontent.com/37131177/121887389-3fb40080-cd49-11eb-9f26-546389a6c533.png)

**Comment by NateScarlet** [comment]
体力不影响比赛成绩 反而是低体力跑比赛更赚 因为体力无法低于0
