### ISSUE TITLE
OCR问题

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#54]
![last_screenshot local](https://user-images.githubusercontent.com/37131177/121896866-5ad83d80-cd54-11eb-8efd-a1f13576b24f.png)
![image](https://user-images.githubusercontent.com/37131177/121896874-5dd32e00-cd54-11eb-9d57-6138e2d26a91.png)
这个字无法被打出。可能是windows自带字库的原因。
参看这个解答[请问谁能打出日本汉字的“直”(下面是竖折的)？](https://zhidao.baidu.com/question/1895999282044672740.html)

**Comment by NateScarlet** [comment]
chokusenn 直線　你把中文的直用日文字体应该就会变成竖折
打出也没用 因为我识别没识别直线跑道的比赛 需要我改一下
