### ISSUE TITLE
[DEV]识别错误

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#55]
![last_screenshot local](https://user-images.githubusercontent.com/37131177/122066648-824b0b00-ce25-11eb-96ac-facd151ade75.png)
![image](https://user-images.githubusercontent.com/37131177/122066664-870fbf00-ce25-11eb-921e-8bdf5c9ac464.png)

**Comment by NateScarlet** [comment]
你手动截图大小不对 发一下 last_screenshot.local.png

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/122069113-81b37400-ce27-11eb-8a41-9b730c48f958.png)
上传的文件就是自动生成的。

**Comment by NateScarlet** [comment]
那你黄边应该是同时在录屏导致的

**Comment by fatinghenji** [comment]
确实是在录屏，是因为录屏的原因吗？

**Comment by fatinghenji** [comment]
确实是在录屏，是因为录屏的原因吗？

**Comment by NateScarlet** [comment]
应该不是 我还测

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/122083966-ef659d00-ce33-11eb-8dfb-46c9f6a716a8.png)
胡来的左手2

**Comment by NateScarlet** [comment]
本来只利用白轮廓的 现在连深橙色轮廓都用上了 应该不会再有类似问题了
再有识别失败的话应该会变成缺字 不导致停止而是导致训练评分错误
