### ISSUE TITLE
DMM 版使用后台截图

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#59]
![图片](https://user-images.githubusercontent.com/21083014/122211683-951f1780-ced9-11eb-8387-5e813267e672.png)

发现虽然 bitblt 后台截图不行 但是管理员权限下赛马娘支持 [PrintWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-printwindow)

**Comment by fatinghenji** [comment]
![image](https://user-images.githubusercontent.com/37131177/122385078-f0ffa400-cf9e-11eb-9c9d-a340113830e2.png)
不知道和楼主说的是不是同一个东西，这个问题我在直播马娘的时候也遇到了，选择bitblt获取不到屏幕。

**Comment by NateScarlet** [comment]
就是同一个东西 这个不支持游戏截图
本来我想说用和 obs win10 以上一样的方法的 然后发现仅截图不录视频可以用兼容性更好的这个

**Comment by NateScarlet** [comment]
后台截图比全屏截图裁剪快 20 倍

```
pil_crop: 0.3787 print_window: 0.0197
```

应该是屏幕越大截图方法越慢

**Comment by fatinghenji** [comment]
好家伙！期待后台截图的版本
