### ISSUE TITLE
训练查看效果时有时候点不到训练 影响选择

### ISSUE THREAD

**Issue by SuperCirno** [NateScarlet/auto-derby#6]
选择训练项目的时候有时候会点不到然后就去点下一个,好像会影响选择

**Comment by NateScarlet** [comment]
会先看所有训练的效果然后最后再选择 不知道是不是你说的点不到

**Comment by SuperCirno** [comment]
是,全部看一遍的时候,经常会漏掉几个没点到

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby/blob/2d3955b912120dc57518d78445f7aafd7c51e568/auto_derby/action.py#L121

可能是拖动太快了 可以尝试增加一下默认duration 或者在 drag 结束后加个 time.sleep 测试下

我昨晚增加过拖动速度 跑了几次没出问题

**Comment by SuperCirno** [comment]
好的

**Comment by SuperCirno** [comment]
调到0.03是没问题了,不过那个输入弹出窗口文字,根本看不清是啥啊
![image](https://user-images.githubusercontent.com/78606692/120189334-c9dc6f00-c249-11eb-8b57-bf674fc0f860.png)

**Comment by NateScarlet** [comment]
你用的不是最新版吧 现在的版本应该不会弹图啊
中途我为了调试有的提交含弹图的命令没删

**Comment by SuperCirno** [comment]
我用的是昨晚最后的版本,我重新整个看看

**Comment by NateScarlet** [comment]
不对 你的意思不是弹太快 而是看不清这个吗 这是应该是个加号

**Comment by NateScarlet** [comment]
不过残缺的说明提取有问题 最好把游戏截图给我我调试下

**Comment by SuperCirno** [comment]
游戏截图?

**Comment by NateScarlet** [comment]
出现问题的时候把游戏画面整个给我 这样我才能重现问题

https://github.com/NateScarlet/auto-derby/blob/c5966f61d41e2555c16e6b8e887105c3635539a6/auto_derby/jobs/test_data/nurturing_comand_scene_issue7.png

**Comment by SuperCirno** [comment]
ok等我再开一把

**Comment by SuperCirno** [comment]
明天吧,今天没空了
