### ISSUE TITLE
清空商店失敗

### ISSUE THREAD

**Issue by Splendent** [NateScarlet/auto-derby#70]
commit 7693ff8fbea66bd876a5c182c29726b63b6285cb
env: android - noxplayer / 1080x1920

log共兩次，搬商店時會無法完成，目測現象是drag後的點擊app沒辦法立刻回應而造成後續的狀況出錯
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6682553/auto_derby.log)
[auto_derby.1.log](https://github.com/NateScarlet/auto-derby/files/6682555/auto_derby.1.log)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/6682558/launcher.log)
![last_screenshot local](https://user-images.githubusercontent.com/3349355/122678820-e7827000-d21a-11eb-8e4f-b1e8503419db.png)

**Comment by Splendent** [comment]
直覺解法是把 sleep 拉高 🐒 
但是我現在刷不出商店沒法測 😆 
https://github.com/NateScarlet/auto-derby/blob/7693ff8fbea66bd876a5c182c29726b63b6285cb/auto_derby/clients/adb.py#L120

**Comment by Small-Ku** [comment]
auto_derby.1.log 的這個bug我也經常遇到，我剛剛試用 #72 的方法把 18 行的 `action.wait_image(templates.CLOSE_NOW_BUTTON)` 換成:
```
        for _, pos in action.match_image_until_disappear(templates.CLOSE_NOW_BUTTON):
            action.click(pos)
            time.sleep(0.5)
```
就解決了（雖然只試了一次限時商店）

**Comment by Splendent** [comment]
> 直覺解法是把 sleep 拉高 🐒
> 但是我現在刷不出商店沒法測 😆
> https://github.com/NateScarlet/auto-derby/blob/7693ff8fbea66bd876a5c182c29726b63b6285cb/auto_derby/clients/adb.py#L120

改成sleep 1.0 完全沒有用!! 看來是我理解有誤
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6683759/auto_derby.log)

**Comment by Small-Ku** [comment]
把這兩行都改成還沒按下去就一直點就好？
https://github.com/NateScarlet/auto-derby/blob/1e96017019501b4bc61e7054e474f35cd73af9a7/auto_derby/jobs/limited_sale.py#L14
https://github.com/NateScarlet/auto-derby/blob/1e96017019501b4bc61e7054e474f35cd73af9a7/auto_derby/jobs/limited_sale.py#L18

**Comment by NateScarlet** [comment]
你怎么判断还没按下去 重复发可能导致点到不该点的地方

是不是 drag 后的点击联网时间比较长导致的

**Comment by NateScarlet** [comment]
我知道了

`match_image_until_disappear` 有个我记得明明修过的bug

它在操作之后应该重新截图 而不是继续用之前截图上的下一个匹配

**Comment by NateScarlet** [comment]
主分支上修了

https://github.com/NateScarlet/auto-derby/blob/1e96017019501b4bc61e7054e474f35cd73af9a7/auto_derby/action.py#L37-L40

开发分支上没修

https://github.com/NateScarlet/auto-derby/blob/a93c86144332344fe451100d9d5a859234aace33/auto_derby/action.py#L38-L40

**Comment by Splendent** [comment]
應該是解掉了
以commit 2054a59e5d6ab22606b1f3cae3c28a608e8d71b6 為基礎的版本測試的

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6690517/auto_derby.log)
![last_screenshot local](https://user-images.githubusercontent.com/3349355/122851939-6625fd00-d342-11eb-8ebc-17ad9f6214f8.png)
