### ISSUE TITLE
在选择比赛的时候滑动事件会变成点击事件

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#71]
报告一个新bug
在选择比赛的时候滑动事件会变成点击事件。log如下：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6682423/auto_derby.log)
手动adb执行`adb shell input swipe 232 1391 232 1353 200`同样为点击，应该不是触摸时间或者延迟的问题吧。
感觉依旧是超出了屏幕的最大值

_Originally posted by @fatinghenji in https://github.com/NateScarlet/auto-derby/issues/69#issuecomment-864555012_

**Comment by NateScarlet** [comment]
这个坐标在1080x1920的范围内 可能200毫秒算作了点击

**Comment by fatinghenji** [comment]
我去调整下时间试试

**Comment by fatinghenji** [comment]
不是时间的问题，是滑动距离的问题。
1391和1353太近了，被识别成点击了
`adb shell input swipe 232 1391 232 1285 200`这个可以正常滑动。

**Comment by fatinghenji** [comment]
需要我改动哪里的代码才可以正常使用呢？

**Comment by Small-Ku** [comment]
我猜是dy的部分?
https://github.com/NateScarlet/auto-derby/blob/a93c86144332344fe451100d9d5a859234aace33/auto_derby/jobs/nurturing.py#L48-L52

**Comment by fatinghenji** [comment]
> 我猜是dy的部分?
> https://github.com/NateScarlet/auto-derby/blob/a93c86144332344fe451100d9d5a859234aace33/auto_derby/jobs/nurturing.py#L48-L52

没太看懂应该怎么修改

**Comment by NateScarlet** [comment]
`rp.vector(-50, 466)` 代表相对于466宽的屏幕向上滑动50像素

不过不能调太大 一次滑动不能超过一个比赛的高度 不然会漏比赛

**Comment by NateScarlet** [comment]
奇怪的是相对466的屏幕都是50像素了 相对于你1080的屏幕为啥会只有40

**Comment by NateScarlet** [comment]
你用的是你自己改过的版本？ 这里的时长不应该是200毫秒

重置一下试试

**Comment by fatinghenji** [comment]
> 你用的是你自己改过的版本？ 

应该不是吧……我也说不好。
>重置一下试试

下载了最新的版本，在跑了，看看还有没有问题。

**Comment by NateScarlet** [comment]
我的也出现了 但是坐标是对的

```
DEBUG [2021-06-22 03:42:16]:auto_derby.clients.adb:114: drag: input swipe 366 1390 366 1622 100
```

我加大时长看看
