### ISSUE TITLE
[DEV]自动育成时发生错误自动退出

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#75]
log如下：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6686714/auto_derby.log)
最后的截图如下：
![last_screenshot local](https://user-images.githubusercontent.com/37131177/122765155-ca10dd00-d2d2-11eb-9c20-4f57850b8a23.png)

**Comment by NateScarlet** [comment]
为啥你这个日志里面没有点击命令 什么版本

**Comment by fatinghenji** [comment]
现在用的版本是：c6b7141

**Comment by NateScarlet** [comment]
不对 有点击命令 但是在截图之前的点击

**Comment by NateScarlet** [comment]
是不是你帧率太低 点击之后生效超过0.5秒

**Comment by NateScarlet** [comment]
https://github.com/NateScarlet/auto-derby/blob/5f65e9d6aa6d63a6a68f35c91b32872059059e15/auto_derby/clients/adb.py#L58
加大这个

**Comment by fatinghenji** [comment]
帧率应该不会吧，一会我开个帧率显示试试

**Comment by NateScarlet** [comment]
那看来所有点击都要加等待当前点击图片消失 不然点了还没得及起效果又被截图匹配到就会出错

**Comment by fatinghenji** [comment]
有没有可能是因为我用的死无线adb，网速不稳定的问题？

**Comment by NateScarlet** [comment]
网速越慢这错误越不可能出现 操作快于你游戏导致的

**Comment by NateScarlet** [comment]
我之后把fps限制到20重新调试

**Comment by fatinghenji** [comment]
更新到b62e59c了，我试试怎么样

**Comment by fatinghenji** [comment]
问题依旧存在？
现在是卡在跑完比赛的结算了。
![last_screenshot local](https://user-images.githubusercontent.com/37131177/122772102-9e452580-d2d9-11eb-9287-5d31f01c630f.png)
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6687014/auto_derby.log)

**Comment by fatinghenji** [comment]
手动将等待时常改为1.0，卡比赛的问题依旧存在

**Comment by NateScarlet** [comment]
这个是我改成不用固定时间导致的bug 在你说的时候就已经修了 2054a59e5d6ab22606b1f3cae3c28a608e8d71b6
