### ISSUE TITLE
要不要以賽事Banner取代OCR？

### ISSUE THREAD

**Issue by hoho97** [NateScarlet/auto-derby#76]
目前選擇賽事時的OCR不中需要手動輸入的情況還挺多的
而且有時輸錯了就會直接炸了挺麻煩的，比如日文的内和中文的內就是不一樣的字符

解包能得到類似這種的圖，程式識別度感覺應該會更高？
![thum_race_rt_000_1003_00](https://user-images.githubusercontent.com/18360960/122975300-cad66b80-d3c5-11eb-90e7-2b89152a178c.png)

**Comment by NateScarlet** [comment]
我平均一个新角色多识别不到2个字 不知道你挺多的是什么情况

日文的内和简体的内是同一个字 而且输入日文请用日文输入法

不会解包 你可以自己实现然后发PR

**Comment by NateScarlet** [comment]
模版识别和OCR的像素量不是一个数量级 何况你还要轮询所有比赛 时间复杂度从O(n) 变成 O(n^2)

**Comment by NateScarlet** [comment]
如果你用正确的 ocr_labels.json 识别出错误的个结果 那是Bug请发单独 issue
现有方法准确度应该是 100% 不存在更高

**Comment by Small-Ku** [comment]
比賽的話，在 single_mode_races.json 中找字複製吧
