### ISSUE TITLE
生病時不會去保健室治病

### ISSUE THREAD

**Issue by hoho97** [NateScarlet/auto-derby#79]
剛運氣不好得睡癌了，發現不會去治病

看了一下源碼，發現有源碼檢查生病，不過看template那邊好像還沒有生病的素材
https://github.com/NateScarlet/auto-derby/blob/0439139b28323acca633989651b9a59c81b99cfb/auto_derby/single_mode/context.py#L402

要不下次生病的話我截個圖提供素材？

**Comment by NateScarlet** [comment]
训练分低于期望值才会休息 休息的时候如果可以保健室就会保健室
负面状态不用急着消掉 很有可能几个回合都没效果

**Comment by NateScarlet** [comment]
截图的话截全图 我可以加测试用例
现在默认debug是开的 截图自动保存为 last_screenshot.local.png

**Comment by hoho97** [comment]
> 训练分低于期望值才会休息 休息的时候如果可以保健室就会保健室
> 负面状态不用急着消掉 很有可能几个回合都没效果

感覺睡癌還是得快點治的，體力跟心情都扣的機率體感不低

倒是肌無力，吃胖這種會自己好的優先級可以低些

**Comment by NateScarlet** [comment]
扣体力导致训练分下降 自然就去治了

**Comment by hoho97** [comment]
> 截图的话截全图 我可以加测试用例
> 现在默认debug是开的 截图自动保存为 last_screenshot.local.png
這把中了
![last_screenshot local](https://user-images.githubusercontent.com/18360960/123507823-3d816880-d69e-11eb-89d4-f1d37502b0cc.png)

**Comment by hoho97** [comment]
> 截图的话截全图 我可以加测试用例
> 现在默认debug是开的 截图自动保存为 last_screenshot.local.png

有睡癌的圖了
![last_screenshot local](https://user-images.githubusercontent.com/18360960/123915322-f43d5b80-d9b2-11eb-9d31-8cc49faf36b2.png)

**Comment by NateScarlet** [comment]
你这个图好像动画没播完 导致所有位置比其他的样本低2像素匹配不上
