### ISSUE TITLE
[dev]育成因粉丝数不够而失败

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#80]
~两战两胜怎么就养完了~
log文件如下：
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6706670/auto_derby.log)
用的默认参数，adb调试养马。
父母及支援卡：
![image](https://user-images.githubusercontent.com/37131177/123211093-8ba73800-d4f5-11eb-8f44-2437bc1978a4.png)
离谱的2战2胜：
![image](https://user-images.githubusercontent.com/37131177/123211133-9b268100-d4f5-11eb-9e95-34ca5d5f5418.png)
是不是识别错了点到育成结束什么的？

**Comment by NateScarlet** [comment]
目标粉丝数不够
![image](https://user-images.githubusercontent.com/21083014/123212395-4f74d700-d4f7-11eb-9b52-eccc0f1283da.png)
https://github.com/NateScarlet/auto-derby/blob/0439139b28323acca633989651b9a59c81b99cfb/single_mode_races.json#L7549

**Comment by NateScarlet** [comment]
我开发分支昨天有更新粉丝数不够的逻辑 你更新再试

**Comment by NateScarlet** [comment]
不行的话你就带个加比赛粉丝数的支援卡

**Comment by fatinghenji** [comment]
用的应该就是昨天更新的dev分支。
在粉丝数不够的情况下是先比赛发现不能跑过然后训练吗？

**Comment by NateScarlet** [comment]
应该是因为目标粉丝数每回合清空导致识别粉丝输不够的对话框没起到作死有

你手动删掉这一行试试 https://github.com/NateScarlet/auto-derby/blob/4bce50e627f60f6fcb6c32bdffe6ca9f80e32143/auto_derby/single_mode/context.py#L245

**Comment by fatinghenji** [comment]
> 应该是因为目标粉丝数每回合清空导致识别粉丝数不够的对话框没起到作用
> 
> 你手动删掉这一行试试 https://github.com/NateScarlet/auto-derby/blob/4bce50e627f60f6fcb6c32bdffe6ca9f80e32143/auto_derby/single_mode/context.py#L245

啊等我晚上下班再试试

**Comment by fatinghenji** [comment]
删除后问题解决

> 应该是因为目标粉丝数每回合清空导致识别粉丝数不够的对话框没起到作用
> 
> 你手动删掉这一行试试
> 
> https://github.com/NateScarlet/auto-derby/blob/4bce50e627f60f6fcb6c32bdffe6ca9f80e32143/auto_derby/single_mode/context.py#L245
