### ISSUE TITLE
有時會在選比賽那邊死循環

### ISSUE THREAD

**Issue by hoho97** [NateScarlet/auto-derby#86]
之前就發現這個問題了，今天放假開了debug來查原因

就是會掉進_handle_race的這個循環，會在選比賽的頁面一直向下滑然後點最後一個賽事的資訊

>     while True:
>         tmpl, pos = action.wait_image(
>             templates.RACE_RESULT_BUTTON,
>             templates.SINGLE_MODE_RACE_START_BUTTON,
>             templates.RETRY_BUTTON,
>         )
>         if tmpl.name == templates.RACE_RESULT_BUTTON:
>             break
>         action.click(pos)

翻查LOG後發現未勝利戰的score是最高, 應該是這樣導致了程序想找未勝利戰來跑但一直找不到～估計根本原因是沒發現已經首勝了導致ctx.is_after_winning一直是FALSE?

> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:84: expected score:	15.00
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	44.43:	Race<福島 turf 2000m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	44.43:	Race<福島 turf 2600m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	34.43:	Race<福島 turf 1800m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	24.03:	Race<福島 turf 1200m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	19.04:	Race<福島 dart 1700m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:86: score:	race:	14.03:	Race<福島 dart 1150m Not-Winning クラシック級未勝利戦>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:88: score:	training:	40.41:	Training<lv=5 gut=18 pow=9 spd=7 ski=3>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:88: score:	training:	40.14:	Training<lv=5 wis=23 spd=6 ski=6>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:88: score:	training:	25.65:	Training<lv=5 spd=19 pow=9 ski=2>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:88: score:	training:	25.63:	Training<lv=5 pow=17 sta=12 ski=2>
> INFO  [2021-06-30 12:45:20]:auto_derby.jobs.nurturing:88: score:	training:	24.51:	Training<lv=5 sta=18 gut=7 ski=2>

附上我的賽程跟完整log，有試過把名字含未勝利的賽事設成0分但沒有生效的樣子。
[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/6738161/auto_derby.log)
[oguri_race_score.zip](https://github.com/NateScarlet/auto-derby/files/6738164/oguri_race_score.zip)

**Comment by NateScarlet** [comment]
把粉丝数界面的截图发一下  https://github.com/NateScarlet/auto-derby/blob/master/auto_derby/single_mode/test_data/class_detail.png

现有测试用例都是通过的 需要加新测试
https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/single_mode/context_test.py#L228

**Comment by NateScarlet** [comment]
> 把名字含未勝利的賽事設成0分

你代码写反了 `self.name in "未勝利"`  是 未胜利包含整个比赛名称 而不是比赛名称包含未胜利

不过就算写对了也没用，根据日期选比赛时会无视前提条件不符合的比赛，所以设成 0 相当于禁用了自动出赛

**Comment by hoho97** [comment]
> 把粉丝数界面的截图发一下 https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/single_mode/test_data/class_detail.png
> 
> 现有测试用例都是通过的 需要加新测试
> https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/single_mode/context_test.py#L228
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/137e57dac4dabd4edce91c5db1ce3e19ba1adef8ad5416d343ca63a4ce71ccbb/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f363531353831616466373137346264626662653931393330373966396431353137383665643837613938666265626239623239343633393732306436616535622f4e617465536361726c65742f6175746f2d6465726279"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[NateScarlet/auto-derby](https://github.com/NateScarlet/auto-derby)**🐎🖥《赛马娘》（ウマ娘: Pretty Derby）辅助脚本 . Contribute to NateScarlet/auto-derby development by creating an account on GitHub.


剛剛重現了一次，但是當下的截圖我沒找著因為在無限複讀中只能強制關掉了
這截圖後來重開截的，不知道有沒有幫助。
![last_screenshot local](https://user-images.githubusercontent.com/18360960/124286021-171d6a80-db81-11eb-8bb0-cef427637de8.png)

**Comment by NateScarlet** [comment]
没用 这张图识别结果是对的

**Comment by NateScarlet** [comment]
你现在什么版本 这几天我加了很多菜单动画等待

https://github.com/NateScarlet/auto-derby/blob/fb202125e42d689b4d4458b5349566fbf53123e3/auto_derby/jobs/nurturing.py#L260

说不定你也是这个原因

**Comment by hoho97** [comment]
最近沒遇到這問題了，先close
