### ISSUE TITLE
育成小栗帽时会出现的小问题

### ISSUE THREAD

**Issue by 1246174923** [NateScarlet/auto-derby#87]
第三年如果一直训练，没跑G1，出来育成目标提醒的时候不会点掉，会卡住。有时候会没跑够比赛直接育成失败。
可不可以加上如果出现比赛提醒选择自动参赛的功能

**Comment by NateScarlet** [comment]
本来就有 目标提醒会让比赛优先于训练 如果还不去比赛说明预测比赛拿不到名次不如不跑

https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/jobs/nurturing.py#L287-L293

https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/jobs/nurturing.py#L93-L96

**Comment by 1246174923** [comment]
不是粉丝不足的目标提醒，是无法识别小栗帽的育成目标，就是那个提醒你需要赢2次G1的框不会自己点，要手动操作


INFO&nbsp; [2021-07-01 00:42:57]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:42:57]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:42:58]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:42:59]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:43:00]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:43:00]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')
INFO&nbsp; [2021-07-01 00:43:01]:auto_derby.template:197: no match: tmpl=('connecting.png', 'retry_button.png', 'single_mode_command_training.png', 'single_mode_fans_not_enough.png', 'single_mode_finish_button.png', 'single_mode_formal_race_banner.png', 'single_mode_race_next_button.png', 'single_mode_option1.png', 'green_next_button.png', 'single_mode_ura_finals.png', 'single_mode_gene_inherit.png')







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NateScarlet/auto-derby"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 凌晨1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NateScarlet/auto-derby] 育成小栗帽时会出现的小问题 (#87)





 
本来就有 目标提醒会让比赛优先于训练 如果还不去比赛说明预测比赛拿不到名次不如不跑
 
https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/jobs/nurturing.py#L287-L293
 
https://github.com/NateScarlet/auto-derby/blob/6f3e7f04793548f6a9b7f79d387d2709fcdfdc52/auto_derby/jobs/nurturing.py#L93-L96

**Comment by NateScarlet** [comment]
我没有小栗帽  做不了这功能

你可以通过插件实现遇到G1保证去 #66

**Comment by 1246174923** [comment]
ok，明白了，我明天去试试看，感谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NateScarlet/auto-derby"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 凌晨1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NateScarlet/auto-derby] 育成小栗帽时会出现的小问题 (#87)





 
我没有小栗帽  做不了这功能
 
你可以通过插件实现遇到G1保证去 #66
