### ISSUE TITLE
关于养成跑历战，如何在Plugin实现的问题

### ISSUE THREAD

**Issue by yourlies** [NateScarlet/auto-derby#91]
谢谢贡献了这么好的代码
今天偶然搜到了，花了些事件看了一下您的代码，可能有看疏漏或理解错的情况，这里我有一些疑问
q: 养成的核心逻辑应该是在这里了吧，我看了下，是只有育成目标的比赛，以及粉丝不足的情况下，才会去跑比赛么？
q: 如果我想在Plugin里实现跑历战的需求，需要如果做才能让特定日期下的case，被跑比赛catch到？

https://github.com/NateScarlet/auto-derby/blob/a5a1177d11addbb902af6488d2d94b94bd06cb45/auto_derby/jobs/nurturing.py#L271-L287

**Comment by NateScarlet** [comment]
你看漏了 是评分决定要不要比赛 甚至粉丝不足的时候如果拿不到名次都不跑比赛

https://github.com/NateScarlet/auto-derby/blob/a5a1177d11addbb902af6488d2d94b94bd06cb45/auto_derby/jobs/nurturing.py#L94-L104

参见 #89 #66
