### ISSUE TITLE
templates中的截图是如何生成的

### ISSUE THREAD

**Issue by yourlies** [NateScarlet/auto-derby#97]
有统一的生成方案吗

**Comment by NateScarlet** [comment]
直接在 960x540 的游戏画面上用截图工具截

如果要固定位置用 scripts/capture_template_position.py 配合 last_screenshot.local.png 生成位置图

**Comment by NateScarlet** [comment]
如果要生成索引文件需要装了 [gotmpl](https://github.com/NateScarlet/gotmpl) 后

运行 `make -C auto_derby/templates`

**Comment by yourlies** [comment]
好的，谢谢
